baresip/baresip

modules/speex/speex.c
As noticed by @alfredh in pull request #41, I screwed up vbr settings by forgetting to fix actual variables when copy-pasting code.
=> speex: fix config parsing

src/config.c
While at it, also make spacing of this configuration item more consistent.
=> config: mention kqueue on platforms supporting it

mk/modules.mk, modules/gtk/gtk_mod.c, modules/gtk/module.mk
This adds support for old versions of glib that don't have have GNotification (#65), by using libnotify as a fallback. However, libnotify notifications can't have buttons and so can't be used for accepting and rejecting incoming calls. So a new submenu is added here for each current incoming call, so that the user can accept or reject a call using the menu instead of by using the notification.
=> More ways to answer calls in GTK+

Makefile
Call `$(TEST_BIN)` executable during execution of `test` target.
=> test: do actual testing

modules/gtk/module.mk
Thankfully GNU make has `!=` operator.
=> gtk: don't run pkg-config on every operation

modules/directfb/module.mk, modules/gst/module.mk, modules/gst1/module.mk, modules/gst_video/module.mk, modules/gst_video1/module.mk, modules/rst/module.mk
Output of `pkg-config` shouldn't change during build, so it is sufficient to run it once per check.
This pull request is follow-up to #80.
=> Get rid of VAR += `pkg-config ...` idiom

mk/modules.mk, modules/directfb/module.mk, modules/gst/module.mk, modules/gst1/module.mk, modules/gst_video/module.mk, modules/gst_video1/module.mk, modules/gtk/module.mk, modules/rst/module.mk
Followup to #80 and #81. This time using `shell` macro.
=> build infrastructure: get rid of " = `pkg-config ...`" idiom

Makefile, mk/mod.mk
In *silent* mode build infrastructure prints only short messages in format:
```
TOOL	filename
```
and toolchain's warnings.  In *verbose* mode it additionally echoes exact commands including all compiler and linker flags.  By default baresip is built in *silent* mode (as before this commit); *verbose* mode can be set either by unsetting `HIDE` variable (running `make HIDE=`) or by setting `V` variable to any value (eg. `make V=1` or `make V=yes`).
=> build infrastructure: silent and verbose modes

modules/daala/decode.c
Commit [dd604a08](https://github.com/xiph/daala/commit/dd604a08694fa70b28b0f0888a83dede78c1ee90) to daala split `daala_decode_packet_in()` into `daala_decode_packet_in()` and `daala_decode_img_out()`. This diff is supposed to adapt *daala* module to this change.
=> daala: recover after recent api change

modules/gtk/gtk_mod.c
This diff makes gtk module compile with OpenBSD's stock gcc.
=> gtk: make module ANSI C compliant

modules/sndio/sndio.c
As discussed in #101, unintialized `par` causes issues.
=> sndio: initialize "par" to NULL

include/baresip.h, modules/amr/amr.c, modules/bv32/bv32.c, modules/codec2/codec2.c, modules/g711/g711.c, modules/g722/g722.c, modules/g7221/g7221.c, modules/g726/g726.c, modules/gsm/gsm.c, modules/ilbc/ilbc.c, modules/isac/isac.c, modules/l16/l16.c, modules/mpa/mpa.c, modules/opus/opus.c, modules/silk/silk.c, modules/speex/speex.c, src/audio.c, test/call.c
All, @choene please review and test this patch.
The patch splits the "srate" parameter of struct aucodec into 2 parts; srate and crate.
The srate is the Audio sample-rate for the DSP, the crate is the RTP Clock rate.
Most audio codecs will use exactly the same value here. The exception is e.g G.722 and MPA.
For example G.722 has 8000 Hz and 16000 Hz:
https://tools.ietf.org/html/rfc3551#section-4.5.2
```
Even though the actual sampling rate for G.722 audio is 16,000 Hz,
the RTP clock rate for the G722 payload format is 8,000 Hz because
that value was erroneously assigned in RFC 1890 and must remain
unchanged for backward compatibility.  The octet rate or sample-pair
rate is 8,000 Hz.
```
the goal is to make audio.c agnostic to these codec details.
=> aucodec: split srate into srate and crate (Clock Rate)

mk/modules.mk
GLib 2.32 is needed for some things: https://developer.gnome.org/gio/stable/api-index-2-32.html
#122
=> Build gtk module only with new enough glib

modules/sndio/sndio.c
Sndio provides value of buffer size (`par->bufsz`) that is equal to audio delay
in audio driver.  Using buffer under this size causes underruns without reducing delay.  As I get it, using `par->bufsz` for buffer size ensures minimal delay while saving audio driver from additional buffer management.
=> sndio: use driver-suggested buffer size

modules/avformat/avformat.c
Due to warning message:
`Using network protocols without global network initialization. Please use avformat_network_init(), this will become mandatory later.`
(I've got following warning when I use avformat library as video RTSP source - SIP call initialization)
=> avformat network initialization

.travis.yml
Test on both Ubuntu and OS X, with both `clang` and `gcc`.  While at it, make build verbose and print build info.
Workarounds bugs that I hit and had to work around:
* `ccache` does not play nice with `clang`; disable `ccache`;
* build infrastructure requires compiler and all other tools in `PATH` even for `install` target alone;  pass user's `PATH` to `sudo` commands.
=> More diverse testing

modules/snapshot/snapshot.c
Module `snapshot` was not updated after a4798e3cdb0b3758c7f11f289c28663e65da6d6c and e3ecbddba06f91c3ef5b3cd8305a8f2fdb6c9cde.  Right now it does not build.
(*Referencing PR #173 as a reminder that the issue should probably be solved before the release.*)
=> snapshot: fix after changes in command API

src/config.c
Add missing modules to configuration file generator.  I did not add deprecated and obscure modules.
(*Referencing PR #173 because it would make sense to merge this before release.*)
=> config: list several modules that were missing

src/config.c
Currently module path detection logic uses `PREFIX` if it is defined, and falls back to Linux locations if it is not.  This PR brings the same behavior to the other absolute path in configuration file - `audio_path`.
(*Referencing PR #173 because this PR should probably be merged before 0.5.0 release.*)
P.S.: Sorry for not including this with PR #175.
=> Consistently use PREFIX in absolue paths

modules/v4l2/v4l2.c
These are defined in `rem`'s `rem_vid.h`, and there are corresponding definitions in V4L2 API, but they somehow did not make to `v4l2` module.
(*Referencing PR #173 as a reminder that this PR might be merged before release is cut.*)
=> v4l2: pick up VID_FMT_NV12 and VID_FMT_NV21 formats as well

modules/v4l2/v4l2.c
Libv4l2 appends emulated formats to the end of the list, so there is no real chance that native format will follow if we already stumbled upon emulated one.
Currently this change only saves one ioctl call: baresip supports only one of emulated formats, and it comes second from the end of the list.  Still libv4l2 tends to sort formats according to conversion efficiency and amount of data loss, so if at some point in future they add another emulated format that librem supports, with current algorythm baresip will fall throught the list until it picks the worse format.
=> v4l2: don't check for native/emulated format

modules/avcodec/encode.c
ffmpeg 3.2 renames nvenc_h264 to h264_nvenc & drops a deprecated warning when nvenc_h264 is used.
The patch updates the nvenc_h264 section to set the encoder options on both possible selections with ffmpeg >=3.2. Additionally the debug messages are more general.
=> prepare nvenc_h264 code for ffmpeg >= 3.2.x

modules/httpd/httpd.c, src/cmd.c
changed the parsing of the command that an '%20' in an url is equivalent
to an whitespace.
=> enabled long commands on httpd module

modules/v4l2_codec/v4l2_codec.c
Correcting a bug making impossible to select the video device in v4l2_codecs
=> Video device selection bug in v4l2_codecs

mk/modules.mk, modules/omx/README, modules/omx/module.c, modules/omx/module.mk, modules/omx/omx.c, modules/omx/omx.h
As previously announced on the Mailing list, this patch introduces support for hardware-accelerated scaled video playback on the Raspberry Pi. It is not very well tested, and breaks for some resolutions, but otherwise running stable.
The module is named 'omx', due to the "OpenMAX Integration Layer".
In the future, it might support the native video codec (h.264), and video capture (Pi Camera).
It is probably not compatible with OpenMAX on other platforms like Android, without further changes.
Cheers,
Jonathan
=> Video Display Support for Raspberry Pi

src/play.c
This allows to play call progress tones having defined intervals without introducing redundancy in the audio file. This is especially useful for a continuous dial tone or busy tones with a short pause between tones.
=> Add gapless repeat for tone playback

src/call.c
The handler of the progress event may want to access the audio object of the call (for example to change the audio device). This is only possible if the media stream has already been started.
=> Call event handler for call progress/ringing after media has been set up

src/audio.c
For telephone events the same clock rate as for audio has to be used, as both share the timestamp base.
This depends on the corresponding pull request for libre.
=> Set correct clock rate for telephone events

README.md, include/baresip.h, src/audio.c, src/config.c, src/core.h, src/stream.c, src/video.c, test/call.c, test/main.c, test/test.h
https://tools.ietf.org/html/rfc6464
requires libre from this commit or later:
https://github.com/creytiv/re/commit/1544a1e375c76a80084b411d21b0431f95e9cdfb
=> add RTP Header extension for Client-to-Mixer Audio Level Indication

include/baresip.h, modules/sdl2/sdl.c, src/config.c, src/video.c
Hello Alfred,
In my application, the video output must always be fullscreen, so i added a global configuration option to specify that as default. This is currently only obeyed by the sdl2 module, but could be implemented by others?
Another Commit changes the SDL flag to SDL_WINDOW_FULLSCREEN_DESKTOP, which means that SDL won't switch resolution, but create instead will create a borderless window with the size of the desktop.
I don't know if this is preferable to everyone, maybe it should be configurable in some way, too?
Thanks for your review,
Jonathan
=> Make sdl2 Fullscreen Mode configurable

mk/modules.mk, modules/avahi/avahi.c, modules/avahi/module.mk
Hello Alfred,
I improved a bit on the avahi module, it is getting closer to being generally useful.
Now it registers a new UA under username@hostname.local, which is resolved through Avahi.
~~There are some remaining problems, like with IPv4/IPv6 Dual-Stack support. Since baresip seems to support only one at a time, that one should be advertised through Avahi.~~
~~But i have not found a way to query if baresip was started with the -6 flag, so i'm just assuming v6.~~
UPDATE: I found net_af(), which allows to query that. I'm working on a fix to handle both v4 and v6 discoveries.
A Similar issue is advertising the correct transports (UDP, TCP, TLS), which should be based on the parameters to ua_init(). For now it just advertises UDP.
Thanks in advance for your review,
Best Regards,
Jonathan
=> Local Discovery through Avahi/ZeroConf module

docs/examples/config, modules/zrtp/zrtp.c, src/config.c
Use SDP attribute a=zrtp-hash to protect the Hello message (RFC 6189, section 8.1).
https://tools.ietf.org/html/rfc6189#section-8
This adds an extra level of protection especially when using a secure signaling channel. When an attack is detected, all incoming and outgoing UDP packets are being dropped, and the call is aborted.
If, for whatever reason, this feature is undesirable (for example, if one wants to hide the UA's ZRTP capability), it can be disabled by the configuration file option.
=> modules/zrtp: add signaling hash support

mk/modules.mk, modules/gzrtp/gzrtp.cpp, modules/gzrtp/messages.cpp, modules/gzrtp/module.mk, modules/gzrtp/session.cpp, modules/gzrtp/session.h, modules/gzrtp/stream.cpp, modules/gzrtp/stream.h
I created this module after having regular ZRTP issues with libzrtp and linphone. It uses Werner Dittmann's [ZRTPCCP](https://github.com/wernerd/ZRTPCPP) library as a backend.
Pros:
* maintained
* reviewed
* widely used (Twinkle, PJSIP, CSipSimple etc.)
* flexible
* works with linphone!
Cons:
* more glue code
* C++ (if it matters)
The module is statically linked with libzrtpcppcore.a which should be built from source using the following commands:
```sh
git clone https://github.com/wernerd/ZRTPCPP.git
cd ZRTPCPP
mkdir build
cd build
cmake -DCMAKE_POSITION_INDEPENDENT_CODE=1 -DCORE_LIB=1 -DSDES=1 -DBUILD_STATIC=1 ..
make
```
Then make baresip with
```
make USE_GZRTP=1 ZRTP=<ZRTPCPP_DIR> <OTHER OPTIONS>
```
And add `module gzrtp.so` to the configuration file.
This module has been tested with …
=> modules/gzrtp: new module using GNU ZRTP C++ library

modules/avahi/avahi.c
I identified a bug in the avahi code.
Resolvers where not free'd after use, which lead to multiple contact entrys when remote nodes came off- and online in a single run.
=> avahi: Bugfix: Destroy resolver after callback

modules/gzrtp/module.mk, modules/gzrtp/srtp.cpp, modules/gzrtp/srtp.h, modules/gzrtp/stream.cpp, modules/gzrtp/stream.h
And add an option to use libre SRTP processing stuff instead of the one provided by ZRTPCPP (-DGZRTP_USE_RE_SRTP).
This makes stream class code a bit cleaner. libre SRTP processing can be used as a fallback if one has issues with ZRTPCPP's one. It works fine but supports only a standard set of algorithms (AES).
=> modules/gzrtp: move SRTP processing to a separate class

src/audio.c
Having min_sz > tx->psize in aubuf_alloc() results in insertion of 16 packets of silence at the beginning of the RTP stream. This adds an unnecessary delay.
The delay (~ 1/3 sec) is clearly noticeable when calling localhost->localhost using baresip at both ends. Use hold/resume to hear the difference.
=> audio: remove silence at the beginning of the RTP stream

src/audio.c
Perhaps should be done once when RX stream is set up, and stored in
struct audio.
/ Ola Palm
=> Max skew is calculated during runtime and not a defined fixed value.

mk/modules.mk, modules/mqtt/README.md, modules/mqtt/module.mk, modules/mqtt/mqtt.c, modules/mqtt/mqtt.h, modules/mqtt/publish.c, modules/mqtt/subscribe.c, src/config.c
mqtt: relay ua_event with publish
relay incoming message to long commands (with '/' prefix)
mqtt: add file for publish
mqtt: add command response
mqtt: add subscribe.c
mqtt: use fd_listen for READ/WRITE
Make + Config entry for MQTT module (#329)
* include mqtt in modules and config
* Check for mosquitto-dev
* fix mqtt module checks
* Moving MQTT config to module_app block
mqtt: add JSON payload for events
mqtt: add JSON decoding of command
mqtt: add config for broker host/port
=> mqtt: new module for MQTT

modules/avcodec/encode.c
Just a very small fix: 
I found that the avcodec module with x264 won't obey the video_bitrate config option.
With a different rate control mode (ABR=Average-Bitrate instead of CQP=Constant-Quality), it will usually keep the bitrate around or below the configured value.
=> avcodec: change x264 rate control mode to ABR

modules/avcodec/decode.c
Hello Alfred,
Previously, when packet loss occured on a H264 stream, the image would get corrupted and not recover for many seconds, until the left-to-right-rolling periodic intra-refresh came by.
Today i did some tests with simulated packet loss, and noticed that in most cases, decode_h264() won't return an error, because the missing fragment is already noticed by h264_fu_hdr_decode(), and the subsequent code returns 0;
I changed these cases to return EPROTO, and now it recovers much faster.
Only one or a few frames of a destroyed image are shown, before the video recovers, which still is annoying and probably unnecessary, but the overall experience seems to already be much better.
I'd be happy if you have some time to look into this and comment, i'm very much interested in a more robust …
=> avcodec: Request Frame Refresh in more cases

Makefile, src/config.c
No need to try to guess path at runtime, whereas it has been configured at build time.
=> set exact installation pathes at build time

modules/menu/menu.c
- if given value "off" statsmode defaults to STATMODE_OFF
- otherwise statsmode initial value is STATMODE_CALL
=> modules/menu: added "statmode_default" config variable

include/baresip.h, modules/avcapture/avcapture.m, modules/avformat/avformat.c, modules/cairo/cairo.c, modules/fakevideo/fakevideo.c, modules/rst/video.c, modules/v4l/v4l.c, modules/v4l2/v4l2.c, modules/vidbridge/src.c, modules/vidbridge/vidbridge.h, modules/vidloop/vidloop.c, modules/x11grab/x11grab.c, src/video.c, src/vidutil.c, test/mock/mock_vidsrc.c
This PR adds a new _timestamp_ field to the vidsrc frame handler.
Background: The video encoding pipeline currently does not use the timestamp
from the video source at all. Instead the video codecs have a frame counter,
that is used together with `fps` to calculate the RTP timestamp.
This solution is not accurate, and I want to change it so that the exact timestamp
for each video frame (coming from the source) will be transported all the way
through the video pipeline, which currently looks like this:
1. Video source
2. Video filters
3. Video encoder and packetizer
4. RTP sending
For timestamp format the following units was considered:
* double float (seconds)
* uint64_t timestamp (milliseconds)
* uint64_t timestamp (microseconds)
* int64_t pts, Presentation Timestamp in timebase units
* …
=> Vidsrc add timestamp

include/baresip.h, modules/av1/av1.h, modules/av1/encode.c, modules/avcodec/avcodec.h, modules/avcodec/encode.c, modules/gst_video1/encode.c, modules/gst_video1/gst_video.h, modules/h265/decode.c, modules/h265/encode.c, modules/h265/h265.h, modules/v4l2_codec/v4l2_codec.c, modules/vidloop/vidloop.c, modules/vp8/encode.c, modules/vp8/vp8.h, modules/vp9/encode.c, modules/vp9/vp9.h, src/video.c, src/vidutil.c, test/mock/mock_vidcodec.c
This PR adds a new timestamp parameter to the video encoder API.
The unit is the same as the vidsrc API (defined in the VIDEO_TIMEBASE macro).
=> Videnc add timestamp

include/baresip.h, src/account.c
for ease of use and implementation, audio codecs argument is a string
containing comma separated list of codecs like in accounts file
=> added account_set_audio_codecs API function

modules/avcodec/avcodec.c, modules/avformat/avformat.c, modules/h265/h265.c
fixes warnings when compiled with ffmpeg 4.0
=> dont call deprecated ffmpeg functions

src/video.c
If there are no displays available,
add the sdp flag sendonly to the video stream
=> If no displays: add sendonly to the video stream

mk/win32/baresip.vcxproj, mk/win32/baresip.vcxproj.filters
After commits on Mar 21, 2018 ([74b22](https://github.com/alfredh/baresip/commit/74b228ad7ee5f46788707f74904101b3ccab2ba7) and [74b40](https://github.com/alfredh/baresip/commit/78b4031dd0334b55ea4f92dd93ff27dc20755355)) timer.c need to be compiled
=> Keeping MSVS project up to date

include/baresip.h, modules/gtk/gtk_mod.c, modules/plc/plc.c, modules/sndfile/sndfile.c, modules/speex_aec/speex_aec.c, modules/speex_pp/speex_pp.c, modules/vumeter/vumeter.c, src/audio.c
This is needed so that the audio-filter (aufilt) modules can
get access to the audio session state, and also the call object.
This commit breaks the AUFILT api.
=> aufilt: add pointer to "struct audio"

modules/dshow/dshow.cpp
Hello
According to this issue: https://github.com/alfredh/baresip/issues/464 I moved declarations of `ISampleGrabberCB` and `ISampleGrabber` into dshow.cpp so it does not require qedit.h file.
Here is [MSVS build log](https://pastebin.com/tCGb5BKn).
@nicotyze would you like to compile with mingw please? I have some troubles with compilation both in current state and this pr. Thank you.
Alexey
=> dshow: remove qedit.h

modules/vidloop/vidloop.c
This is a proposal to address #451 last comment analyses.
As suggested, video frames are rendered/displayed from main thread and the logic is moved to vidloop module.
A mutex is used to protect vl->frame and vl->disp accesses
A frame copy is needed in order to provide the display module with final pixel values.
Tested with SDL2 display, on win10 and ubuntu 16.04
=> Vidloop fix: video frame rendering is moved to main thread

include/baresip.h, modules/amr/amr.c, modules/bv32/bv32.c, modules/codec2/codec2.c, modules/g711/g711.c, modules/g722/g722.c, modules/g7221/g7221.c, modules/g726/g726.c, modules/gsm/gsm.c, modules/ilbc/ilbc.c, modules/isac/isac.c, modules/l16/l16.c, modules/mpa/mpa.c, modules/opus/opus.c, modules/silk/silk.c, src/audio.c, test/mock/mock_aucodec.c
this is currently only needed for the MPA codec, where the
audio channel count and RTP-packet channel count differs.
=> aucodec: add packet channels (pch) to struct

docs/examples/config, include/baresip.h, src/audio.c, src/config.c
remove these config options:
audio_srate            8000-48000
audio_channels         1-2
these options has no practical usage, except to limit the
enabled audio codecs to the range of samplerate/channels
as specified.
if a module has multiple audio codecs, and you only want
to use one of them, this can now be done with the
"audio_codecs" parameter to the "accounts" file.
=> audio: remove audio_srate and audio_channels

src/conf.c
Accept also empty contacts file as existing contacts file.  When baresip is started with empty contacts file,
it now does not create a new default one, but reports:
Populated 0 contacts
=> consider empty contacts file as existing contacts file

include/baresip.h, mk/modules.mk, modules/rtcpsummary/module.mk, modules/rtcpsummary/rtcpsummary.c, src/main.c, src/stream.c
- new module: rtcpsummary
- At the end of a call, output the RTCP stats in a format that's easily parsed
- expose some read-only info from stream.c
=> RTCP summary module

modules/x11/module.mk
the current code gives a warning on OSX:
```
CC [M]  build-x86_64/modules/x11/x11.o
LD [M]  x11.so
ld: warning: directory not found for option '-L/usr/X11/lib'
```
=> x11: remove old path

src/main.c
- do not buffer output/input to any of stdin, stdout, stderr
- without this change, the new UI infrastructure buffers all output
until the application is killed; makes it impossible to control
programatically
=> Prevent buffering standard I/O

include/baresip.h, src/core.h
This is a proposal in order to be consistent with vidsrc and vidisp struct.
This patch is necessary for mediadev API support in audio modules.
=> make struct ausrc and auplay public

src/call.c
In function call_connect SIP URIs like "<sip:user@host>" are not supported. The
log tells us:
call: sipsess_connect: Function not implemented
This is because the angle brackets are present and the display name is missing.
The patch achieves that the empty display name is ignored and the URI is
accepted.
=> call: Support also SIP URI with missing display name.

modules/alsa/alsa_play.c
When the write_thread finishes we have to wait until ALSA has processed it's
internal buffer before we call snd_pcm_close. This can be achieved by calling
snd_pcm_drain.
=> alsa: On termination of alsa_play wait until buffer was processed.

include/baresip.h, modules/selfview/selfview.c, modules/snapshot/snapshot.c, modules/swscale/swscale.c, modules/vidinfo/vidinfo.c, modules/vidloop/vidloop.c, src/video.c
add timestamp parameter to the Vidfilt API.
this allows a video filter module to read and to modify the frame timestamp.
updated modules:
* selfview
* snapshot
* swscale
* vidinfo
=> Vidfilt add timestamp

modules/dshow/dshow.cpp
Hi,
This PR is an  implementation of set_available_devices in dshow module.
Testing environment:
- Cross compilation from Ubuntu 16.04.1 ( i686-w64-mingw32 toolchain, following https://github.com/alfredh/baresip-win32 )
- Binaries tested on Win10
=> dshow: mediadev support

modules/dshow/dshow.cpp
Fix compilation error reported in https://github.com/alfredh/baresip/pull/550
Testing environment:
- Cross compilation from Ubuntu 16.04.1 ( i686-w64-mingw32 toolchain, following https://github.com/alfredh/baresip-win32 )
- Binaries tested on Win10
=> dshow: fix missing parenthesis in enum_devices

src/mediadev.c
In response to duplicated devices observed from linux/wine testing environment and reported here https://github.com/alfredh/baresip/pull/550#issuecomment-427644290
Tested with dshow, pulse and v4l2 modules.
=> mediadev: check if device already exists in mediadev_add

modules/winwave/play.c, modules/winwave/src.c, modules/winwave/winwave.c, modules/winwave/winwave.h
This PR is an  implementation of set_available_devices in winwave module.
Testing environment:
- Cross compilation from Ubuntu 16.04.1 ( i686-w64-mingw32 toolchain, following https://github.com/alfredh/baresip-win32 )
- Binaries tested on Win10
=> winwave: mediadev support

modules/winwave/play.c, modules/winwave/src.c, modules/winwave/winwave.c, modules/winwave/winwave.h
This PR adds support for FLOAT sample format.
See here for a list of audio drivers and sample formats:
https://github.com/alfredh/baresip/wiki/Audio-sample-formats
=> winwave: add support for FLOAT sample format

modules/opengl/opengl.m
the current code assumes that linesize == width.
if the linesize is different from width, the rendered picture
will be broken.
adding a call to glPixelStorei(GL_UNPACK_ROW_LENGTH, linesize)
seems to fix it.
=> opengl: properly handle linesize

modules/avcapture/avcapture.m
This PR is a proposal to fix video resolutions mismatches in avcapture (map_preset function).
AVCaptureSessionPresetLow, AVCaptureSessionPresetMedium and AVCaptureSessionPresetHigh seem to be device dependent. 
For instance, if I configure video_size  640x480, I get AVCaptureSessionPresetHigh which is mapped to 1280x720 with my macbook => video resolutions written explicitly in this patch.
With the current implementation, we can get a resolution upper than the configured video_size. 
For instance, if I configure video_size  854x480, I get AVCaptureSessionPreset1280x720.
My understanding is that the required video resolution should be considered as an upper bound => in the patch map_preset returns the upper resolution for which frame width and heigh are lower than the required values.
To …
=> avcapture: fix video resolutions mismatches

modules/sdl2/sdl.c
Not a lot, but It would be nice to have resizable window with SDL2.
Tested with win 10, Ubuntu 16.04 and OSX 10.13.6
=> sdl2: make window resizable

include/baresip.h, modules/contact/contact.c, src/contact.c
This is an improvement to make the contacts UI a bit more
user-friendly.
It adds the concept of a "current contact", which can be
changed by pressing the keys < and >.
- Pressing 'D' will dial the current contact.
- Pressing 'M' will send message to the current contact.
Example output of listing all contacts (press 'C'):
```
--- Contacts: (3) ---
Unknown  Alfred <sip:aeh@creytiv.com>
>      Unknown  Bob <sip:bob@builder.com>
Unknown  Carl <sip:carl@supertruck.com>
```
the left-most character '>' indicates the current contact.
also the current contact is saved to disk, so that the
state is correct next time you start baresip.
=> contact: add support for current contact

modules/coreaudio/coreaudio.c, modules/coreaudio/coreaudio.h, modules/coreaudio/player.c, modules/coreaudio/recorder.c
This  patch adds mediadev support in coreaudio.
Tested from OSX 10.13.6
=> coreaudio: mediadev support

modules/avcodec/decode.c
This patch adds a check in decode_h263 and decode_h264 in order to return an error while the decoding process has not been initiated with a key frame (~intra frame).
This error is returned in video_stream_decode (video.c), triggering a RTCP FIR.
This aims at avoiding infinite loop with no key frame received/processed (=> no decoded video)
=> avcodec: force intra (H.263, H.264) frame request if no key frame received

include/baresip.h, src/config.c, src/stream.c
This is a proposal to remove the config option `rtcp_enable`.
The RTCP will now always be enabled.
Is there a usecase where one would like to run RTP without RTCP?
Please state here if are for or against this change.
=> config: remove 'rtcp_enable', always enabled

modules/menu/menu.c
Hi, this is my first PR to this project, please let me know if this is the way to go and if this feature has a place in baresip.
I would like this feature as toggling through a list becomes a bit cumbersome with multiple UAs. I was also using `ctrl_tcp` and then selecting a UA is much easier than cycling through the list (with toggle). With `/uafind <aor>` you can select them by aor. I didn't consider a short command or _fuzzy_ find (eg. to just search username `alice` instead of `sip:alice@example.com`).
=> menu: add uafind to select ua by aor

modules/menu/menu.c
I think I actually copied this one as template. Shouldn't use `dialbuf` then as well.
=> menu: create_ua doesn't use dialbuf

modules/audiounit/audiounit.c, modules/audiounit/audiounit.h, modules/audiounit/player.c, modules/audiounit/recorder.c
This PR is a proposal of an AUConverter resampler for audiounit module (recorder side).
The approach consists in using a specific AudioUnit for conversion (sub-type AUConverter).
The raw audio samples are captured (at hw sample rate) and then, the conversion is called
I did it in a really empirical way, mixing different "sources" (mainly from [here](http://dinhe.net/~aredridel/projects/audio/audioengine-1.4/ ) and [here](https://github.com/alfredh/baresip/tree/audiounit_resample2))
Tested successfully from OSX 10.13: auloop and calls with many combinations (44100 Hz -> 48000 Hz, 44100 Hz -> 8000 Hz, 48000 Hz -> 44100 Hz ...). 
Not tested from iOS...
=> audiounit: add AUConverter resampler (recorder)

docs/examples/config, modules/mqtt/mqtt.c, modules/mqtt/mqtt.h, modules/mqtt/publish.c, modules/mqtt/subscribe.c
The current mqtt module use the same client ID for all logins, making it impossible to have multiple baresip instances connected to the same broker. It also makes it impossible to separate instances when sending commands or reading events.
This patch adds configuration options for client ID, username, password as well as a base topic making it possible to control a cluster of Baresip instances on the same broker.
When configured, the base topic is used for both events and commands.
```
mqtt: connecting to broker at sollentuna.example.com:1883 as baresip01 topic baresip/olle01
mqtt: Publishing on /baresip/olle01/event, subscribing to /baresip/olle01/command/+
```
Tested with mosquitto. Original defaults are the same.
=> Improve mqtt module

mk/win32/baresip.vcxproj, mk/win32/baresip.vcxproj.filters
Hello @alfredh 
In this commit 18c79180628c90889bd1610742a2e21bd366d818 file `realtime.c` was removed. This patch will remove it from MS Visual Studio solution
=> Update MSVS project

modules/vumeter/vumeter.c, modules/winwave/play.c, modules/winwave/src.c, src/account.c, src/video.c
This commit will fix warnings about possible data loss https://github.com/alfredh/baresip/issues/654#issuecomment-461546865
<details>
<summary>Here is a full output:</summary>
<p>
```
3>------ Build started: Project: baresip-win32, Configuration: Debug Win32 ------
3>  account.c
3>  amr.c
3>  sdp.c
3>  auloop.c
3>  b2bua.c
3>  cons.c
3>  contact.c
3>  debug_cmd.c
3>  dshow.cpp
3>  echo.c
3>  g711.c
3>  httpd.c
3>  ice.c
3>  l16.c
3>  menu.c
3>  mwi.c
3>  natbd.c
3>  libnatpmp.c
3>  natpmp.c
3>  notifier.c
3>  presence.c
3>  publisher.c
3>  subscriber.c
3>  selfview.c
3>  sdes.c
3>  srtp.c
3>  stun.c
3>  turn.c
3>  uuid.c
3>  disp.c
3>  src.c
3>  vidbridge.c
3>  vidloop.c
3>  vumeter.c
3>  wincons.c
3>  play.c
3>  src.c
3>  winwave.c
3>  account.c
3>  aucodec.c
3>  audio.c
3>  aufilt.c
3> …
```
=> Fix warnings at windows compilation

modules/vidloop/vidloop.c
This patch makes possible to switch between video sources without having to restart the loop.
Tested on Ubuntu16.04 and Win10.
=> vidloop: update vidsrc

src/cmd.c
If a command does not exist, the response should be a failure, not "ok", for clients only looking at success/failure and not the content.
=> Command not found returns error

README.md, docs/examples/config, modules/httpd/httpd.c, src/config.c
Hi Alfred,
I've suggested some very light changes. It helped me to more easily set the configuration. I added just an enum to httpd.c -> HTTP_PORT and comments so it resembles how the cons.c and ctrl_tcp.c looks and works.
Best regards
Roger (Swedish Radio) :)
=> Readme and config example correction, httpd comments

modules/avcodec/avcodec.c, modules/avcodec/avcodec.h, modules/avcodec/decode.c, modules/avcodec/encode.c, modules/avcodec/h263.c, modules/avcodec/module.mk
the main reason for this is that libx264 is GPL and we dont want to link to GPL code.
avcodec.so will now use only FFmpeg libavcodec for both encoding and decoding.
Platforms:
Things to fix:
=> Avcodec remove libx264

modules/menu/menu.c
This addition allows to delete ua's from within baresip. I removed `sip_close` as it would otherwise stop Baresip on deleting the last ua. I believe `sip_close` is not necessary here as it is called from `ua_stop_all` already which is called when you quit Baresip.
=> menu: add uadel to delete a uac by aor

include/baresip.h, src/ua.c
Resolves #701
Count ua references after UA_EVENT_SHUTDOWN in case that triggers clean-up in other modules.
=> Count ua references after UA_EVENT_SHUTDOWN in ua_destroy

src/call.c, src/stream.c
The audio data in the jitter buffer has to be flushed when putting a call into
on hold state. Otherwise it is played on the playback device after the call is
resumed.
=> call: reset streams on call hold

src/audio.c
Hi,
This is a small patch to fix problems with long audio device names.
Tested with ubuntu 16.04
=> audio: increase buffer size for audio device string

modules/webrtc_aec/aec.cpp, modules/webrtc_aec/decode.cpp, modules/webrtc_aec/encode.cpp
WIthout pthread.h includes, Android clang++ compiler didn't find pthread related functions.
=> webrtc_aec module: added pthread.h include to .cpp files

src/audio.c, src/stream.c
when audio stream is receiving RTP with marker bit set, the following
should happen:
1. flush jitter buffer (re-ordering buffer)
2. flush aubuf for playback.
@cspiel1 could you please test this patch ?
=> audio: handle marker bit in stream.c

mk/win32/baresip.vcxproj, mk/win32/baresip.vcxproj.filters
Hello!
In this PR https://github.com/alfredh/baresip/pull/739 `src/mos.c` file was removed from repo but not from MSVS project. This PR removes it from project
=> Update MSVS project (Remove mos.c)

modules/ctrl_tcp/ctrl_tcp.c, src/event.c
=> Allow CALL_CLOSED to be raised when call_id is not set.

modules/menu/menu.c
Coming back on PR #628. The DTMFs arrive, but the last sent digit really needs the `KEYCODE_REL` in order for the far end to receive the DTMF end marker. I changed this PR to the suggestion you made in that PR :-)
=> menu: sndcode should signal release of key

include/baresip.h, modules/ice/ice.c
this is a proposal to add a new flag to the mnat struct, called `bool wait_connected`
the purpose is to control when the media-stream should be started
(audio and video stream). if the flag is set, the core will not start audio/video
until for example ICE is connected, meaning that it has a working candidate pair.
below is the list of all MEDIANAT modules and the suggested value
of the wait_connected flag:
| Medianat | wait_connected |
| ---- | ---- |
| stun | no |
| turn | no |
| ice | yes |
| natpmp | no |
| pcp | no |
a similar flag will also be added to the MEDIAENC struct, e.g. `bool wait_secure`
=> mnat: add wait_connected flag

include/baresip.h, modules/dtls_srtp/dtls_srtp.c
this patch adds a flag `bool wait_secure` to the mediaenc struct
the purpose is to control when the media-stream should start.
if the flag is false, the media stream will start when the SIP session
is established. if the flag is true, the media stream will start when
the menc is secure.
for example DTLS-SRTP has an async handshake after the SIP session
is established, so the flag should be set to true here.
here is a list of Mediaenc modules and the suggested flag value:
| Module | wait_secure |
| --- | --- |
| srtp | no |
| zrtp | no |
| dtls_srtp | yes |
=> menc: add wait_secure flag

src/call.c, src/core.h, src/stream.c
This PR adds support for WebRTC interop.
The main change is that each stream layer is connected
in this order:
1. mnat (ICE)
2. menc (DTLS-SRTP)
3. audio/video media
Testing:
chrome 75.0.3770.100 and TRYITJsSIP -- ok
firefox 68.0 (64-bit) and TRYITJsSIP -- ok
Sample accounts:
```
"Anti Alf" <sip:alfredh2@sip.antisip.com>;outbound="sip:sip.antisip.com;transport=tcp";auth_pass=XXXX;regint=60;answermode=auto;medianat=ice;mediaenc=dtls_srtp
```
Sample config:
```
rtcp_mux                yes
module                  opus.so
module                  g711.so
module                  vp8.so
module                  ice.so
module                  dtls_srtp.so
```
=> webrtc interop

modules/avcodec/avcodec.c, modules/avcodec/avcodec.h, modules/avcodec/decode.c, modules/avcodec/encode.c
add support for hardware accelleration for ffmpeg decoder.
sample config:
```
avcodec_h264enc		h264_vaapi
avcodec_h264dec		h264
avcodec_hwaccel		vaapi
```
Testing:
* vaapi encoder
* vaapi decoder
* videotoolbox encoder
* videotoolbox decoder
=> Avcodec hwaccel

modules/pulse/player.c, modules/pulse/recorder.c
Passing NULL to pa_simple_new as the device instructs PulseAudio to use the default. This is better then the current baresip behaviour which just uses the first device if no device was specified. In my case the first device was not the default.
=> Use default PulseAudio device 

modules/account/account.c, src/account.c, src/audio.c, src/core.h, test/account.c
Add support for specifying audio source and player per account.
The global config will be used by default.
Syntax:
```
;audio_source="module,device"
;audio_player="module,device"
```
Example with multiple accounts/devices:
```
<sip:user1@example.com>;audio_source=alsa,plughw:0,1
<sip:user2@example.com>;audio_source=alsa,plughw:0,2
<sip:user3@example.com>;audio_source=alsa,plughw:0,3
```
Please review and test.
=> Account specific audio source and playback

mk/modules.mk, modules/mpa/encode.c, modules/mpa/module.mk, modules/mpa/mpa.c, modules/mpa/mpa.h, modules/mpa/sdp.c
libmp3lame uses MPEG2 Layer III.
=> mpa: switch encoder to use lame

include/baresip.h, src/account.c, src/core.h
When using baresip as library, it would be convenient to be able to add a parameter to an account that contains such information about the account that is only relevant to the application code, not to baresip core.  For example, it may be easier to handle automatic answering of a call in the application code after receiving UA_EVENT_CALL_INCOMING event than directly handling UA_EVENT_CALL_ESTABLISHED event.
This pull request adds possibility to include ';extra' parameter to an account and access its value with account_extra() API function.  An example of ';extra' parameter could be:
```
;extra="answer_mode=auto;speaker_phone=on"
```
=> account ";extra" parameter and account_extra() API function

include/baresip.h, src/main.c, src/ua.c
this requires a special version of libre:
https://github.com/alfredh/re
To run baresip with SIP trace enabled:
```
$ baresip -i
```
(the letter `i` is open to better ideas).
=> ua: add support for SIP trace

Makefile
after this commit in libre:
https://github.com/creytiv/re/commit/18ba584f02a525e066de4e9eb24d9f36a4c49ae2
the `SYSROOT` variable now points to the OSX SDK selected by xcode-select:
```
SYSROOT:       /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr
```
compiling baresip on OSX now gives thousands of warnings
from the system header files.
The compile should have a list of include paths for system header
files, so there is no need for us to explicitly specify it.
```
clang -x c -v -E /dev/null
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin …
```
=> Fix osx build

modules/avcodec/decode.c
instead of manually parsing the video packets, we use the libavcodec decoder
to determine if a frame is a keyframe. this results in much simpler code.
testing:
```
Debian 8	libav 11.12		ok
Debian 9	ffmpeg 3.2.14-1		ok
OSX 10.12	ffmpeg 4.2.1		ok
OpenBSD 6.5	ffmpeg 4.1.3		ok
```
=> avcodec: use AVFrame key_frame flag to check for keyframes

modules/mpa/encode.c, modules/mpa/mpa.c, modules/mpa/sdp.c
Please note: The MPA module currently does layer 3 encoding only (using `libmp3lame`).
It tries to advertise this by SDP and apply constraints even to mirrored fmtp encoding.
There are not any constraints decoding other audio layers.
Encoding layer 2 (MP2) would require dynamic switching to `libtwolame` encoding which is not implemented (yet).
=> MPA layer 3 encoding fixes

modules/i2s/i2s.c, modules/i2s/i2s.h, modules/i2s/i2s_play.c, modules/i2s/i2s_src.c, modules/i2s/module.mk
An I2S audio driver for freeRTOS.
Tested with:
MAX98357A - i2S CLASS D stereo amplifier
Sparkfun I2S Audio Breakout - MAX98357A SF14809
=> aui2s: add rtos i2s audio driver module

include/baresip.h, modules/l16/l16.c, src/audio.c
- add optional ptime (in ms) packet time to each codec,
which can be used to override the default
- update l16.so with some ptime values to keep the
packet size below a common MTU (1500):
48000/2 -> 5ms
44100/2 -> 5ms
32000/2 -> 10ms
16000/2 -> 20ms
... etc ...
=> audio: add ptime to struct aucodec

modules/l16/l16.c
Changed default ptime from 5ms to 4ms when using l16 48000/2 & 44100/2
=> l16 ptime 5 -> 4ms

include/baresip.h, src/audio.c, src/config.c
The audio receive/decode path has an audio buffer with de-jitter.
This patch makes the size run-time configurable:
`audio_buffer            20-100          # ms`
=> add config for audio receive buffer size

src/stream.c
Stop spamming to console and logs when unknown RTP extension type is used.
=> change message log level of unknown RTP extension

docs/examples/config, modules/jack/jack_play.c, modules/jack/jack_src.c, src/config.c
Second attempt... Fixed formatting.
Add option to allow baresip not to make jack connections once the call is up and running.  My use case is radio broadcasting where the routing will be switched by the playout system.
=> Jack connect config

src/core.h, src/reg.c, src/ua.c
Do not update ua->af_media by reg.c  register_handler().  Instead make reg->af available for use by ua.c best_effort_af().
=> make reg->af available for use by best_effort_af

README.md, docs/examples/config, include/baresip.h, modules/ice/ice.c, modules/natpmp/natpmp.c, modules/stun/stun.c, modules/turn/turn.c, src/account.c, src/call.c, src/config.c, src/core.h, src/srcs.mk, src/stunuri.c, test/mock/mock_mnat.c
https://tools.ietf.org/html/rfc7064
https://tools.ietf.org/html/rfc7065
ice_turn yes|no config has been replaced by per account
stunserver:
;stunserver="turn:example.org:8000"
=> add support for STUN uri used in MNAT api

README.md, include/baresip.h, mk/modules.mk, modules/ebuacip/ebuacip.c, modules/ebuacip/module.mk, src/audio.c, src/call.c, src/config.c, src/event.c
This patch moves the EBUACIP specific code from core
to a new module called `ebuacip.so`
The functionality is the same.
Please review: @Ola-Palm @djhenley @premultiply
=> add ebuacip module

.travis.yml, modules/avformat/audio.c, modules/avformat/avformat.c, modules/avformat/mod_avformat.h, modules/avformat/module.mk, modules/avformat/video.c
This PR adds support for audio in the avformat.so module
You can use it to read the audio track from an MP4 file:
audio_source    avformat,foo.mp4
video_source    avformat,foo.mp4
Any avformat backend is supported, except avdevice
```
Compile Testing:
Platform:     ffmpeg:          Status:
--------      ------           ------
Debian 9      3.2.12-1~deb9u1  OK
Debian 10     4.1.4-1~deb10u1  OK
Ubuntu 16.04  2.8.15-0ubuntu0  OK
OSX 10.12     4.2.1            OK
```
=> Avformat add audio

modules/echo/echo.c
```
ua: sip-stack exit
ua exited -- stopping main runloop
module: unloading app vidloop
module: unloading app menu
menu: close (redial current_attempts=0) 
module: unloading app echo
echo: module closing..
echo: flushing 1 sessions
echo: session destroyed (in=0x55c9fb8bcbc0)
mem: mem_deref: magic check failed 0xb5b5b5b5 (0x55c9fb8bcbc0)
Trace/breakpoint trap (core dumped)
```
=> echo: fix flushing session

modules/account/account.c
There are use cases where account does not need to authenticate itself when sending SIP requests, for example, when it is only used to call some public service URIs.
So far I have not figured out how to create an account without auth_user and auth_pass so that password is not prompted when account module is loaded.  
This pull requests solves the issue by causing password prompting only if auth_user is set and auth_pass is not set.  Better solutions are, of course, welcome .
=> prompt password only if auth_user is set and auth_pass is not

include/baresip.h, modules/alsa/alsa_src.c, modules/aubridge/device.c, modules/audiounit/recorder.c, modules/aufile/aufile.c, modules/auloop/auloop.c, modules/avformat/audio.c, modules/coreaudio/recorder.c, modules/gst/gst.c, modules/jack/jack_src.c, modules/opensles/recorder.c, modules/oss/oss.c, modules/portaudio/portaudio.c, modules/pulse/recorder.c, modules/rst/audio.c, modules/sndio/sndio.c, modules/winwave/src.c, src/audio.c, test/mock/mock_ausrc.c
- Add auframe type
- Change ausrc api to use auframe
The purpose is to add a more flexible type, and add more members
to struct auframe later, such as sample format, sample rate, channels
Tested modules:
=> Ausrc add auframe

mk/win32/baresip.vcxproj, mk/win32/baresip.vcxproj.filters
Hi Alfred,
these are my fixes to build baresip with VS 2017.
Not sure about the HAVE_GETOPT though - it requires to install the LGPL getopt via vcpkg:
vcpkg.exe install getopt
There's an alternative getopt implementation that works too, but it's using "AT&T public" license which I think is not compatible with baresip's BSD.
=> Win32 fixes

include/baresip.h, src/account.c
Needed to get full AoR URI that includes not just username@domain:port, but also parameters, such as ;transport.
=> Added account_luri API function

modules/alsa/alsa_play.c, modules/alsa/alsa_src.c
This prevents compilers to optimize them away.
gcc -O2 now creates different code. I'm not sure whether the old output was
actually broken. The point is, that without volatile some compilers
might produce broken code.
Signed-off-by: Harald Geyer <harald@ccbib.org>
I stumbled upon this while looking why baresip sometimes hangs in auplay_destructor(). The behaviour I see still doesn't make sense to me, but I guess this is a step forward in getting rid of hard to reproduce bugs.
=> alsa: mark thread control variables volatile

include/baresip.h, modules/alsa/alsa_src.c, modules/aubridge/device.c, modules/audiounit/recorder.c, modules/aufile/aufile.c, modules/avformat/audio.c, modules/coreaudio/recorder.c, modules/jack/jack_src.c, modules/oss/oss.c, modules/portaudio/portaudio.c, modules/pulse/recorder.c, modules/rst/audio.c, modules/winwave/src.c, test/mock/mock_ausrc.c
Add timestamp to audio frame. The clock-rate of the timestamp is in microseconds:
`#define AUDIO_TIMEBASE 1000000U`
Updated audio source modules:
=> auframe: add timestamp

mk/modules.mk, modules/avformat/audio.c, modules/avformat/avformat.c, modules/avformat/mod_avformat.h, modules/avformat/module.mk, modules/avformat/video.c
Added  avdevice_register_all() and av_find_input_format() calls before avformat_open_input() call.
Added libs to module.mk needed by avdevice_register_all().
=> avformat: enhanced avformat_shared_alloc() function

Makefile, test/call.c
add usage of external modules in selftest.
only add g711.so for now.
When running `make test` also g711.so will be compiled
and used by selftest.
The advantage of this is that we can get modules under test,
which can then be used by tools like valgrind.
=> test: add usage of g711.so module

include/baresip.h, modules/debug_cmd/debug_cmd.c, src/account.c, src/core.h, src/reg.c, src/ua.c
Hi!
Thanks for answering the 'issue' #959 . "MQTT / TCP on connection client state request". 
As mentioned before in the "issue" the idea here is to have a command with a JSON-formatted response. The command could be used when you are starting an api connection to Baresip, via TCP or MQTT. Similair like how '/uastat' and '/callstat' is used today, so an external application could get up and running without a lot of parsing of those commands. The new 'response' could also be the default response on registration and call events...
I should start with an apology, I don't have a deep knowledge of C-programming. So the pull-request is a very early one, maybe @alfredh you can put me in the right direction. Please let me know if I should look up something before you give a proper response, I …
=> JSON initial codec state command and response

src/call.c
I noticed that ua event CALL_REMOTE_SDP parameter has always value "offer" no matter if remote answers to re-INVITE or sends re-INVITE.  This pull request updates call->got_offer depending on if answer or offer is handled.
=> Update call->got_offer when re-INVITE or answer to re-INVITE is received

mk/modules.mk
On Fedora/RHEL/CentOS, 64 bit libraries on multi-arch systems end up in `/usr/lib64`, thus it would be great if this path could be honored, too.
=> Test also for /usr/lib64/libspeexdsp.so to cover Fedora/RHEL/CentOS

src/config.c
Proposal to address #994; adding `-DDEFAULT_AUDIO_DEVICE=\"pulse\"` or similar to `$EXTRA_CFLAGS` should be suitable for Linux distributions needing this.
=> Allow distribution specific default audio device

src/config.c
Proposal to address #993; adding `-DDEFAULT_CAFILE=\"/etc/pki/tls/certs/ca-bundle.crt\"` or similar to `$EXTRA_CFLAGS` should be suitable for Linux distributions needing this.
=> Allow distribution specific CA trust bundle locations

include/baresip.h, src/config.c, src/net.c
Sometimes the system name server recognition fails (is empty) or a defect name server is used.
Now it is possible to define a separate fallback DNS server (without overwriting the system-side ones).
=> net: add fallback dns nameserver

src/config.c
Modern Linux distributions often prefer PulseAudio over ALSA, thus their default audio driver should be "pulse" rather "alsa"; derive the default audio driver from the default audio device, which can already be changed by using e.g. `-DDEFAULT_AUDIO_DEVICE=\"pulse\"` in `$EXTRA_CFLAGS`.
It completes the approach taken by #994 and #1001 and avoids for downstreams the need to batch baresip just to change the default.
=> Derive default audio driver from default audio device

modules/gtk/gtk_mod.c
On my KDE System I see the notification, but the accept / reject buttons will not work.
While debugging I found, that the call is not found after the pointer to int conversation.
With this PR i could make the buttons work and should not break any other Systems.
=> GTK notification buttons do not work on Systems

modules/pulse/player.c
The call to pa_simple_free in the auplay_destructor() sometimes crashed with a
segfault when it comes to quick after the last call to pa_simple_write(). This
occurs with libpulse 11.1.0.
=> pulse: drain pulse buffers before freeing

modules/jack/jack_play.c, modules/jack/jack_src.c
Simpler version of my previous request to modify info message generation when a new jack client is created:
1. Always message the new client name, even if this is the first jack client created.
2. Specify in the message the audio flow direction as source (audio flow out of client) or destination (audio flow into client).
Unlike my previous pull request, this info change is only for the new client creation message and more closely conforms to the project info message format.
=> Again, modifying info message on jack client creation

modules/jack/jack_play.c, modules/jack/jack_src.c
* When for example making a call with mono audio with 2 physical jack playback ports the audio was only routed to the left channel. This fixes the problem by connecting all physical playback ports to at least one of the baresip registered ports.
* Also added JackPortIsPhysical flag when looking up jack ports.
=> jack_play: connect all physical ports

modules/snapshot/png_vf.c, modules/snapshot/snapshot.c
Hi,
Here is a simple extension to snapshot module. It adds two additional commands `snapshot_recv path` and `snapshot_send path`. 
They create snapshot only from receiving video stream or sending video stream and save it to provided file path.
The old "snapshot" command works as it was, creating two png files in working directory.
Just need more control over snapshots for one of my projects.
=> Add snapshot_send and snapshot_recv commands

Makefile
With this change, debian package build works also when STATIC=yes.  There exists separate `make install-static`, but I would prefer `make install` to work also when the build is static.  If others don't think so, this pull request can be deleted.
=> Do not try to install modules if build is static

mk/modules.mk, modules/avfilter/avfilter.c, modules/avfilter/avfilter.h, modules/avfilter/filter.c, modules/avfilter/module.mk, modules/avfilter/util.c, modules/avfilter/util.h, src/config.c
Hi,
Here is my attempt to add FFmpeg filter graphs integration to baresip.
Idea is to allow dynamically set video filter graph for current video stream. And then remove it when needed.
It's implemented as baresip filter module and command `/avfilter`. For example to enable `vflip` simple filter graph just call `/avfilter vflip` at any time and see how video is flipped. To disable filter graph just send `/avfilter` command without any filter string.
As more complex example you can apply some png overlay on top of current video stream with
`/avfilter movie=/path/to/some/image.png[pic];[in][pic]overlay=(W-w)/2:H-h-20` command.
Full syntax and list of filters are available on FFmpeg Filtegraph's page: https://ffmpeg.org/ffmpeg-filters.html#Filtergraph-description
I run into several issues …
=> Add avfilter module/command

README.md
When testing out the build system I'm updating I found a build error.
After a bit of searching I found I had the upstream libre, not the
forked version that's now required to build, yet I had followed the
README instructions.  This should hopefully stop others falling into the
same trap.
=> Update the re project to install

mk/modules.mk
The first search path for avdevice.h should look in the "avdevice" directory, instead of "avformat".
=> fix search path for avdevice.h

modules/menu/menu.c, src/call.c, src/ua.c
A segfault occurs in modules loaded after menu and have an ua_event_handler
that use call object (to collect information about the call). The call object
may not be de-referenced in any ua_event_handler.
=> menu: fix segfault in ua_event_handler (#1059)

docs/examples/accounts, src/account.c, src/core.h, src/reg.c
Adds a parameter rwait to the account that set the re-register interval
relative to the proxy expiry time reported from the SIP proxy. This value was
hard-coded in libre to 90%.
This PR is based on libre PR https://github.com/baresip/re/pull/13.
=> account: add parameter rwait for re-register interval

include/baresip.h, modules/menu/menu.c, src/call.c, src/core.h, src/stream.c
This commit adds a command for the user to specify the video stream direction.
Possible directions:
none: disable the video at all
send: the client does not accept a video stream but will send a video steam
receive: the client will receive and display a video stream but will NOT send a video stream
duplex: normal bidirectional video call
=> call, stream, menu: add cmd to set the direction of video stream

modules/amr/module.mk
Added AMRWBENC_PATH env var to amr module module.mk and used it to check if AMR_WB should be enabled.  Allows installing vo-amrwbenc source directory outside of sysroot.
=> Added AMRWBENC_PATH env var to amr module module.mk

include/baresip.h, modules/menu/menu.c, src/ua.c
With these two commands a user can print the issuers and subjects of the certificate chain stored in SIP_certificate
=> ua, menue: new command to print certificate issuer and subject

include/baresip.h, modules/menu/menu.c, src/ua.c, test/call.c
ua: count calls globally for max_calls check
menu: for an outgoing call only play ringback for the current call
menu: remove redundant stop of play tone in cmd_hangup
menu: on call termination resume adequate play tone
menu: stop play tone also for call progress
menu: remove redundant call to menu_set_incall()
menu: correct incall decision for update_callstatus()
menu: do not start ringback tone during established call
=> Menu: corrections for ring tones and call status by means of a global call counter

docs/examples/config, mk/modules.mk, modules/httpreq/httpreq.c, modules/httpreq/module.mk, src/config.c
Provides the HTTP request feature of https://github.com/baresip/re/pull/33 in form of a new baresip module "httpreq".
- Makes use of struct network which also was moved to libre.
- GET, POST requests
- TLS
- basic, digest and bearer authentication
PR https://github.com/baresip/re/pull/34 adds struct network to libre.
Travis will be happy if https://github.com/baresip/re/pull/33 and https://github.com/baresip/re/pull/34 are merged.
=> Add a HTTP request module with authorization

modules/webrtc_aec/module.mk
Two changes:
(1) add link flags to $(MOD)_LFLAGS instead of LIBS so that they don't get listed in the very beginning of flags making other modules to use webrtc_aec specific libs
(2) added missing webrtc_sdk subdir x64 to path:
```
$ ls webrtc_sdk/lib/*/*
webrtc_sdk/lib/x64/Debug:
libwebrtc_full.a  pkgconfig/
webrtc_sdk/lib/x64/Release:
libwebrtc_full.a  pkgconfig/
```
=> modules/webrtc_aec: link flags fixes

mk/modules.mk
Make and link EXTRA_MODULES last so that when they are linked, their static libs don't get used by non-extra modules.
=> make EXTRA_MODULES last, not first

include/baresip.h, modules/menu/menu.c, src/ua.c, src/video.c
Implementation of a new dial command which allows the user to control the media stream directions. The media directions are passed via command arguments. This PR depends on #1125.
=> Cmd dialdir

modules/menu/dynamic_menu.c, modules/menu/menu.c, modules/menu/menu.h, modules/menu/module.mk, modules/menu/static_menu.c
In the PR #1125 @alfredh mentioned a refactoring of the menu module would make sense.
My proposal is to split it in the following way:
split menu into static and dynamic part
put both parts into separate files
command arrays are put into c files
command registration via register utility functions
ua_event_handler and related funtions stay in menu.c
=> menu: module refactoring

modules/httpreq/httpreq.c
Fixes segfault if parameter is not given.
=> httpreq: in cmd_setauth check if parameter was given

docs/examples/config, modules/mqtt/mqtt.c, src/config.c
The port was printed in a debug message before the default value
got overwritten by our config value, which confuses users if a
port other than the default port is used.
When passing the CA certificate of the broker with the new
mqtt_broker_cafile, then a TLS connection is established to the
broker. Usually used with mqtt_broker_port=8883.
=> mqtt: fix printing port and add tls support

docs/examples/config, modules/mqtt/mqtt.c
By not setting the new mqtt_subscribetopic or mqtt_publishtopic,
the default behavior of using the mqtt_basetopic option as a base
is used.
However, one can now configure the pub- and sub-topics completely
independent as well to allow multi-level wildcards or some custom
topic tree.
=> mqtt: allow to separate pub from sub topic base

docs/examples/config, include/baresip.h, src/audio.c, src/config.c, src/core.h, src/stream.c
audio, stream: put to and get from jitter buffer in two threads
During a call there is the RTP receive thread (A) and the auplay thread (B).
Previously the two threads had been connected by an aubuf. Thread A put the
RTP packets in the jbuf and also did a get in the same thread. Thus jbuf did
not really work as jitter buffer. Thread A did also the decoding and pushed the
data into the aubuf. Thread B fetched the data from the aubuf and pushed it to
the audio device.
Now in libre the jbuf was made thread safe and it works now as adaptive jitter
buffer. What means that the latency is controlled in reaction on the measured
network jitter.
Thread B has real time constraints and decoding could be to time consuming (e.g. on slow HW). We added a third thread X for decoding. Like shown in this …
=> Adaptive jbuf

docs/examples/config, modules/menu/menu.c, src/config.c
Adds these configurations for menu.c
- ring_aufile
- callwaiting_aufile
- ringback_aufile
- notfound_aufile
- busy_aufile
- error_aufile
Our next PR will make it possible to specify also mp3 or other files in the config. The playback then will be done with an ausrc. E.g. the module/gst makes it possible to play a couple of different file types.
=> menu: make audio files configurable

docs/examples/config, modules/aufile/aufile.c, src/config.c, src/play.c
Adds improved tone playback (play.c) by means of coupling ausrc with auplay.
- Uses aufile as first example.
- The aufile commits are only small fixes. (Depends on rem PR: https://github.com/baresip/rem/pull/1)
- By means of modules/gst it will be possible to play e.g. mp3 ring tones.
=> play ausrc

modules/aac/decode.c, modules/ctrl_dbus/module.mk, modules/jack/jack_play.c, modules/jack/jack_src.c
Needed for `mk/re.mk` re-enabled -Werror and -Wdeclaration-after-statement Flags. See baresip/re#58
=> Fix compiler warnings

modules/aufile/aufile.c, modules/aufile/aufile.h, modules/aufile/aufile_play.c, modules/aufile/module.mk
This works already:
```
audio_source  aufile,/usr/local/share/baresip/recorded.wav
```
This PR adds also the ouput to wav file:
```
audio_player		aufile,/tmp/output.wav
```
This can be used for debugging, audio analyzes or automatic tests.
=> aufile: add audio player to write speaker data to wav file

docs/examples/config, modules/aufile/aufile.c, src/config.c, src/play.c
This PR adds support for playing ring tones and other signal tones with an ausrc with different sample rates without resampling.
- As example we use aufile. We made aufile returning the sample rate and channels number.
- Adds PCMA/PCMU support to aufile.
- Fixes read until the end of aubuf in play.c.
- If the ausrc does not support returning the sample rate and channels number, new config settings are used.
=> Play aufile extended support

include/baresip.h, src/stream.c, src/video.c
The new function will open a NAT pinhole by sending a dummy
packet via the RTP port in case of no running video source.
This patch should fix the NAT pinhole topic in #1142
=> stream: add function to send a RTP dummy packet

modules/menu/dynamic_menu.c, src/call.c
See Issue #1142
Rename video_dir command to videodir to be consistent with the acceptdir and dialdir
Add stream direction information to output at re-Invite
=> Video dir rename

modules/aufile/aufile.c, modules/debug_cmd/debug_cmd.c, modules/gst/gst.c
This adds a command to debug_cmd that uses an ausrc (e.g. aufile) in order to count the samples and compute the length of the audio file in milli seconds.
The ausrc needs a new "blocking mode". As a first example we extend the aufile with a blocking mode.
Maybe later we also deliver our auogg (audio source for ogg files) or the gst module with a blocking mode.
=> Audio file info

modules/alsa/alsa_play.c, modules/omx/omx.c, modules/oss/oss.c
This fixes some remaining shorten-64-to-32 warnings. I leave `mixausrc` as is, so if @cspiel1 wants to provide a pull request for this.
=> clang shorten-64-to-32 warnings

mk/modules.mk, modules/mixausrc/mixausrc.c
Fixes the shorten-64-to-32 warnings for OSX (clang compiler)
=> Mixausrc warnings

modules/menu/menu.c
- fixes possible crashes when tmr_stat, tmr_redial are used
- also some other struct menu members have not been initialized
=> menu: initialize menu with zeros

src/ua.c
If ANSWERMODE_EARLY is set for the account an incoming call could not be
declined or hangup, because module menu did not set the current UA.
=> ua: for answer-mode early also send INCOMING event

docs/examples/config, include/baresip.h, modules/menu/menu.c, modules/menu/menu.h, modules/menu/static_menu.c, src/config.c, src/ua.c
Adds SIP auto answer for outgoing calls. Used SIP header can be chosen by config "sip_autoanswer_method":
sip_autoanswer_method | SIP Header                                                   
------------ | ------------------------------------------------------------ 
rfc5373      | Answer-Mode: Auto                                            
call-info    | Call-Info: \<http://www.notused.com>;answer-after=0           
alert-info   | Alert-Info: <...>;info=alert-autoanswer;delay=0
=> Sip auto answer caller

modules/menu/static_menu.c
Remove current account when no more accounts exist.
This should solve the issue: https://github.com/baresip/baresip/issues/1189
=> menu: fix segfault on last account deletion

modules/menu/static_menu.c
Allows to delete all user agents at once from within baresip.
=> menu: add uadelall to delete all user agents

modules/gtk/call_window.c, modules/gtk/gtk_mod.c
Fix parallel usage of CLI and GTK menu:
* Let notifications disappear, when accepting from CLI
* Fix race condition in call_window with mutex
* Fix use_after_free of vu enc/dec in call_window
=> Fix interaction between CLI menu and GTK menu

.github/workflows/build.yml, mk/modules.mk, modules/gtk/call_window.c, modules/gtk/dial_dialog.c, modules/gtk/gtk_mod.c, modules/gtk/module.mk, modules/gtk/transfer_dialog.c
Transition to a compiling GTK 3 build is rather seamless, but some deprecation warnings need further attention:
* Deprecation of status menu icon -> Should the application use a standalone widget instead of a status icon?
* Deprecation of gdk_threads_enter and friends -> Can be dealt with the/another message queue.
=> mod_gtk: switch to gtk 3

modules/opus/opus.c
This change fixes a malformation and eventual buffer overflow of the `fmtp` string that is generated when the Opus codec module is unloaded and reloaded in a static build configuration.
The issue is that the `fmtp` string relies on static initialization upon `dlopen` of the module - subsequent `init` does not reset back to a clean state in a static build configuration, and the string grows until it overflows its buffer.
The change forces `fmtp` to be reset to an empty string at `init` time.
=> opus: Ensure (re)init of fmtp strings

include/baresip.h, modules/ctrl_dbus/com.github.Baresip.xml, modules/ctrl_dbus/ctrl_dbus.c, modules/ctrl_tcp/ctrl_tcp.c, src/message.c
relay SIP MESSAGE to the application via:
- ctrl_tcp
- ctrl_dbus
The ctrl_dbus extension can be tested with:
```
dbus-monitor interface=com.github.Baresip
```
=> Sip message to application

include/baresip.h, src/message.c, src/ua.c, test/call.c, test/main.c, test/test.h
This allows to deny certain transport protocols (e.g. only allow TLS) for
incoming peer-to-peer calls. Also checks for correct address family which is
important if there is no af hint in the SDP.
@juha-h Now loosened the transport check. If the account does not specify a transport protocol, the check is omitted.
=> ua: improve UA selection for incoming calls

src/config.c, src/ua.c
With https://github.com/baresip/re/pull/67 SIP TLS connections will fail if no `sip_cafile` is specified. This PR enables `sip_cafile` in config by default on supported platforms or if `DEFAULT_CAFILE` is defined. And instead of fail hard with wrong `sip_cafile` path it warns only now.
=> Improve sip cafile handling

modules/menu/static_menu.c, src/ua.c
A first small step toward an intelligent call answer.
It is bound to the menu_uacur(). After merge of https://github.com/baresip/baresip/pull/1207 this is the UA of the active call.
For further improvements, should we consider an overall UA call answer strategy?
=> Intelligent call answer

docs/examples/config, include/baresip.h, src/config.c, src/ua.c, test/main.c
Adds a config flag sip_verfiy_server that disables the SIP TLS server verification.
By default server verification is turned on.
=> disable_verify_server_general

src/event.c
This allows the application to detect if the remote set us on hold/resume call.
The event CALL_REMOTE_SDP already exists. We have to add only the remote audio
direction to the encoded event data.
```
remote audio dir | application
-----------------|----------------------------
recvonly         | The remote set us on hold.
sendonly         | We set the call on hold.
sendrecv         | The call is active (again).
```
=> event: encode also remote audio direction

modules/ctrl_dbus/ctrl_dbus.c
Process commands in baresip main thread. This avoids un-expected behavior due to concurrency issues.
=> Ctrl dbus synchronize

src/ua.c
This commit loosens the checks for non-registered accounts to allow arbitrary
SIP URIs. This applies only to regint=0 accounts.
- For outgoing SIP requests: Setting regint=0 should not be done to disable a
SIP registration account.
- For incoming SIP requests: Only the SIP messages URI has to match the local
IP address. The accounts URI is arbitrary.
=> ua: for UA selection allow arbitrary aor for regint=0 accounts

docs/examples/config, src/config.c
This commit disables the server verification for old TLS configurations.
Requested by: @juha-h 
Please vote for or against this: @juha-h,  @alfredh, @sreimers , others?
I am not 100% for this commit, because we have to ensure for our products that a config line is added. If it is forgotten, then we believe that SIP TLS is safe. But it isn't.
This has to be added.
```
sip_verify_server	yes
```
Of course our testing have to do negative tests also for SIP TLS.
=> config: disables server verification if sip_verify_server is missing

modules/jack/jack_play.c, modules/jack/jack_src.c
For jack_play and jack_src:
- Added support for setting port pattern (regexp) for ports to connect as device string in config file. For example:
`audio_player              jack,^system:playback_(1|2)$`
`audio_source             jack,^system:capture_(1|2)$`
- If no device is specified it works as before, connect to all physical ports
=> jack: support port pattern in config file

modules/menu/menu.c
If starting multiple outgoing calls in a row, then start the playback of the
ringback sound only for the first call. This prevents that the playback is re-
started several times.
Note: But, we still switch the current call id two the last outgoing call in this case. Thus if hangup is called, then the last outgoing call will be terminated.
=> menu: start ringback only once for parallel calls

modules/menu/dynamic_menu.c, modules/menu/static_menu.c
- Do not use returned error code re_hprintf() as return err code for commands.
Except in print commands.
- Replace warnings() and info() by re_hprintf() where a pf is available.
- Return EINVAL if call was not found.
Suggest also a unified print format of "some error (%m)" in menu. Let me know if you should add this!
=> menu: use print backend pointer pf correctly

mk/modules.mk, modules/multicast/module.mk, modules/multicast/multicast.c, modules/multicast/multicast.h, modules/multicast/player.c, modules/multicast/receiver.c, modules/multicast/sender.c, modules/multicast/source.c
This module depends on [re#77](https://github.com/baresip/re/pull/77).
A new baresip module which allows the user to send and receive RTP streams.
Supported audio codecs: PCMU, PCMA, G722
The receiver contains a priority logic, which allows the user to decide the importance of the streams.
The core SIP-call is not affected from this module. A call has always the highest priority. Receiving a call or making a call will stop all sender and receiver of this module.
=> Multicast module

modules/avformat/avformat.c, modules/avformat/video.c
This makes mjpeg decoding on avformat+v4l2 with hwaccel vaapi (common in GNU/Linux specially with Intel CPUs). It works fine here with almost no cpu use on vidloop at 720p 30fps.
All is hardcoded so... how do you see adding some config values to handle this?
Something like:
avformat_hwaccel vaapi           # ffmpeg -hwaccel vaapi ....
avformat_inputformat mjpeg     # ffmpeg -input_format -f v4l2 ...
=> RFC: Make avformat decode mjpeg v4l2 with vaapi

include/baresip.h, modules/menu/dynamic_menu.c, modules/menu/menu.c, src/ua.c
Prevent barsip from having multiple "onhold == false" calls. Resuming a call will replace the active call to the resumed one.
The handling of UA_EVENT_CALL_REMOTE_SDP is added to ensure that the menu does get the resumed call as active call.
Otherwise cmd_hangup will trigger the UA_EVENT_CALL_CLOSED and the menu.callid is removed. All commands with menu_uacur() will not work anymore.
=> Fix multiple resumed calls

modules/menu/menu.c, modules/menu/static_menu.c, src/ua.c
Related to (first point in) https://github.com/baresip/baresip/issues/1243.
We found that to resume a call if another call terminates is not always correct.
We  also decided that menu should invoke the resume, not UA directly. If somebody prefers to let this logic in UA, let me know and I will change this!
Note: The second point in the issue (avoid multiple established calls) will be handled in a different PR. This will be handled also in menu.
=> Call resume on hangup

include/baresip.h, modules/menu/menu.c, modules/menu/static_menu.c, src/ua.c
Related to https://github.com/baresip/baresip/issues/1243 (second point).
- Adds a new function uag_hold_others(call).
- For outgoing calls that become established uag_hold_others() is called in the ua_event_handler().
- For incoming calls the command accept and acceptdir have to use uag_hold_others().
@alfredh: Should we split uag from ua.c --> uag.c? Maybe in a soon next PR?
=> Menu ensure only one established call

src/ua.c
Fixes "Invalid read", a wrong le->data cast.
=> ua: fix uag_hold_others use of wrong list element

src/call.c
Related to: https://github.com/baresip/baresip/issues/1261
This fixes a problem with ALSA. The ALSA playback device can not be opened
because the ringback tone is not stopped before.
=> call: start streams asynchronously

modules/avformat/avformat.c
In my prev PR I missed this and made this parameter mandatory.
I think it should not be; it should figure out the decoder automatically, if not set.
=> Optional avformat decoder

include/baresip.h, src/config.c, src/ua.c
With the new on hold changes in `menu`, use cases like handling multiple separate calls are not possible anymore (like providing multiple test instances with `echo` or `ausine`). I think putting calls on hold should be optional.
=> conf: add call_hold_other_calls config option

modules/menu/menu.c
Resume another call on termination of a call  does not work correctly if the
call was hangup locally. Anyway, this feature is business logic and should not
be done by baresip automatically.
=> menu: remove call resume on termination

modules/gst/gst.c
=> gst: add missing include unistd.h

docs/examples/config, include/baresip.h, modules/menu/dynamic_menu.c, modules/menu/menu.c, modules/menu/menu.h, src/config.c, src/core.h, src/ua.c
Replaces #1273.
- ringback tone was not played
- fixes when and what to play for incoming calls
- resume right tone if a call terminates
- remove ANSI bell alert
=> Menu fixes for play tones2

include/baresip.h, modules/menu/static_menu.c, modules/multicast/multicast.c, modules/multicast/multicast.h, modules/multicast/receiver.c, src/config.c, src/ua.c
Introduce a new config parameter "multicast_call_prio" to allow the multicast module having receivers with higher priority than a call. To prevent barsip from incoming and outgoing calls two new flags are added in the uag. On the incoming side, the DnD  reject all requests with the error 480 "Temporarily Unavailable". On the other side, the noDial flag prevents users from initiating calls.
Removing "multicast_call_prio" from the config or assigning it to 0 will ensure that a call will always be prioritized.
In cases where a multicast does have a higher priority than a call, the module takes advantage of the DnD and noDial flags. If all streams with high priority are done, the module switches back the flags. For established calls, these calls are set on_hold until the multicast is finished …
=> Multicast call priority

include/baresip.h, src/config.c, src/ua.c
Same PR like #1295. Renaming of the branch for automated testing.
adds an config option to add capath
requires re/#84
The ca_path is does have the same meaning like in [openSSL/SSL_CTX_load_verify_locations](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_load_verify_locations.html).  The ca_file defines a file with (maybe) many certificates in one file. While the ca_path defines a directory containing (maybe) many certificates as single files.  The verification checks will check first the one defined in ca_file, then go on to the ca_path certificates.
=> tls: more generic function to set cafile and capath

modules/serreg/serreg.c, src/reg.c
- useful reginfo printing if account prios are configured
- serreg: fixes for serial mode (accounts with fbregint=0)
accounts:
```
"chris" <sip:1004@xxx:15060>;auth_pass=xxxx;regint=10;prio=0;fbregint=4
"chris" <sip:1001@10.1.0.215:15060>;auth_pass=xxxx;regint=10;prio=1;fbregint=4
```
```
3 - sip:1004@xxx:15060                          OK   Expires 10s
24 - sip:1001@10.1.0.215:15060                  FB-OK  
```
The first with “OK” is registered and shows the expiry time.
The second shows only “FB-OK” which means fallback proxy is reachable.
```
13 - sip:1004@xxx:15060                         FB-ERR 
24 - sip:1001@10.1.0.215:15060                  OK   Expires 10s
```
Here the first one shows that the fallback proxy is not reachable. The second proxy is registered.
```
14 - …
```
=> Serreg fixes

docs/examples/config, src/config.c
The example config should be the same like generated by config_write_template()
@alfredh already stated that we should add a Configuration section in the wiki. I am about to start this. Because I have to do this anyway now for the application developer in my company.
Proposition:
A new section "Configuration" with sections for
- the core-config and
- the accounts parameter
The modules configuration should be done in the module pages.
=> Docs examples config

include/baresip.h, modules/menu/menu.c, modules/menu/menu.h, modules/menu/static_menu.c, src/ua.c
This PR should replace the uag_find_call_state() by the new uag_filter_calls(). But the uag_filter_calls() seems not to be useful for all use-cases of uag_find_call_state() in module menu.
@juha-h I couldn't find a simpler solution for the use case in menu_selcall() which selects a call when a call terminates.
It looks first for a CALL_STATE_ESTABLISHED, then CALL_STATE_EARLY, then CALL_STATE_RINGING, ...
If you like this PR anyway, you may merge it.
=> ua,menu: remove uag_find_call_state

modules/avformat/avformat.c
hi @sreimers
should we consider dropping ubuntu 16.04 support ?
ffmpeg version:
2.8.17-0ubuntu0.1 [security]: amd64 i386 
https://github.com/baresip/baresip/wiki/Supported-platforms#supported-version-of-ffmpeg
=> avformat: clean up ifdefs

src/main.c
Issue https://github.com/baresip/baresip/issues/1309
Fixes segfault with double Ctrl+c.
=> main: unload app modules in signal handler

modules/menu/menu.c
Otherwise ringback might not be started for next outgoing call.
=> menu: use menu_stop_play()

modules/menu/dynamic_menu.c
The selection of the call was missing.
=> menu: select call in cmd_find_call()

modules/menu/static_menu.c
E.g. module ctrl_dbus will return the call id in the dbus response.
```
$ qdbus com.github.Baresip /baresip com.github.Baresip.invoke "dial 10.1.0.215"
call id: bde55d2528902248
```
Can be used for following call specific commands e.g. hangup, without the need
to query calls with "listcalls".
=> menu: return call-id for dial and dialdir

include/baresip.h, src/net.c
I changed the name 'dns_refresh' to 'net_dns_refresh' and made it public.
=> Changed name and made public

include/baresip.h, modules/snapshot/png_vf.c, src/event.c
It was clearer to add new event rather than use UA_CUSTOM_EVENT.  Did not see use for new event category.
=> Nw event UA_EVENT_SNAPSHOT to tell to app when snapshot has been written

include/baresip.h, modules/snapshot/png_vf.c, src/event.c
This PR should ensure a more uniform format for events generated by modules.
Following PRs: Maybe we are able to replace the already used UA_EVENT_CUSTOM events in other modules also.
=> Module event

src/ui.c
a memory leak can be triggered with this command:
```
$ ./baresip -ed
```
```
Quit
ua: stop all (forced=0)
mem: Memory leaks (3):
0x7fbb947381f0: nrefs=1  size=24      [50 82 73 94 bb 7f 00 00 70 55 53 16 01 00 00 00 ] [P.s.....pUS.....]
0x7fbb94738250: nrefs=1  size=32      [b0 82 73 94 bb 7f 00 00 20 00 00 00 00 00 00 00 ] [..s..... .......]
0x7fbb947382b0: nrefs=1  size=32      [00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ] [................]
```
it will leak the ctx in ui_input_pl
=> ui: fix leaking of cmd_ctx

modules/gtk/gtk_mod.c, modules/gtk/gtk_mod.h
GTK was no longer able to dial since the URI was not auto completed.
=> gtk with account_uri_complete

modules/ctrl_dbus/ctrl_dbus.c, modules/gtk/gtk_mod.c
Unify overlefts from `com.creytiv.*` (or similar) to `com.github.*`.
See also: https://en.wikipedia.org/wiki/Reverse_domain_name_notation
=> Correct reverse domain name notation

mk/modules.mk, modules/snapshot/module.mk
An attempt to clarify the unknown status of these modules (fixes #1341).
=> Document and enable rtcpsummary and snapshot modules

src/call.c, test/ua.c
Remove the attribute "tool: baresip vx.x.xx" from the SDP, because it seems to
result in "488 SDP Parameter Error" with some SIP/PSTN gateways. This solves
issue #1351.
=> call: remove tool attribute from SDP

modules/ctrl_dbus/ctrl_dbus.c
- The dbus call to invoke writes exactly one byte.
- This wakes command_handler() which reads exactly one byte.
- If byte could not be written, do not wait for the command_handler().
This constraints should avoid deadlocks.
=> ctrl_dbus: ensure save synchronization (#1358)

src/audio.c
added ifdef checks.
builds and works with and without the `HAVE_PTHREAD` flag
=> should fix #1364

modules/avcapture/avcapture.m
=> avcapture: fix macos 10.15 devicesWithMediaType deprecation warning

modules/multicast/multicast.c, modules/multicast/player.c, modules/multicast/receiver.c, modules/multicast/sender.c, modules/multicast/source.c
Removes the warnings for the module/multicast listed in #1368
=> multicast: remove clang static analyzer warnings

src/account.c
This adds support for dialing IP-address with given transport protocol.
Function `account_uri_complete()` should make a from a user-input dial URI that might not be fully RFC conform a fully RFC conform SIP URI.
But dial URIs like:
```
10.1.0.215;transport=tcp
```
result in an nonsense URI
```
sip:10.1.0.215;transport=tcp@localhost
```
@alfredh If you like it, we maybe should put it into 1.1.0.
=> account: allow also ip;transport=tcp as valid dial URI

src/config.c
- In case no sip_cafile or sip_capath is configured. sip_verify_server is false.
- The sip_verify_server option in the config file overrules the decision via sip_cafile and sip_capath.
- The standard config template shows the possibility of a sip_verify_server option. But it is not active.
=> config: enable sip_verify_server if sip_cafile or sip_capath is set

modules/debug_cmd/debug_cmd.c
Use unified format for module events in module debug_cmd.
=> debug_cmd: use module_event() for aufileinfo events

modules/ctrl_dbus/ctrl_dbus.c
Use unified format for the event sent from ctrl_dbus module.
=> ctrl_dbus: use module_event() to send exported event

modules/gtk/gtk_mod.c, modules/gtk/gtk_mod.h
A simple caller history on the gtk module.
Tracks up to 20 missed / outgoing / incoming calls.
=> GTK caller history

modules/menu/menu.c
The ringtone has to be played on separate audio device. Differently from audio speech.
I don't think that anybody has a problem that the ring and other signal tones are played on `audio_alert` where currently only the message.wav is played.
An option would be to add a new setting. But in order to keep the config as simple as possible, we prefer this solution.
=> menu: play ringtone on audio_alert device

modules/menu/dynamic_menu.c, modules/menu/static_menu.c
Fixes the commands in combination with module ctrl_tcp where the carg->prm
are empty strings if not specified.
=> menu: use str_isset() for command parameter

docs/examples/config, modules/dtls_srtp/dtls_srtp.c, src/config.c
The used curve is configured in the config file via "dtls_srtp_use_ec".
=> dtls_srtp: use elliptic curve cryptography

docs/examples/accounts, src/account.c, src/core.h, src/ua.c
This PR depends on [#96](https://github.com/baresip/re/pull/96)
It allows the user to specify different client certificates for different
accounts in the accounts file.
SIP proxies environments may not allow installing new trusted certificates. In 
the same time they may have a certificate installed which is used to issue
new SIP certificates. For a single server it is no problem, since a user could
configure the server generated certificate as the SIP_certificate in the
config file. Having multiple such servers (maybe as fallback servers)
leads to a problem where baresip is currently not able to handle a variety of
client certificates.
This PR overcomes exactly the described problem.
In case a user has more than one account on the same SIP proxy. The connection
TLS handshake is done …
=> Tls sipcert per acc

docs/examples/accounts, include/baresip.h, modules/account/account.c, src/account.c, src/core.h, src/ua.c
```diff
+#    ;mediaaf={ipv4,ipv6}
```
This makes most sense for local accounts (regint=0). The logic is already in ua.c. This PR adds only the setting in accounts file.
=> account: add accounts parameter to force media address family

include/baresip.h, modules/menu/static_menu.c, src/core.h, src/ua.c, src/uag.c
- The UA at head will be used for a dial to a user only URI.
- Command uafind also switches the active call if there is one at this UA.
This solution replaces the already removed `uanext` ("current UA") solution. The benefit is that `uag_find_requri()` selects an adequate UA regarding these rules: If URI looks like
- user --> selects the head UA
- user@domain --> selects the UA whose account host matches domain
@juha-h This might be useful for baresip-studio.
=> menu: command uafind raises UA to head

modules/menu/static_menu.c
A first commit in a series for intercom features.
- Feature: Announcement (talk in one direction)
This adds the auto answer to command dialdir similar to command dial.
=> menu: enable auto answer calls also for command dialdir

modules/menu/dynamic_menu.c, modules/menu/menu.c, modules/menu/menu.h, modules/menu/static_menu.c
Intercom feature: Force Privacy Interruption
- Talk ( + video ) in one direction from A to B
- B wants to switch to audio ( + video ) to bi-directional with a re-INVITE
This PR lets A change its local audio + video directions per menu command. Otherwise the re-INVITE from B to A will not have an effect.
=> menu: add command for settings media local direction

docs/examples/accounts, modules/account/account.c
Some cleanup for the accounts examples in template and docs.
- regint has to be specified for SIP registrar accounts
- user:password is not supported. Instead auth_pass.
=> Accounts example cleanup

modules/menu/menu.c, src/call.c
If a call is in state CALL_STATE_OUTGOING and the remote does not answer, e.g.
if the remote is not available, then the call can not be canceled by command
"hangup" without specifying the call-id.
Fixes: #1416
Not solved: `dial_handler()` returns the call-id. This gives only a useful result if no media-nat is configured.
A solution would mean to generate the call-id in baresip core, pass it to libre as optional call-id where it is used in sip_dialog. `sip_dialog_alloc()` will generate a random call-id if is not given as parameter (like it does now). --> This needs a change in the libre API function `sip_dialog_alloc()` and `sipsess_connect()`.
=> menu,call: fix hangup for outgoing call

modules/multicast/multicast.c, modules/multicast/multicast.h, modules/multicast/player.c, modules/multicast/sender.c, modules/multicast/source.c
This adds some API calls which are useful for the exchangeable multicast source/player.
=> multicast: add source and player API calls

modules/menu/static_menu.c
This can be used to match with event CALL_LOCAL_SDP field `peeruri` to identify
the right call. Then the field `id` of this event then contains the correct
call-id.
If media nat is configured, then the call-id is not given, when these commands
return. The above process is a work-around to determine the call-id.
=> menu: return complete URI for commands dial,dialdir

modules/menu/static_menu.c
Instead of
```
ua = uag_find_requri("sip:alice@sipproxy.org audio=sendrecv video=sendrecv")
```
it should be:
```
ua = uag_find_requri("sip:alice@sipproxy.org")
```
=> menu: in command dialdir call uag_find_requri() with uri

include/baresip.h, src/call.c
call: add a setter function for answer delay
Can be used to override the SIP auto answer delay from an external application/module. E.g. Set it back to -1, which suppresses the auto answer.
The baresip-apps PR https://github.com/baresip/baresip-apps/pull/2 introduces an intercom module with privacy mode. If privacy is on, the SIP auto answer is suppressed.
TODO: override ringtones for module menu, or prevent menu from ringing for intercom calls
=> Work on Intercom module

include/baresip.h, modules/gtk/call_window.c, modules/gtk/dial_dialog.c, modules/gtk/gtk_mod.c, modules/gtk/gtk_mod.h, modules/menu/static_menu.c, src/call.c
I implemented an attended transfer for gtk.
It still has some rough edges, e.g. you have to set the call on hold manually to enable attended transfer, but it is functional (at least it worked on a `starface` telephony system.
Edit: I also fixed a bug with clean number in this merge request, which includes `ctype.h` on the `menu` and `gtk` module. It seems that either a contact formatted entry returns a errorcode from `re_regex` or I missunderstood how the function should be used.
On a sidenote, I could segfault re_regex with `int err = re_regex(str, str_len(str), "[0-9]+");` (I wanted to check "[0-9\\-\\.\\+\\(\\)"]+, but it to showcase the error, this was the shortest regex I tested) and the following string: `"Doe, John" <sip:75@192.0.2.55>`, which is why i now check the string with …
=> Attended Transfer on GTK

docs/examples/accounts, modules/account/account.c
Just realized that the default value of regint is ~3600 seconds, not zero.
These two commits do not fully revert my previous changes in docs/examples and accounts template.
=> Accounts examples and template

modules/gst/gst.c
Some WAV files are played much too fast especially if the depth is not 16 bit and the sampling rate is not 16000. 
The behavior can be tested with the file pcm0822m.wav attached:
[pcm0822m.wav.gz](https://github.com/baresip/baresip/files/6457570/pcm0822m.wav.gz)
=> gst: audio playback not correct for some WAV files.

modules/menu/menu.c, modules/menu/menu.h
Allow other modules loaded before menu to override played ring-, ringback and other signal tones.
E.g. module intercom in baresip-apps is able to replace the aufile configuration keys of menu by its own configuration keys
in order to specify separate audio files.
The overrides are call related and can be set via module events.
Example: https://github.com/baresip/baresip-apps/tree/main/modules/intercom
=> Working on intercom (ringtone override)

modules/amr/amr.c, modules/amr/amr.h, modules/amr/sdp.c
Basic support for AMR Bandwidth Efficient mode. Original code hade support for 'octet aligned' mode only; with this code added both modes are supported. This code changes the default proposed mode from Baresip from octet aligned to bandwidth efficient.
Interop testing is OK with:
1. MicroSIP client (which seems to run only octet-aligned') 
2. PSTN carrier supporting both modes with bandwidth efficient being default
3. Mitel hardware SIP phone
4. MX-ONE PBX
=> AMR Bandwidth Efficient mode support

modules/account/account.c
This prevents registration of un-configured baresip.
=> account: comment out very basic example in template

modules/menu/dynamic_menu.c, modules/menu/static_menu.c, src/call.c, src/stream.c
- In combination with re PR https://github.com/baresip/re/pull/103 fixes audio only calls. There was an RTP timeout for the video stream.
- Fixes also one-directional `acceptdir` for incoming early-video calls.
=> call answer media dir

docs/examples/accounts, docs/examples/config, include/baresip.h, modules/account/account.c, modules/menu/menu.c, src/account.c, src/config.c, src/core.h
The flag `sip_autoanswer_beep` is moved from config to account because there might be SIP servers that stream the beep tone at the beginning of an intercom call. For peer-to-peer intercom calls the beep tone should be played locally.
Instead of a bool we use an enum. Reason:
**Following PR** will support also Beep tone specified in the Alert-Info headers URI.
```
Alert-Info: <file:///usr/local/share/baresip/autoanswer.wav>;info=alert-autoanswer;delay=0
```
Thus the enum has the values:
- SIPANSBEEP_ON    ... The beep is played before the call is answered automatically. The locally configured audio file can
be overwritten with the Alert-Info header URL. This is the default value.
- SIPANSBEEP_OFF   ... No beep is played.
- SIPANSBEEP_LOCAL ... The local configured beep tone is played.
=> Account auto answer beep

modules/serreg/serreg.c
For the "Serial registration mode" stop the registration not before all
accounts with same prio failed. It is best to do this in register_curprio().
=> serreg: unregister correct User-Agents on registration failure

src/stream.c
Fixes the unwanted call termination by the  `check_rtp_handler` for an audio-only call in an audio+video setup.
=> stream: check if media is present before enabling the RTP timeout

modules/aubridge/device.c, modules/aufile/aufile.c, modules/ausine/ausine.c, modules/gst/gst.c, modules/multicast/player.c, modules/multicast/source.c, modules/pulse/recorder.c, modules/rst/audio.c, src/audio.c
https://github.com/baresip/baresip/commit/1ef3a96412667581ac35547c53394426a8a261c1 added `srate` and `ch` to `auframe`. However there are several cases where the values are not actually set. If I haven't missed anything, this should fix the remaining cases.
=> auframe: always set srate and ch

include/baresip.h, modules/menu/menu.c, modules/menu/menu.h, modules/menu/static_menu.c, src/call.c, src/play.c, src/ua.c
Add support for overriding beep tone with Alert-Info URI. E.g.
```
Alert-Info: <file:///usr/local/share/baresip/autoanswer.wav>;info=alert-autoanswer;delay=0
```
```
Alert-Info: <https://github.com/baresip/baresip/raw/master/share/soundd.wav>;info=alert-autoanswer;delay=0
```
1. At callee side:
- accounts
```
"A" <sip:A@localhost>;regint=0;sip_autoanswer=yes
```
- config
```
module			gst.so
file_ausrc		gst
```
2. At caller side invoke:
```
/setadelay 0
/setansval <https://github.com/baresip/baresip/raw/master/share/soundd.wav>
/dial callee-IP
```
=> auto answer beep per alert info URI

include/baresip.h, modules/menu/menu.c, src/account.c, src/core.h, src/ua.c
This simplifies auto answer mode and the handling for the answer delay.
- The account answer delay is handled in menu instead of ua.c.
- The `ANSWERMODE_AUTO` simply answer the call immediately.
After this PR is merged, I will update the wiki.
=> ua, menu: move auto answer delay handling to menu (#1474)

src/account.c, test/account.c, test/main.c, test/test.h
```
/dial [IPv6]
```
lead to wrong append of the account host
```
sip:[IPv6]@account-host
```
=> account: fix IPv6 only URI for account_uri_complete()

modules/menu/static_menu.c
A cleanup PR.
Planning to add a next PR that adds commands for enabling/disabling UDP/TCP/TLS transport protocols during runtime.
```
/entcp <bool>
/enudp <bool>
/entls <bool>
```
=> fmt: add string to bool function

src/reg.c
- Find first successfully registered proxy correctly.
- Show FB (fallback) flag only if fbregint was set in `reg_status()`
=> registration fixes

docs/examples/config, include/baresip.h, src/audio.c, src/config.c
RFC-4733 tells that the payload type for the telephone-event should be set
dynamically. Baresip sets it to 101 if it is available. This commit adds a
setting for the payload type with default value 101.
=> config,audio: add setting audio.telev_pt

src/core.h, src/stream.c
Fixes #1494 
Tested with `jitter_buffer_type` `off`, `fixed` and `adaptive`.
Problem consists since dbb4a985ca4184b73bb32a4e490d9a154ee327b3.
@alfredh I can remember that you wanted to call the `s->pth()` only if the pt differ from the audio codec pt. The solution with `s->pt_dec` was wrong. What we want is to check if `rx->pt` differs from `hdr->pt`. In `stream.c` we don't have the `rx->pt`. So the simplest solution is to call `s->pth()` for each RTP packet and do the check in audio.c (video.c).
Found the old PR: https://github.com/baresip/baresip/pull/1128
=> stream: fix telephone event (#1494)

mk/modules.mk, modules/i2s/i2s_play.c, modules/i2s/i2s_src.c
This PR makes the I2S module compile again using auframe.
However, the microphone does not seem to work.
=> Fix I2S compile error, use auframe

docs/examples/accounts, include/baresip.h, src/account.c, src/audio.c, src/core.h
It makes sense to make the config option for telephone-event payload type per account.
=> account: add setting audio payload type for telephone-event

src/config.c, src/core.h, src/uag.c
- Fix: WS was enabled because it is a partial string of WSS
- write a sip_transports line to template
- add sip_transports to config_print()
- do not pass a pointer to u32mask_enabled()
=> confg,uag: rework on sip_transports setting

include/baresip.h, modules/menu/menu.c, src/call.c, src/ua.c
In case the peer is not capable of video, handle the incoming
call as normal call without pre video.
=> ua: check if peer is capable of video for early video

include/baresip.h, src/account.c, src/core.h
This allows to disable video for specific accounts.
Examples to disable video:
```
<sip:user@example.com>;video_codecs=
<sip:user@example.com>;video_codecs=none
```
=> account: add enable/disable flag for video

src/net.c
I know we discussed once about to remove all the HAVE_INET6 switches. But then baresip will not build on old systems.
Currently indeed we have a customer that didn't activate IPv6 on their devices.
=> net: add missing HAVE_INET6

docs/examples/config, modules/multicast/multicast.c, modules/multicast/multicast.h, modules/multicast/sender.c, src/config.c
The standard value of TTL for a multicast addesse is 1 to limit the multicast package range to the local network. In some networks it might be necessary to set the multicast TTL value to higher values than 1. This TTL value is now configurable via the `multicast_ttl` config parameter.
The value for the underlying UDP socket is set in the multicast/sender.c since it is a multicast module related option.
If somebody wants to be able to set the TTL for any RTP socket, it is possible to move the part into libre/rtp.
=> multicast: add new configurable multicast TTL config parameter

src/call.c
In #1526 i took the wrong remote direction for this check.
Now if the caller is capable of video sendonly, the callee actually can request a video stream from the caller to the callee.
Tested with accounts:
`"coffeeA"<sip:coffeeA@192.168.1.1>;regint=0;answermode=early-video` (callee)
`"coffeeB"<sip:coffeeB@192.168.1.1>;regint=0` (caller)
coffeeB: `/dialdir coffeeA audio=sendrecv video=sendonly`: Early video is established. After Call established unidirectional video since coffeeB is in video=sendonly
coffeeB: `/dialdir coffeeA audio=sendrecv video=sendrecv`: Early video is established. After Call established bidirectional video
coffeeB: `/dialdir coffeeA audio=sendrecv video=inactive`: Handle the call without 183 Session Progress as normal call.
=> call: fix early video capability check (wrong SDP direction checked)

src/audio.c
If the error code equals 0 in the _ausrc_error_handler_, only a warning is logged and the error is not forwarded.
=> audio: catch end of file message in ausrc error handler (#1539)

modules/menu/dynamic_menu.c
Added new command _stopringing_:
Stops the audio player of the menu (e.g. playback of ring.wav, or ringback.wav)
=> menu: added stopringing command

src/call.c
based on https://github.com/baresip/re/pull/135
The call-id should be returned to the application immediately. This is in the first event: CALL_EVENT_OUTGOING
=> outgoing calls early callid

modules/serreg/serreg.c
In case all SIP servers go down (primary and the fallback servers) and one of the fallback servers comes back online, the serreg modules does not register at this server.
The module polls the information that a fallback server is back online. In the case of the fallback server, the module never register on that server since it behaves like it is already registered at the primary server.
A boolean flag is introduced to save the registration state information if any server is registered. If the flag is false, just register at the highest prio server which is available.
=> serreg: fix server selection in case all server were unavailable

modules/multicast/player.c
found with Coverity Scan:
```c
if (!player->thr.run) {
345                int err;
346
347                player->thr.run = true;
348                err = pthread_create(&player->thr.tid, NULL,
349                        rx_thread, player);
4. Condition err, taking true branch.
350                if (err) {
351                        player->thr.run = false;
CID 331124 (#1 of 1): Missing unlock (LOCK)
5. missing_unlock: Returning without unlocking player->thr.mutex.
352                        return;
353                }
354        }
355
356        pthread_cond_signal(&player->thr.cond);
357        pthread_mutex_unlock(&player->thr.mutex);
```
@cHuberCoffee
=> multicast: fix missing unlock

src/config.c
Here is the fix.  How can I add the CID number of the Code Coverity Scan?
=> config: replace strcpy by saver re_snprintf (#1558)

docs/examples/config, include/baresip.h, modules/multicast/receiver.c, src/conf.c, src/config.c, src/core.h
If multiple baresip instances which are in near range receive a multicast RTP
stream, it should be possible to adjust their playback latency to achieve a
simultaneous audio playback on all devices.
On the other hand the jitter buffer configuration for a SIP call should be
optimized to minimum latency.
=> multicast,config: add separate jitter buffer configuration

src/ua.c
E.g. if someone invokes command `uadelall`, no UA_EVENT_CALL_CLOSED was sent for ongoing calls.
=> ua: emit CALL_CLOSED event when user agent is deleted

include/baresip.h, src/core.h
For RTP Connections like webrtc (module/app) its useful to make `stream_enable_rtp_timeout` available.
=> core: move stream_enable_rtp_timeout to api

modules/avcodec/avcodec.h
supported ffmpeg:
FFmpeg 3.2.14 "Hypatia" or later
=> avcodec: remove old backwards compat wrapper

include/baresip.h, modules/menu/menu.c, src/uag.c
- uag: add argument to call match handler for uag_filter_calls()
- menu: play ringback and error tone correctly for parallel call feature
- If there are multiple outgoing calls and the peers all reject the calls, then
the error tone only should be played if the last call was rejected.
- When an outgoing call was rejected, the function menu_selcall() did not
select another outgoing call.
=> menu fix tones for parallel outgoing calls

modules/dshow/dshow.cpp, modules/menu/static_menu.c, src/video.c
p.s. I would like to write tests for case with `clean_number `. 
How do you look at adding the ability to run tests in the visual studio?
And to simplify access to the `clean_number` method, it would be well to remove the static attribute from it, otherwise it is so difficult to call through `dial_handler`. 
if you agree, I will prepare a new PR, in which I will add a new visual studio project, only for running tests, and the new test itself.
=> Fix static analyzer warnings

docs/examples/accounts, include/baresip.h, modules/account/account.c, src/account.c, src/call.c
Added new value DTMFMODE_AUTO to the dtmfmode enumeration.
If this value is selected, it is checked whether the remote station has a media typefor the "telephone-event" in the sdp description.
If not, then the DTMF digit is sent as a sip info message, otherwise as an RTP event.
=> call: added auto dtmf mode

modules/mixausrc/mixausrc.c
Fixes a lot of
```
mixausrc: sampc changed 160 --> 320.
mixausrc: sampc changed 160 --> 320.
mixausrc: sampc changed 160 --> 320.
mixausrc: sampc changed 160 --> 320.
mixausrc: sampc changed 160 --> 320.
```
in situations where the sample rate/codec changes.
=> mixausrc: no warnings flood when sampc changes

src/ua.c
Re-opens: https://github.com/baresip/baresip/pull/1556
For incoming calls (INVITE) we get an SDP offer and can use the contained IP
address `dst` to find a local address which has a route to `dst`.
The function `sdp_connection()` replaces the `sdp_af_hint()` and still
retrieves the address family from the SDP offer. As fallback use address family
of SIP message source.
Checking if the address family is supported can be done also in
`ua_call_alloc()`. This avoids similar code in `sipsess_conn_handler()`.
=> ua: select laddr with route to SDP offer address

include/baresip.h, src/net.c, src/uag.c
Simplifies function `uri_host_local()` and add support for incoming
peer-to-peer calls with SIP URI user@domain.
=> net,uag: allow incoming peer-to-peer calls with user@domain

src/baresip.c, src/net.c
Allows baresip to start without any network interface/local IP.
Instead only prints a warning.
The network addresses can be added later.
=> start without network

modules/multicast/multicast.c, modules/multicast/receiver.c
* Allow any port number for any multicast direction
* Warn the user about an odd port number
* The implementation uses a plain UDP socket
* The payload of the UDP package gets fixed decoded as RTP package
=> multicast: allow any port number for sender and receiver

include/baresip.h, modules/netroam/netroam.c, src/net.c, src/uag.c
net,uag: remove differential uag transport changes (#1611)
- removes the `uag_transp_rm()` and re-registration/re-invite from `net_rm_address()`
- adds function `net_add_address_ifname()`
- `net_add_address()`, `net_rm_address()` will not call `uag_transp_add()`, `uag_transp_rm()`
Instead `uag_reset_transp()` has to be called by the application/netroam module after one or several calls to `net_rm_address()`, `net_add_address()` or `net_add_address_ifname()`.
Previously we wanted to send only re-register for UAs for which we know that the local IP address changed. But what we didn't think about, that also the default route may change if an interface is added. Thus it is best to send re-register/re-invite for all UAs when the network changes.
=> remove uag transp rm (#1611)

modules/netroam/netroam.c, src/net.c
Only query local DNS settings if necessary.
In Android function `dns_srv_get()` does not work according to @juha-h. If DNS was configured with `dns_server`, then this function needs not be called.
Another check for `config_net->nsc` in module `netroam` is not really need. Should we add it anyway?
```c
static void poll_changes(void *arg)
{
...
if (!cfg->nsc)
net_dns_refresh(baresip_network());
...
```
=> net dns srv get

src/core.h, src/stream.c
propsals for naming the sender/receiver structs:
1. struct sender
2. struct rtp_sender
3. struct rtpsender
same with "receiver".
Please chime in with your preference...
=> stream: split up sender/receiver

modules/serreg/serreg.c
This fixes a lot of fast switches between primary/secondary SIP server (REGISTER and de-REGISTER) if `fbregint` was set for the accounts (Cisco Mode).
We tested this and the issue of the reverted commit.
We made
- manual tests against baresip
- automated tests against baresip
- manual tests in two products
and used two Cisco Call Manager as SIP servers. But the issue also could arise on other SIP servers.
=> serreg fix fallback accounts

modules/alsa/alsa_play.c
Fixes https://github.com/baresip/baresip/issues/1668
I suspect that the parallel use of snd_pcm_drop and snd_pcm_drain leads to problems.
From alsa doc:
```
snd_pcm_drain()
...
For stopping the PCM stream immediately, use ::snd_pcm_drop() instead.
```
https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#ga49afc5b8527f30c33fafa476533c9f86
=> alsa: use snd_pcm_drop instead of snd_pcm_drain

include/baresip.h, src/audio.c, src/call.c, src/core.h, src/stream.c
based on: https://github.com/baresip/re/pull/185
Flushes not only the jbuf but also the packets that are waiting in the RTP socket for processing. This ensures a clean start of the audio playback.
This might be independent from https://github.com/baresip/re/discussions/184.
=> stream flush rtp socket

modules/menu/dynamic_menu.c, modules/menu/menu.c, src/call.c, src/ua.c, test/call.c, test/main.c, test/test.h
Current behavior: In case the transfer-target refuses the call, all calls get closed.
[RFC5589 Section 6.3.1](https://datatracker.ietf.org/doc/html/rfc5589#section-6.3.1) shows a different behavior.
If the transfer-target refuses the call, the original call between transferor and transferee should be reestablished. This means the original call should be unhold.
@juha-h opened a question in the mailing list ["call transfer question"](https://groups.google.com/g/baresip/c/NUHJeMqAyTw/m/O6wxqRVuAQAJ) earlier this year. This PR changes the behavior such that a failed transfer will resume the original call.
=> Transfer like rfc5589

modules/gtk/call_window.c
This should fix #1675 since it derefs the call when the call is ended instead of when the window is closed.
=> GTK: mem_derefer call earlier

modules/multicast/multicast.c, modules/multicast/multicast.h, modules/multicast/receiver.c
* Range priority enable/disable: A command to disable and enable a specific range (priority range) of multicast receivers
* Ignore stream: A command to ignore a current receiving stream on a specified priority
=> Multicast new functions

modules/avcodec/avcodec.c
On initial submisson of "video passthrough", see https://github.com/baresip/baresip/pull/1418 `packetizeh()` call-back was added to only 1 codec: `h265_1`, while `avcodec_packetize()` itself supports much more (not to mention both h264 flavors): h263, h264 & h265.
That makes the current implementation to fail on a default configuration like that:
```shell
video: Skipping Packet as Copy Handler not initialized ..
video: Skipping Packet as Copy Handler not initialized ..
video: Skipping Packet as Copy Handler not initialized ..
```
Fix that by properly initializing all call-backs, though I haven't tested h263 & h265 since I don't have such sources handy.
=> avcodec: Enable pass-through for more codecs

modules/menu/menu.c
State array enumeration is not equal to the call_state enum definition.
Use loop counter to access the state of the array.
=> menu: filter for the correct call state in menu_selcall

test/account.c
test/account.c:182:14: warning: 'mb[0]' may be used uninitialized in this function [-Wmaybe-uninitialized]
=> test: fix warning on mingw32

docs/examples/accounts, src/account.c, src/core.h, src/reg.c
related to: https://github.com/baresip/re/pull/198
Adds a new account related parameter for the SIP TCP source port.
Some Session Border Controller (SBC) or other SIP components require the
ability to set a static source port at a UAC for SIP TCP connections. If the
new setting `sip_tcpsrcport` is not used, the source port still is
randomly chosen from the ephemeral ports range.
UDP source port can already be set by `sip_listen` setting.
SIP devices that have such a configuration setting: Konftel 800, Mitel 6800/6900
=> sip: add optional TCP source port

src/stream.c
Ref: https://github.com/baresip/baresip/issues/1676
the reason for this is that the first ~50 video packets are dropped during call setup,
causing the decoder to request a new keyframe and the video start to be delayed.
@cspiel1 could you please have a look why it was added ?
=> stream: only call rtp_clear for audio

modules/gtk/call_window.c
It should remove the segmentation fault but I am still not sure why it gets called with a closed call.
I could not reproduce the error before or after the change.
Returning `false` will also close the interval function.
=> checks if call is available before calling call, closes #1708

modules/gtk/call_window.c
There were cases where the call_window_progress function was called
twice before the call was established.
- call: SIP Progress: 183 Session Progress (application/sdp)
- call: SIP Progress: 181 Call Is Being Forwarded (application/sdp)
This caused multiple registrations of the call_timer function. But
only the last one was later removed in call_window_destructor.
When this happens the call_timer function is called with an already
freed call_window parameter. It then crashed when accessing the
poisoned pointer value call in the structure:
Thread 2 "baresip" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff50da700 (LWP 27424)]
0x0000555555571fc0 in call_duration (call=0xb5b5b5b5b5b5b5b5) at src/call.c:2260
2260        if (!call || !call->time_start)
Adding a new …
=> gtk: Avoid duplicate call_timer registration

modules/menu/menu.c, modules/menu/menu.h
When a UA event occurs menu needs to search for other active calls to decide
which tone should be played.
E.g. on UA_EVENT_CALL_CLOSED menu is looking for another active call while the
closed call may still be in CALL_STATE_ESTABLISHED. In this case the closed
call should be excluded from the search.
This fixes resume of ringback tone for multiple parallel outgoing calls, when
the first peer declines the call.
=> menu: exclude given call when searching for active call

docs/examples/config, mk/modules.mk, modules/auresamp/auresamp.c, modules/auresamp/module.mk, src/audio.c, src/config.c
Moves resample code from audio.c to a new module `auresamp`.
Proposed by @alfredh here: https://github.com/baresip/baresip/pull/1443
More discussions in this issue: https://github.com/baresip/baresip/issues/1699
TODOs:
- Not sure if the `struct auresamp_st` should have an "optional" inheritance by means of union.
=> module auresamp

modules/auresamp/auresamp.c
Fixes build for older compilers.
=> auresamp: replace anonymous union for pre C11 compilers

modules/auresamp/auresamp.c, src/audio.c
- Doxygen in module auresamp. The correct order of `[ ausrc ] --> [ aubuf ] --> filters --> RTP`
- Correct size of resample output buffer.
- In audio.c use the srate returned by the ausrc allocation function for `tx->psize`.
=> auresamp fixes

modules/multicast/receiver.c, modules/multicast/source.c
* Fix identical condition: Issue #1750 fix.
* Fix missing argument in warning with format string
=> Multicast identical condition and fmt string fix

src/audio.c
WARNING: ThreadSanitizer: data race (pid=59549)
Read of size 8 at 0x7b3800003ed8 by thread T2 (mutexes: read M1643):
#0 aubuf_cur_size /rem/src/aubuf/aubuf.c:392:11 (baresip+0x205044)
#1 ausrc_read_handler /baresip/src/audio.c:886:6 (baresip+0x11d6ac)
#2 read_thread /baresip/modules/alsa/alsa_src.c:88:3 (baresip+0x16a193)
Previous write of size 8 at 0x7b3800003ed8 by main thread (mutexes: write M1554):
#0 memset <null> (baresip+0xcc85d)
#1 mem_zalloc /re/src/mem/mem.c:178:2 (baresip+0x1f4273)
#2 aubuf_alloc /rem/src/aubuf/aubuf.c:78:7 (baresip+0x20453a)
#3 start_source /baresip/src/audio.c:1756:10 (baresip+0x11bb77)
#4 audio_start /baresip/src/audio.c:1823:9 (baresip+0x11b148)
#5 audio_encoder_set /baresip/src/audio.c:1982:10 (baresip+0x11c44b)
#6 start_audio /baresip/src/call.c:146:10 …
=> audio: allocate aubuf before ausrc_alloc (fixes data race)

src/call.c
* Add supported header into 200 Answering/OK sip package: Fix for #1746
* Traced with wireshark. Now Supported header is included in 200 package.
=> call: send supported header for 200 answering/ok

src/event.c
Adds remotevideodir and fixes remoteaudiodir. If the media line is not present
we want to report "inactive" instead of "sendrecv" in the UA event.
=> event: check if media line is present for encoding audio/video dir

docs/examples/config, src/audio.c, src/config.c
- audio: use module auconv for optional tx format conversion
- audio: use module auconv for optional rx format conversion
- config: add auconv as default module
TODO:
The print pipeline shows that the filters are processed in different order.
```
audio tx pipeline:       pulse ---> auconv ---> auresamp ---> opus
audio rx pipeline:       pulse <--- auconv <--- auresamp <--- opus
```
We want auconv to be processed always first. Otherwise auresamp has to do extra conversion internally if rx decoder works with float. Should we change the filter processing order to be head to top for tx and rx?
=> audio use module auconv

modules/menu/menu.c, modules/menu/menu.h
- menu: fix current call selection on `CALL_STATE_CLOSED` (#1733)
- menu: add call pointer match to `filter_arg` (#1733)
- menu: replace current call-id by pointer (#1733)
In some setups it is possible to receive multiple incoming calls with equal
call-id. This PR solves tracking of the current call if there are multiple
calls with identical call-id.
=> menu select other call on hangup

src/event.c
Adds e.g. "audiodir":"inactive", "videodir":"recvonly" to "CALL_REMOTE_SDP"
for early video.
An application may be interested in the final audio/video direction. E.g. automatic testing environments are able to check if there is audio/video with desired direction.
=> event: encode also combined media direction

src/audio.c
tmr_jiffies should only be used to compare/measure time in ms. But pthread_cond_timedwait relies on a REALTIME value.
fixes #1768
=> audio: fix rx_thread (adaptive jitter buffer)

test/account.c
rewrite the test so that each array entry is a pair of input string and expected output string.
reduces complexity, not sure if the explicit compare function was needed ?
@cspiel1 please review
=> test: refactoring of test_account_uri_complete

mk/modules.mk
Fixes build error on systems that don't have libxext-dev.
```
modules/x11/x11.c:12:10: fatal error: X11/extensions/XShm.h: No such file or directory
12 | #include <X11/extensions/XShm.h>
|          ^~~~~~~~~~~~~~~~~~~~~~~
```
=> mk: check also if extensions/XShm.h is present

modules/menu/menu.c
A fix for `menu_play()` audio file overrides.
=> menu: avoid multiple hash entries with same key

modules/menu/menu.c
E.g. suppresses the ringtone.
```
ring_aufile		none
```
E.g. can be used in combination with
```c
module_event("intercom", "override-aufile", ua, call, "ring_aufile:icring_aufile");
```
```
icring_aufile		none
```
in order to suppress the ringtone.
=> menu: support audio file config value "none"

include/baresip.h, src/call.c
Added API function `call_diverteruri` taken from History-Info or Diversion header.  Needed in order to be able to show to user who (if any) has diverted the incoming call.  Even though Diversion header has officially been replaced by History-Info, Diversion is still widely used.  Both have worked fine in my tests.
=> Added API function call_diverteruri

src/audio.c
Build-time failure without this patch:
```
src/audio.c: In function 'rx_thread':
src/audio.c:746:3: warning: implicit declaration of function 'clock_gettime'; did you mean 'calc_ptime'? [-Wimplicit-function-declaration]
clock_gettime(CLOCK_REALTIME, &ts);
^~~~~~~~~~~~~
calc_ptime
src/audio.c:746:3: warning: nested extern declaration of 'clock_gettime' [-Wnested-externs]
src/audio.c:746:17: error: 'CLOCK_REALTIME' undeclared (first use in this function)
clock_gettime(CLOCK_REALTIME, &ts);
^~~~~~~~~~~~~~
```
=> Avoid undeclared 'CLOCK_REALTIME' on RHEL/CentOS 7 (fixes #1781)

docs/examples/config, include/baresip.h, modules/multicast/player.c, modules/multicast/receiver.c, src/audio.c, src/conf.c, src/config.c, src/core.h, src/stream.c
Relates to https://github.com/baresip/rem/pull/33
Discussion: https://github.com/baresip/re/discussions/184
- audio: adapt to adaptive aubuf, adaptive jbuf becomes obsolete
- audio: do not drop reordered packets
- config,stream: support for new jbuf type "minimize"
- stream: also for JBUF_ADAPTIVE decode immediately 
This makes JBUF_ADAPTIVE completely obsolete what is the final goal
of the current PR. This is necessary because otherwise no decoding
would be done if `jitter_buffer_type   adaptive` is configured.
An alternative would be to keep all the JBUF_ADAPTIVE functions in
stream.c and audio.c for a deprecation period.
@sreimers, @alfredh, @juha-h 
I suppose that nobody uses JBUF_ADAPTIVE except my company, thus I would prefer to directly drop all the obsolete code in baresip and …
=> aubuf adaptive jitter buffer

test/call.c
the current code was causing occational errors:
```
[ RUN      ] test_call_webrtc
[31mselftest: ASSERT_TRUE: test/call.c:362:
[;m[31merror in event-handler (Invalid argument)
[;m[31mTEST_ERR: test/call.c:1561: (Invalid argument)
[;m[31mtest_call_webrtc: test failed (Invalid argument)
[;m[31mtest failed (Invalid argument)
[;mre main loop:
maxfds:  2048
nfds:    25
method:  2 (select)
```
=> test: check the correct stream in UA_EVENT_CALL_MENC

modules/multicast/receiver.c
+ if multicast_call_prio is configured the following hold: fixes a mix of ringtone and a high prio multicast
+ for non established calls, the overruling multicast will reject
every call which is not in established state
+ already established call are set on-hold
=> mc: reject incoming call if high prio multicast is received

modules/multicast/multicast.c, modules/multicast/multicast.h, modules/multicast/player.c, modules/multicast/receiver.c
+ add small statemachine to the multicast player to allow
fadein and fadeout at stream start and stream switching
+ configurable fade time via multicast_fade_time config parameter
+ default time is 125ms, disable the fade by setting the config to 0
=> mc: mcplayer stream fade-out and fade-in

src/audio.c
- audio: set timestamps in [us] in audio frame.
- Fixes disordered audio frames if only partial frames are read be the audio player. We are currently evaluating a new pulseaudio module that uses the native (asynchronous) pulseaudio API. The native API orders chunks of samples of different size.
- audio: code cleanup - use pointer for ac
=> ajb,aubuf: timestamp is given in [us]

src/call.c
Good day, 
I have seen SIP INFO messages containing an extra space character before the actual signal and duration in combination with a Mitel SIP server. 
As I'm not aware of any standard, it might be good to ignore leading spaces.
[traces.zip](https://github.com/baresip/baresip/files/8510719/traces.zip)
I attached 2 traces for reference - one of a failing SIP INFO from a working project ("mitel.pcap") and one from my test system with the code change already included ("test.pcap"). In the trace "test.pcap" you can see two SIP INFO messages, one with and one without leading space. Both result in the same message "call: received SIP INFO DTMF: '#' (duration=100)" printed on command line now:
> 1234@test.com: account match for 1234
> ua: using origin address 192.168.0.41 of SDP offer
> …
=> call: allow optional leading space in SIP INFO for dtmf-relay

debian/changelog
I noticed that debian changelog version was still 1.0.0, but that latest tag was 2.0.2.  So I went and updated debian changelog accordingly.
In the future, should this be done each time a new tag is created?
How come macos tests take MUCH longer time than all other tests altogether?
Looks like macos check was not able to download something.
=> Updated debian version

modules/menu/menu.c
Some fixes for ringback tone during multiple parallel outgoing calls.
- menu: resume ringback also if call is in CALL_STATE_EARLY
- menu: instead of restart ringback proceed playing for parallel call
=> menu ringback for parallel call

modules/multicast/player.c, src/audio.c
- audio: use RTP clock rate for timestamp calculation
- multicast: use RTP clock rate for timestamp calculation
Realized that for G.722 timestamps had been 10,20,30, ... instead of 20,40,60.
Further: If stereo or mono makes no difference for the RTP timestamps.
=> use RTP clock rate for timestamp calculation

modules/evdev/print.c
found and fixed by debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=961434
=> evdev: fix wrong ioctl size

src/conf.c
Fixes:
```c
src/conf.c:117:23: warning: Access to field 'buf' results in a dereference of an undefined pointer value (loaded from variable 'mb') [core.NullDereference]
pl.p = (const char *)mb->buf;
```
=> conf: missing pointer initialization found by clang analyzer

modules/avfilter/avfilter.c
I noticed that destroy is missing from the wrapper api ?
it is probably a good idea to migrate lock usage from "struct lock" to C11 mutex.
after that we can delete the "lock" module
=> avfilter: migrate to C11 mutex

test/ua.c
The dns test checks for rotating entries and so these cannot be cached.
depends on: https://github.com/baresip/re/pull/369
=> dns: add query cache

modules/aufile/aufile_play.c
Fixes:
```bash
$ ./selftest test_call_mediaenc
WARNING: ThreadSanitizer: data race (pid=200111)
Write of size 1 at 0x7b3c00000748 by main thread:
#0 destructor /baresip/modules/aufile/aufile_play.c:35:11 (selftest+0x1d0083)
#1 mem_deref /re/src/mem/mem.c:314:3 (selftest+0x2c3141)
#2 stop_rx /baresip/src/audio.c:293:15 (selftest+0x15629a)
#3 audio_stop /baresip/src/audio.c:1661:2 (selftest+0x15607d)
#4 call_stream_stop /baresip/src/call.c:224:2 (selftest+0x162dba)
#5 call_destructor /baresip/src/call.c:400:2 (selftest+0x15fceb)
#6 mem_deref /re/src/mem/mem.c:314:3 (selftest+0x2c3141)
#7 list_flush /re/src/list/list.c:51:3 (selftest+0x2b1849)
#8 ua_destructor /baresip/src/ua.c:57:2 (selftest+0x18aa40)
#9 mem_deref /re/src/mem/mem.c:314:3 (selftest+0x2c3141)
#10 test_call_mediaenc …
```
=> aufile/play: fix run data race

modules/av1/av1.c, modules/av1/av1.h, modules/av1/encode.c
this enables support for avformat pass through of AV1
1. avformat module can enable pass_through mode
2. the mediafile read can contain AV1 bitstream
3. the bitstream will not be decoded by avformat, but passed raw to av1.so codec module
4. the av1 packetize handler will convert the bitstream to RTP packets
=> av1: add packetize handler

modules/vp8/encode.c, modules/vp8/vp8.c, modules/vp8/vp8.h
This enables streaming of mediafiles with VP8 codec, without any re-encoding using avformat.so "pass through" mode.
=> vp8: add packetize handler

src/audio.c
This is only for discussion so far.
```
If an AEC is in the filter list aufilt, then the aubuf should be
constant and small. A second audio buffer aubufdec should be added via
config if network jitter is expected.
.--------.   .-------.   .--------.   .----------.   .--------.
|\    |        |   |       |   |        |   |  opt.    |   |        |
| |<--| auplay |<--| aubuf |<--| aufilt |<--| aubufdec |<--| decode |<--- RTP
|/    |        |   |       |   |        |   |          |   |        |
'--------'   '-------'   '--------'   '----------'   '--------'
```
The aubufdec makes mostly sense, if it runs in adaptive mode to handle changing network jitter best. If running in adaptive mode, an extra thread might not be required.
=> audio: add optional decoding buffer

modules/audiounit/recorder.c, modules/coreaudio/coreaudio.c
```
modules/audiounit/recorder.c:202:3: warning: 'kAudioObjectPropertyElementMaster' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
kAudioObjectPropertyElementMaster };
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
kAudioObjectPropertyElementMain
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreAudio.framework/Headers/AudioHa
rdwareBase.h:208:5: note: 'kAudioObjectPropertyElementMaster' has been explicitly marked deprecated here
kAudioObjectPropertyElementMaster API_DEPRECATED_WITH_REPLACEMENT("kAudioObjectPropertyElementMain", macos(10.0, 12.0), ios(2.0, 15.0), watchos(1.0, 8.0
), tvos(9.0, 15.0)) = kAudioObjectPropertyElementMain
^                                
OC [m] …
```
=> audiounit,coreaudio: fix kAudioObjectPropertyElementMaster deprecation

src/audio.c
Involved threads are:
- global re main thread
- rx_filter_thread (only used if config contains: `decode_buffer_mode`)
commits
- audio: rename lock to mtx
- audio: make rx.filtl thread-safe
=> audio: make rx.filtl thread-safe

src/audio.c
Fixes a crash because of wrong buffer size if
```
ausrc_srate 16000
auplay_srate 16000
decode_buffer_mode adaptive
module auresamp.so
module g711.so
```
=> audio: allocate correct buffer size for static auplay srate

src/reg.c
This PR changes behavior of `reg_unregister` API function so that it does not anymore destroy register client, but just un-registers it.  `reg_unregister` is currently used only by `ua_unregister` API function, which in turn us used by `menu` module `uareg` command and by `serreg` module.
If these usages require that in addition to un-registering, register client is also destroyed, I can instead of changing the behavior of `reg_unregister` function, create a new API function `reg_unregister_only`.  Based on my tests, menu module `uareg` command works fine with the modified `reg_unregister` function of this PR.  Also, quit command works the same way as before.
=> Do not destroy register client when it is unregistered

modules/mwi/mwi.c
When UNREGISTERING event is received, un-SUBSCRIBE possible MWI subscription, because at least when outbound is used, SIP proxy cannot anymore route NOTIFY requests to baresip based on gruu.
=> Un-subscribe mwi at un-register

src/call.c
While handling a session progress, the media streams were always stopped and restarted. Now the streams are updated according to the media information received in the session progress message.
=> call: update media on session progress.

include/baresip.h, modules/menu/dynamic_menu.c, modules/menu/menu.c, modules/menu/static_menu.c, src/call.c, src/ua.c
Due to RFC-3261 the SDP in the 183 Session Progress has to be equal to the SDP
in the 200 Ok. The correct solution is to answer the call with same SDP and
send immediately a re-INVITE if needed. E.g. in case of early video send
re-INVITE in order to activate the audio stream.
RFC-3261 13.2.1 Creating the Initial INVITE, Page 80
```
The UAC MUST treat the first session description it receives as the answer, and MUST ignore any
session descriptions in subsequent responses to the initial INVITE.
```
=> call, menu: make selective early media RFC-3261 conform

include/baresip.h, src/config.c, src/net.c
IPv4/IPv6 link local addresses is by default enabled.
In my application I wish to disable link-local, so adding a flag in `struct config_net`
=> config: add flag to enable/disable linklocal

src/audio.c
When the codec is changed, filters have to updated because parameters like
sample rate may change. E.g. auresamp needs the new configuration.
=> audio: update filters if codec changes

CMakeLists.txt
This fixes build issue when OpenSSL is not installed on target system:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OPENSSL_CRYPTO_LIBRARY (ADVANCED)
linked by target "baresip_exe" in directory /home/dima/git/baresip
linked by target "baresip" in directory /home/dima/git/baresip
OPENSSL_SSL_LIBRARY (ADVANCED)
linked by target "baresip_exe" in directory /home/dima/git/baresip
linked by target "baresip" in directory /home/dima/git/baresip
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
=> Fix CMake fails when OpenSSL is not present

src/audio.c
`mtx_lock(NULL)` crashes on linux
```
stream: rtp_listen failed: af=AF_INET ports=1024-49152 (Address already in use)
stream: failed to create socket for media 'audio' (Address already in use)
Thread 1 "baresip" received signal SIGSEGV, Segmentation fault.
___pthread_mutex_lock (mutex=0x0) at pthread_mutex_lock.c:76
76	pthread_mutex_lock.c: No such file or directory.
(gdb) bt
#0  ___pthread_mutex_lock (mutex=0x0) at pthread_mutex_lock.c:76
#1  0x00007ffff7d4c60d in __mtx_lock (mutex=<optimized out>) at ../sysdeps/pthread/mtx_lock.c:25
#2  0x0000555555567b6b in stop_rx (rx=0x5555556675e0) at src/audio.c:309
#3  0x0000555555567c0c in audio_destructor (arg=0x555555667508) at src/audio.c:322
#4  0x00007ffff7f8099e in mem_deref (data=0x555555667508) at src/mem/mem.c:335
#5  0x0000555555569f14 …
```
=> audio: fix SEGV if stream_alloc() fails

README.md, include/baresip.h, modules/menu/dynamic_menu.c, modules/menu/menu.c, modules/menu/static_menu.c, src/call.c, src/ua.c
This PR adds support for [RFC 3311](https://datatracker.ietf.org/doc/html/rfc3311) - the SIP UPDATE method.
Specifically, in concert with [RFC 3262](https://datatracker.ietf.org/doc/html/rfc3262) this allows session modifications in the early media state if the early media session is established through reliable 1xx responses. As outlined in [RFC 6337](https://datatracker.ietf.org/doc/html/rfc6337) ([section 3.2](https://datatracker.ietf.org/doc/html/rfc6337#section-3.2)), this is the only way to do session modification while in the early media state.
Related:
- https://github.com/baresip/re/pull/425
=> sip: add RFC 3311 support

src/audio.c
The aubuf for decoding and the rx_filter_thread was introduced in order to
combine the benefits of an adaptive audio buffer with an AEC as audio filter.
If a sound daemon like pulseaudio is used, the AEC should be integrated into
this daemon. But if baresip directly connects to ALSA the aubuf between the
filters and the audio player has to be fixed and as short as possible.
We think that the rx_filter_thread with the decoding aubuf has not enough
benefits for the lots of extra code that was necessary. Instead one could use
a modified ALSA module which integrates an AEC solution, like we did. Then the
AEC runs in the auplay thread.
So this commit is a cleanup for unused code parts.
---
We don't think that anybody uses the `rx_filter_thread`. But this should only be for discussion for now. …
=> audio: remove unused aubuf for decoding

src/audio.c
This fixes a major bug with setting:
```
audio_txmode		thread
```
If microphone frames are smaller than `tx->psize`, the aubuf never returned frames.
=> audio: always start reading in TX thread

src/audio.c
This fixes TX poll mode.
With the new `started` flag in aubuf, commit https://github.com/baresip/rem/commit/0a91a77201ecb9af10ed2761eb70e901ab0d198d and the `if` in audio.c the `psize` had to be reached exactly once.
=> audio: always start reading in TX poll mode

modules/multicast/source.c
Similar to: https://github.com/baresip/baresip/pull/1980
=> multicast: always start reading of TX aubuf

src/call.c
This should be the working replacement for PR https://github.com/baresip/baresip/pull/1922 which caused these issues (which are almost the same):
- https://github.com/baresip/baresip/issues/1957
- https://github.com/baresip/baresip/issues/1963
If a UAS sends multiple 183 Session Progress with unchanged SDP, then the streams where stopped and restarted always. This PR fixes this behavior.
The problem with the PR https://github.com/baresip/baresip/pull/1922 was that `call_stream_start()` was missing, or more concretely `stream_enable()` which is needed for processing the RX stream. E.g. for the "free-line signal", which is early-audio from callee (or UAS) to the caller.
@robert-scheck, @juha-h  : please could you test this version?
=> call: do not stop streams on session progress

modules/aufile/aufile_src.c, modules/multicast/source.c, src/audio.c
This https://github.com/baresip/rem/pull/74 is a replacement for the commits reverted here.
This PR fixes also the TX poll mode if e.g. pulse_async is used, which provides audio frames smaller than `ptime`.
- Revert "audio: always start reading in TX poll mode (#1980)"
- Revert "audio: always start reading in TX thread (#1979)"
- Revert "multicast: always start reading of TX aubuf (#1981)"
With https://github.com/baresip/rem/pull/74 also zero is allowed for the min size of aubuf. This disables the low latency control in aubuf which is needed for module aufile in order to read the whole WAV file into an aubuf before the reading is started.
- aufile: disable aubuf wish sz
=> audio: revert some TX commits and fix TX poll mode

src/call.c
We had some strange selftest CI errors sometimes, looks like these are related to this heap-buffer-overflow:
SUMMARY: AddressSanitizer: heap-buffer-overflow src/call.c:2024:25 in prack_handler
Found by:
`make CC=clang EXTRA_CFLAGS="-fsanitize=address" EXTRA_LFLAGS="-fsanitize=address"`
Related: https://github.com/baresip/baresip/pull/1973#issuecomment-1190151908
CC: @cspiel1 @maximilianfridrich
=> call: fix heap-buffer-overflow in prack_handler

modules/aufile/aufile_play.c, modules/aufile/aufile_src.c, modules/ctrl_dbus/ctrl_dbus.c, src/audio.c
Since we can not rely on C11 `_Atomic` (`RE_ATOMIC`) keyword only (no C99 and MSVC support). We have to be explicit about atomic usage. This is also needed for C11 too, since _Atomic has implicit sequentially-consistent memory ordering by default. On weak memory ordering architectures like ARM these needs extra memory barriers and can lead to performance drops if relaxed ordering is enough.
We have to be careful about `re_atomic_weak` (relaxed memory) usage, but for `boolean run` this should be fine and is lock and data-race free. Also with explicit definitions its much fewer code than mutex locking.
=> Improve re_atomic handling

src/event.c
Fixes a bug introduced by https://github.com/baresip/baresip/pull/1951
=> event: fix wrong place of the err check

src/call.c
Since #1996 looks like a serious issue and prack_handler is broken (maybe selftest only), disabling it temporarily should be fine for now I think.
=> call: disable prack_handler temporarily

src/call.c
Re-enable prack handler after the source of issue #1996 has been fixed in https://github.com/baresip/re/pull/457.
=> Fix prack handling

cmake/modules.cmake
With -DEXTRA_MODULES="mod1;mod2" additional modules can be added
=> cmake: add EXTRA_MODULES option

modules/menu/menu.c
If `carg->data` is set, `carg->prm` has to be returned, otherwise `uri` is empty in `dial_handler`. Fixes #2043
=> menu: fix menu_ua_carg data preference

include/baresip.h, modules/menu/dynamic_menu.c, modules/menu/static_menu.c, src/call.c, src/ua.c
Fixes issue #2042
- The function call_set_media_direction() should remember the audio/video dir
for the established state
- Rename call_set_media_ansdir() to call_set_media_estdir(). This function sets
the audio/video dir for the established state, before the call is established
=> call: remember media dir for established state

modules/avformat/avformat.c
avformat has a shared state between audio and video.
the shared state can be a multimedia file that has both audio and video stream.
in this case the state can be shared.
the state is not supposed to be shared across sessions
=> avformat: check shared for both audio+video

README.md
Update README.md to mention actual GTK+ 3 usage (instead of 2)
=> Mention actual GTK+ 3 usage (instead of 2) in README.md

modules/ctrl_tcp/tcp_netstring.c
It prevents a buffer overflow in case of a message which is exactly the size of the buffer. The end symbol would be out of bound.
=> ctrl_tcp: change unsafe operations on an mbuf to the safe mbuf interface

modules/gzrtp/gzrtp.cpp, modules/gzrtp/session.h, modules/gzrtp/stream.cpp
The event should be processed by menu module instead of warning log from gzrtp module
=> gzrtp: Call event hander when SAS needs to be verified

modules/gzrtp/session.cpp, modules/gzrtp/stream.cpp, modules/gzrtp/stream.h
Before this every stream (audio, video) of a session generated its own event
=> Generate only one MENC_EVENT_PEER_VERIFIED event when all streams are verified

include/baresip.h, src/config.c, src/net.c
`dns_getaddrinfo yes`  is useful for debugging (`/etc/hosts`).
=> config,net: add use_getaddrinfo/dns_getaddrinfo option

CMakeLists.txt, modules/aac/CMakeLists.txt
`RE_DEFINITIONS` is found in `../re/cmake/re-config.cmake` or installed in `/lib/cmake/re/re-config.cmake`
https://cmake.org/cmake/help/latest/command/find_package.html?highlight=find_package#config-mode-search-procedure
=> cmake: add_compile_options and use re config

src/uag.c
The REFER handler of uag has to check if the to.tag is unset. This means that
the SIP request is outside of a dialog. Otherwise false should be returned and
the processing is passed to the SIP session request handler in re listen.c
which handles call transfers.
=> uag: out-of-dialog REFER handler checks to.tag

modules/menu/dynamic_menu.c, modules/menu/menu.c, src/call.c
Fix for https://github.com/baresip/baresip/issues/2074.
Relates to: https://github.com/baresip/re/pull/515
- call: do not call update_media in progress handler
- call: in update_media() always update video/audio
Tested:
- Test early media cases: switch on/off of video/audio during 1xx
TODO:
- Clarify if @alfredh webrtc use case still work: See commit fb99976031e63bb1a53d9213dd6b185cf43639a0
Edit:
--> Done: the commit  fb99976031e63bb1a53d9213dd6b185cf43639a0 still is present. Only extended by a stop video.
=> Update media fixes

docs/examples/accounts, src/account.c
100rel will not be put to the Supported header. And if the peer has 100rel in the Required header, baresip answers with a SIP 420 Bad Extension.
Will also update the Wiki.
=> account: set 100rel default to no

modules/menu/menu.c
If remote informs about audio direction changes during early media state,
the ringback might has to be turned on/off. If there is incoming early audio,
ringback is turned off otherwise turned on.
=> menu: during early media switch on/off ringback

include/baresip.h, src/audio.c, src/call.c, src/event.c
UA event handlers are processed in configuration order from h_1 to h_n. Any UA
event handler h_x  may set the calls event stop flag true. Following UA event
handlers are not processed. The next UA event is processed again by the UA
event handlers h_1 to h_x and not by h_{x+1} to h_n.
- call, event: add a UA event stop processing flag
- audio: add audio_txtelev_empty()
Note: If the flag is not set explicitely to `true` by the application, nothing will change for applications that rely on UA events.
Note2: A well known more clean solution would be to add a `return bool` to the UA event handler. But this would mean a break in the API and a lot of changes in different modules.
refers to:
- https://github.com/baresip/re/pull/537
- https://github.com/baresip/baresip-apps/pull/19
=> call, event, audio: send DTMF via hidden call

include/baresip.h, modules/serreg/serreg.c, src/core.h, src/reg.c, src/ua.c
The commit a2ab6ab27052f7b4cf06b0bb7b7338768fd691ef changed the behavior of
the serial mode. This adds a function `ua_stop_register()` that has the
previous behavior.
=> ua,reg,serreg: fix serial registration mode

CMakeLists.txt
Make it possible to define custom app modules:
`cmake -B build -DAPP_MODULES_DIR=../baresip-apps/modules -DAPP_MODULES="auloop;vidloop"`
Works also with static builds:
`cmake -B build -DSTATIC=ON -DAPP_MODULES_DIR=../baresip-apps/modules -DAPP_MODULES="auloop;vidloop"`
=> cmake: add APP_MODULES and APP_MODULES_DIR

src/call.c
Improved CALL_EVENT_CLOSED message when there is no common audio or video codecs (now same as in info message).
=> Improved call closed message

src/call.c, src/core.h, src/ua.c
Related to: https://github.com/baresip/baresip/pull/2140
What changes:
- incoming calls: allocate the streams in `call_accept()`
- outgoing calls: allocate them in `sipsess_desc_handler()`, when the SDP offer is generated. Nothing changes for non-IP address calls.
What relates to https://github.com/baresip/baresip/pull/2140:
For now the peer_uri should be available when the streams are allocated. In a
next PR it could be passed to the streams.
Maybe in another PR the streams could be allocated after the SDP negotiation.
Currently this is not possible due to the "common audio or video codecs" check
which depends on the audio/video streams.
=> call: allocate streams after peer_uri was set

src/config.c
win32 should be build static, so module counting is not needed.
=> config: ignore dirent.h on win32

src/ua.c
If `ua_connect` or `ua_connect_dir` are called and the request URI contains URI parameters, it could occur that some parameters are duplicated if the account luri contains the exact same parameter.
Now, only non-duplicate URI parameters are appended to the request URI in `ua_connect_dir`.
=> ua: do not duplicate request URI parameters

src/call.c
The `call->peer_uri` was not set for the dummy call allocated for incoming OPTIONS.
Leads to fail of `test_ua_options` in PR https://github.com/baresip/baresip/pull/2165
=> call: set peer URI early for incoming calls

CMakeLists.txt
The current implementation leads with `cmake` to `-DSHARE_PATH=\"\"` which leads to an empty string after `audio_path` in a freshly generated `.baresip/config` - which is wrong. According to the GNU Makefiles, it should be by default something like `/usr/share/baresip` (if not overriden).
Patch behaviour (backwards compliant) is to
- use override via `SHARE_PATH`, otherwise
- use distribution default via `SHARE_INSTALL_PREFIX`, otherwise
- use defaults from `cmake --install` during sound files installation
=> cmake: synchronize behaviour of -DSHARE_PATH="…" with GNU Makefiles

CHANGELOG.md, CMakeLists.txt, Makefile, debian/changelog, include/baresip.h
- Click `Draft a new release` on Release page
- Fill a new release tag version and title (like v2.4.0)
- Press `Auto-generate Release notes` 
- **Save as draft** (don't publish yet)
- Copy release notes to `CHANGELOG.md`
- `CMakefile`
- `Makefile`
- `include/baresip.h` (baresip only)
- `CMakefile` (Bump PROJECT_SOVERSION)
- `Makefile` (Bump ABI_MAJOR)
- <s>`CMakefile` </s>
- <s>`Makefile` </s>
- libre
- librem
- retest (needs only a version tag - no PR)
- baresip
- Maybe `Auto-generate Release notes` is needed to update (delete last notes first)
- re - https://github.com/baresip/re/compare/stable...main?expand=1
- rem - https://github.com/baresip/rem/compare/stable...main?expand=1
- retest - https://github.com/baresip/retest/compare/stable...main?expand=1
- baresip - …
=> release v2.8.1

modules/ctrl_dbus/CMakeLists.txt
Fixes CMAKE_CURRENT_SOURCE_DIR and target name needs different to output name.
=> cmake/ctrld_dbus: ninja and subdirectory fixes

CMakeLists.txt
=> cmake: link CMAKE_CURRENT_BINARY_DIR modules

modules/menu/menu.c, modules/menu/static_menu.c, src/call.c
This enables parsing the display name out of the dial URI and report it via
UA events to the application.
=> call, menu: support display name for outgoing calls

src/call.c, src/uag.c
If the transport is reset (e.g. an IP address change) and a call is in the early media state, session modifications might not be possible. In this case, the peer will never receive our transport update (e.g our new IP) and we will no longer be able to communicate with the peer. In such cases - when target refreshes are not possible - hangup the call.
=> call: hangup call on transp reset if necessary

modules/jack/jack_play.c
The variable `sampc_rs_out` may not be initialized here.
=> jack: fix CodeQL uninitialized local variable

modules/selfview/CMakeLists.txt, modules/snapshot/CMakeLists.txt
Avoid these kind of snapshot compiler warnings during cmake build on Debian 11:
```
/usr/src/orig/baresip/modules/snapshot/png_vf.c: In function ‘png_save_vidframe’:
/usr/src/orig/baresip/modules/snapshot/png_vf.c:23:13: warning: variable ‘png_row_pointers’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
23 |  png_byte **png_row_pointers = NULL;
|             ^~~~~~~~~~~~~~~~
/usr/src/orig/baresip/modules/snapshot/png_vf.c:29:8: warning: variable ‘fp’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
29 |  FILE *fp = NULL;
|        ^~
/usr/src/orig/baresip/modules/snapshot/png_vf.c:35:6: warning: variable ‘err’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
35 |  int err = 0;
|      ^~~
/usr/src/orig/baresip/modules/snapshot/png_vf.c:21:46: warning: argument ‘vf’ …
```
=> Avoid snapshot compiler warnings

src/config.c
Fixes a bug in config template generation. The added string must be part of the first string.
After fix:
```
#avcodec_h264enc        libx264
#avcodec_h264dec        h264
#avcodec_h265enc        libx265
#avcodec_h265dec        hevc
#avcodec_hwaccel        vaapi
#avcodec_profile_level_id 42002a
#avcodec_keyint         10
```
=> config: fix template for avcodec_xxx

modules/menu/static_menu.c
- ua: use mbuf functions for ua_connect_dir
- menu: fix display name for command dialdir
=> menu fix display name

CMakeLists.txt
=> cmake: use CMAKE_SHARED_MODULE_SUFFIX

modules/avformat/avformat.c, modules/avformat/video.c
When using VP8 decoder with VAAPI hwaccel, the function call hwtransfer_data crashes. The pixel format should be set by this function. In this case the pixel format is NV12.
```
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.10.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.10 (libva 2.10.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.1.1 ()
vainfo: Supported profile and entrypoints
VAProfileMPEG2Simple            :	VAEntrypointVLD
VAProfileMPEG2Main              :	VAEntrypointVLD
VAProfileH264Main               :	VAEntrypointVLD
VAProfileH264Main …
```
=> avformat: fix hwaccel vaapi

modules/menu/static_menu.c
Without these changes a dial command without a parameter causes baresip to segfault.
=> Stop segfaulting when no URI is passed to dial command

modules/auresamp/auresamp.c
In some situations `srate` or `ch` number might be zero. This PR avoids division by zero.
=> auresamp: avoid division by zero (#2293)

src/ua.c
WebRTC based clients use always `IP4 127.0.0.1` or `IP4 0.0.0.0` as origin `<addrtype> <unicast-address>` for privacy reasons.
https://www.rfc-editor.org/rfc/rfc4566.html#section-5.2
```
For privacy reasons, it is sometimes desirable to obfuscate the
username and IP address of the session originator.  If this is a
concern, an arbitrary <username> and private <unicast-address> MAY be
chosen to populate the "o=" field, provided that these are selected
in a manner that does not affect the global uniqueness of the field.
```
=> ua: use sdp connection data instead origin

modules/ice/ice.c
Storing next list entry within loop, prevents a segfault if last `call_gather_handler` destroys session on error.
=> ice/tmr_async_handler: fix possible segfault

webrtc/src/demo.c, webrtc/src/demo.h, webrtc/src/sess.c, webrtc/www/js/main.js
Tested with:
- Firefox 106.0.5 (64-bit)
- Chromium 107.0.5304.110
```diff
diff --git a/webrtc/src/demo.c b/webrtc/src/demo.c
index 7f48f909..1cd96261 100644
--- a/webrtc/src/demo.c
+++ b/webrtc/src/demo.c
@@ -27,7 +27,7 @@ static struct demo {
static struct rtc_configuration pc_config = {
-       .offerer = true
+       .offerer = false
};
diff --git a/webrtc/www/js/main.js b/webrtc/www/js/main.js
index c1f42b6f..b98abb91 100644
--- a/webrtc/www/js/main.js
+++ b/webrtc/www/js/main.js
@@ -19,7 +19,7 @@ disconnectButton.disabled = true;
let pc;           /* PeerConnection */
let localStream;  /* MediaStream */
let session_id;   /* String (Opaque, generated by Server) */
-let b_offerer = false;  /* false: Send Offer, true: Send Answer */
+let b_offerer = true;  /* false: Send Offer, true: …
```
=> webrtc: fix browser offer handling

webrtc/src/demo.c
The WebRTC demo currently does not handle OPTIONS http requests. This works fine as long as you only use the demo's given frontend on port 9000.
To see how well Flutter WebRTC works with our backend using BareSIP, I made a Flutter program that connects to the BareSIP WebRTC demo backend.
Since this is CORS, and some browsers send "preflight requests", an OPTIONS request before each of certain types of requests. I had to add this commit to enable PUT/PATCH requests.
Network traffic in firefox looks like this when communicating with the demo:
Tested on Firefox
Works on Chrome (Doesn't seem to do preflight requests)
This PR fixes that.
=> Add OPTIONS handling for webrtc demo

src/srcs.mk
=> mk: remove rtpext.c from srcs.mk

src/call.c, src/uag.c
Helps when someone wants to analyse unexpected call termination by the peer.
=> uag,call: do not override status code and reason

include/baresip.h, src/mediatrack.c
This is useful for `audio_set_devicename` etc.
=> mediatrack: add audio and video getters

src/play.c
A new aubuf mode AUBUF_FILE reduces the complexity of the code for the repeated
playback. In `aubuf_write_handler()` the frames have to be taken from `aubuf`
without any exception, otherwise this leads to cracks in the playback.
based on: https://github.com/baresip/rem/pull/117
=> aubuf: add AUBUF_FILE mode

src/play.c
Fixes an audio drop-out caused by faulty timestamps on first restart. When the
timestamps are reset to zero, then the aubuf has to be flushed.
=> play: flush aubuf before restart

modules/avcodec/encode.c
With `rc_buffer_size` and `rc_max_rate` the encoder can better calculate a constant average bitrate and this avoids large bitrate spikes.
See: https://trac.ffmpeg.org/wiki/Limiting%20the%20output%20bitrate
=> avcodec: constrain bitrate

src/video.c
Firefox needs for activating `Generic NACK` a extra rtcp-fb line (which looks RFC conform).
=> video: add rtcp-fb Generic NACK

src/call.c
If STUN/TURN/ICE was configured the media direction for the INVITE was not set
that was given by `ua_connect_dir()`. This lead to a fallback to send-receive
for audio and video.
Note: If `ua_connect()` is used, nothing changes. Then the media direction is send-receive, the default.
=> call: set media dir also for MNAT case

src/core.h, src/stream.c, src/video.c
Instead of requesting a new picture we should answer a Generic NACK with resending the rtp packet if available.
Tested with Chrome/Firefox (needs #2380) 108 and Safari iOS (1-2% packet loss simulation).
Depends on https://github.com/baresip/re/pull/626
=> RTP Resend

src/ua.c, src/uag.c
For incoming SIP requests a certificate is selected by SNI in the TLS client hello.
Multiple certificates can be configured by means of the account parameter `;cert=`.
relates to: https://github.com/baresip/re/pull/596
=> TLS server support SNI based certificate selection

tools/fritzbox2baresip
As pointed out by @alfredh in https://github.com/baresip/baresip/pull/2395#issuecomment-1368219513, there is a warning using a newer `pylint` that should be addressed:
```
tools/fritzbox2baresip:78:14: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
```
=> fritzbox2baresip: use open with explicitly specifying an encoding

CMakeLists.txt
There is a fix in cmake v3.13 for sub-folders. With v3.12.5 there are still
warnings like this for each module:
```
CMake Error at CMakeLists.txt:363 (install):
install TARGETS given target "account" which does not exist in this
directory.
```
=> cmake: increase minimum required version

src/call.c
The RFC-3261 tells that rejecting an incoming call should be done with
486 (Busy Here).
=> call: default status code for rejecting incoming calls

modules/dtls_srtp/dtls_srtp.c
This is needed for Safari interop
=> dtls_srtp: enable single DTLS connection mode

cmake/FindPULSE.cmake
The PulseAudio driver using the simple API has already been removed via commit 1aac3e3589977d5785a7ecd74bcad0d99e907c99, commit 5fb1e54e9d11082eba76d3b86d399e1539a0cc8c and commit d0a47f07214c61102c04c5de0d2b88a94b25b89c.
=> cmake/pulse: Remove pulse-simple library lookup

modules/pulse/pastream.c, modules/pulse/player.c, modules/pulse/pulse.c, modules/pulse/pulse.h, modules/pulse/recorder.c
Yesterday I replaced pulseaudio daemon with WirePlumber / Pipewire on my dev host. The plan was too use pipewire-pulse.service which makes pipewire compatible to pulseaudio clients like baresip with module pulse.
With command `/play ring.wav` didn't hear anything. Also no error messages.
The reason for this seems to be this faulty registration with the obsolete key `pulse_async`.
```c
err  = auplay_register(&auplay, baresip_auplayl(),
"pulse_async", pulse_async_player_alloc);
err |= ausrc_register(&ausrc, baresip_ausrcl(),
"pulse_async", pulse_async_recorder_alloc);
```
Replacing `pulse_async` by `pulse` solves the problem.
=> pulse: replace obsolete string pulse_async (makes baresip PipeWire compatible)

src/core.h, src/mediatrack.c, src/stream.c
WebRTC uses 5 seconds for audio and 1 second interval for video rtcp
ref:
https://chromium.googlesource.com/external/webrtc/+/refs/heads/main/modules/rtp_rtcp/source/rtcp_sender.cc#362
=> make rtcp interval configureable

include/baresip.h, modules/menu/dynamic_menu.c, src/call.c, src/uag.c
- Do not allow answer if awaiting PRACK to a 1xx response with SDP.
- Refactor call_refresh_allowed to use new re function `sipsess_refresh_allowed`.
Related re PR:
- https://github.com/baresip/re/pull/630
=> PRACK refactoring

include/baresip.h, modules/menu/menu.c, modules/menu/menu.h, src/call.c
This PR introduces a logic for handling ringback tones and early media for multiple outgoing calls (parallel call feature).
- call,menu: no early audio if multiple outgoing calls
- menu: delayed play for ringback and ring tone
Follow up PR:
- These changes: https://github.com/baresip/baresip/pull/2368 . Check if SIP UPDATE is allowed directly in `call_modify()` and return err if not allowed.
=> menu: ringback/early audio handling for parallel calls

src/magic.h
Since we support C99 and later we can use the macro `__func__` directly.
=> magic: use C99 __func__ macro

modules/gtk/call_window.c
Get rid of the following clang compiler warnings:
```
modules/gtk/call_window.c:399:6: error: variable 'win' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
if (err) {
^~~
modules/gtk/call_window.c:553:9: note: uninitialized use occurs here
return win;
^~~
modules/gtk/call_window.c:399:2: note: remove the 'if' if its condition is always false
if (err) {
^~~~~~~~~~
modules/gtk/call_window.c:393:25: note: initialize the variable 'win' to silence this warning
struct call_window *win;
^
= NULL
```
Can not return `ENOMEM`, because of return type `struct call_window *`.
=> gtk: return NULL on mtx_init() != thrd_success

.github/workflows/build.yml
I would like to see the gtk module built as part of the CI (also to fix possible issues earlier than currently).
=> ci: add libgtk-3-dev to build GTK+ 3 module

.github/workflows/build.yml
The following build failed on macos-11:
https://github.com/baresip/baresip/actions/runs/4195739157/jobs/7288101408
Arised with:
https://github.com/baresip/baresip/pull/2454#issuecomment-1434166069
=> ci: install pkg-config on mac-os

src/video.c
next list entry has to be saved before `list_move`, otherwise list entry is null.
=> video: fix vidqueue_poll list_move

modules/dshow/dshow.cpp
1. Memory that is already freed is referenced if camera has no resolution equal to requested but best match is the last media offered by the device. Spotted when trying to use 640x480 resolution with OBS-Camera - unlike physical cameras I own this one list resolutions from highest to lowest and the last one, 640x360 is the best match.
2. If during format enumeration device would return something other than FORMAT_VideoInfo (but I'm not sure if/when it can actually happen) then media type memory is leaked.
3. This I believe is actually OBS-Camera issue, but checking buffer buffer size in BufferCB might prevent crash. I'm not sure if I've used the latest version of OBS / virtual camera, but it was reporting back incorrect video size (not the one set by the user) but then returning frames …
=> Dshow fixes

src/call.c
On an incoming call, if autoanwer is configured and we have sent a 183 containing SDP, we have to await the PRACK before we are allowed to send a 200 OK ([RFC 3262](https://www.rfc-editor.org/rfc/rfc3262) section 3 - last paragraph).
With autoanswer configured, it could happen that we try to call `call_answer` while we are still awaiting a PRACK. This commit fixes this.
=> call: Fix delayed (auto) answer if awaiting PRACK

src/ua.c, test/ccheck.py
`list_unlink()` and `list_move()` handling is a bit special, next list entry has be set before, otherwise the loop is stopped early.
See https://github.com/baresip/ccheck_tests/blob/main/src/check_list_unlink.c for examples.
=> ccheck: add check_list_unlink check

modules/sndfile/sndfile.c
In the next step, printing of the info message could be moved to menu module.
=> Send event when dump file is opened

src/video.c
This fixes a baresip crash that occurs when there follows one more frame after a re-INVITE switches off video RX.
=> video: add NULL pointer check for vidisp

src/ua.c
Calls to ua_event were vulnerable to format string attacks. This is now fixed.
See https://owasp.org/www-community/attacks/Format_string_attack
=> ua: Fix calls of ua_event()

.github/workflows/build.yml
Avoid hardcoded OpenSSL path on macOS
=> ci: avoid hardcoded OpenSSL path on macOS

docs/examples/config, modules/menu/menu.c, modules/menu/menu.h, src/config.c
Parallel call memory issue: #2502 - Part 2
- menu,config: limit the number of early audio streams
- menu: optimize count of outgoing calls
=> menu: limit early audio TX streams

CMakeLists.txt
Including /usr/... is unsafe for cross-compilation.
In yocto build fixes the warning:
```
cc1: warning: include location "/usr/local/include" is unsafe for cross-compilation [-Wpoison-system-directories]
```
=> cmake: avoid include of /usr/local/include

modules/ctrl_dbus/ctrl_dbus.c, modules/ice/ice.c, modules/snapshot/png_vf.c
I scanned the whole code base of BareSIP and re for format string and variable argument list issues. Using LLVM, I found 84 functions that use a variable argument list and I did my best to go through all of their invocations manually for potential problems (I have not found a way to use LLVM for this yet).
I have fixed three obvious errors, but there are more potential problem (and va_lists could lead to uncaught errors quite easily). Here are a few that look wrong:
- `rtmp_amf_command` there are quite a few mismatches between the number (and type) of variable arguments and the value of `body_propc` provided.
- `rtmp_amf_command` in rtmp/stream.c there is a `body_propc` mismatch
- `rtmp_amf_request` in rtmp/conn.c there is a `body_propc` mismatch
- `rtcp_quick_send` multiple count …
=> ctrl_dbus,ice,png_vf: Fix format string usage

src/play.c
The ausrc may call the errh (for eof) before the auplay got the complete data.
This commit avoids that data is lost. The flush is still needed in order to
reset internal fields for computing the timestamps.
=> play: flush of the aubuf directly before the replay starts

src/call.c
Key frames of video streams should not be lost.
=> call: only flush audio stream when stream starts

modules/menu/menu.c
The scode 603 did not set a tone in translate_errorcode(). Thus the error.wav
was used when the call was declined. Now busy.wav is played in this situation.
=> menu: use busy tone when call declined (scode 603)

.github/workflows/build.yml
Add latest available gcc compiler (currently gcc-12) to catch possibly new build failures early; clang aka clang-14 is already the newest in Ubuntu 22.04 (ubuntu-latest).
=> ci: add gcc-12 for Ubuntu 22.04 (ubuntu-latest)

README.md, webrtc/README.md
As librem was archived it doesn't make sense to me to still mention it here.
=> docs: remove librem from README files

modules/gtk/CMakeLists.txt
On OpenBSD most third-party libs are in `/usr/local/lib`. 3.0.0 built fine but 3.1.0 fails to build because there's no `-L/usr/local/lib` in the gtk module linking line.
my guess is that it's a regression from #2506.. but doing this fixes the build for me. Strangely, other modules depending on other 3rd-party libs don't fail to link.....
=> cmake/gtk3: make sure gtk3 libs are found

src/audio.c
The samplerate of the audio source has to be used for computing the tx->psize
because the aubuf contains the frames coming directly from the ausrc.
=> audio: count TX underruns correctly (#2535)

modules/ctrl_dbus/ctrl_dbus.c, modules/ice/ice.c, modules/snapshot/png_vf.c, src/sdp.c, src/ua.c
Fixes a few occasions of calls to variadic functions that could fail in certain instances.
I used an LLVM pass to check all of baresip and re where the last non-variadic argument passed to a variadic function is not a constant. Such function calls are potentially dangerous, so I checked those function calls manually for potential bugs/vulnerabilities. I have checked the 52 warnings generated by this pass, most of which were not an issue. Still, this is a snapshot in time and such problems could be introduced with any new code change.
=> variadic function fixes

src/ua.c, test/ua.c
The SIP URI we receive in the Refer-To header is already escaped, so before triggering `UA_EVENT_REFER`, we unescape it. Otherwise, we would double-escape this URI erroneously when sending the INVITE request to this URI.
=> ua: unescape incoming Refer-To header

modules/dtls_srtp/dtls_srtp.c
tls_set_verify_client has same functionality like tls_set_verify_client_trust_all. The old name was misleading for tls usages other than dtls and will be removed.
=> Client cert renegotiation in http

cmake/FindOPUS.cmake
"Cflags: -I${includedir}/opus" in opus.pc
=> cmake/findOpus: fix Could NOT find OPUS (missing: OPUS_INCLUDE_DIR)

CHANGELOG.md, CMakeLists.txt, debian/changelog, include/baresip.h, mk/Doxyfile
ABI increased because of
```patch
@@ -382,8 +382,14 @@ struct config_avt {
struct range rtp_ports; /**< RTP port range                 */
struct range rtp_bw;    /**< RTP Bandwidth range [bit/s]    */
bool rtcp_mux;          /**< RTP/RTCP multiplexing          */
-       enum jbuf_type jbtype;  /**< Jitter buffer type             */
-       struct range jbuf_del;  /**< Delay, number of frames        */
+       struct {
+               enum jbuf_type jbtype;  /**< Jitter buffer type     */
+               struct range jbuf_del;  /**< Delay, number of frames*/
+       } audio;
+       struct {
+               enum jbuf_type jbtype;  /**< Jitter buffer type     */
+               struct range jbuf_del;  /**< Delay, number of frames*/
+       } video;
```
=> release v3.2.0

include/baresip.h, modules/menu/static_menu.c, src/call.c
BareSIP currently showed the following erroneous behavior when acting as the callee:
- Incoming INVITE with video=recvonly
- We answer the call using `/acceptdir` with video=recvonly
- BareSIP sends 200 OK with video=sendonly (wrong! we don't want to send video)
- BareSIP receives ACK
- BareSIP send re-INVITE with video=recvonly (to which peer answers with video=inactive)
Now, this is fixed and the behavior is as follows:
- Incoming INVITE with video=recvonly
- We answer the call using `/acceptdir` with video=recvonly
- BareSIP sends 200 OK with video=inactive
- No re-INVITES
=> Fix oneway video sdp on answering call

src/stream.c
With higher video codec bitrates, packets are lost because udp recv buffer is to small.
=> stream: increase udp socket buffer for video

src/stream.c
With higher bitrates video decoding freezes sometimes since jitter buffer offloading is not fast enough.
=> stream: faster video jitter buffer offloading

src/call.c
I guess that:
- UA_EVENT_CALL_LOCAL_SDP should be emitted if the local UA sends an SDP offer/answer.
- UA_EVENT_CALL_REMOTE_SDP should be emitted if an SDP is received.
=> call: send LOCAL_SDP event if we send SDP

src/event.c
The local audio direction can be used by the application to reliable detect
local call on hold and call resumed.
=> event: add local SDP direction

src/stream.c
There is no need to handle `jbuf` differently for video and audio.
=> stream: also decode audio as long as jbuf returns EAGAIN

modules/aufile/aufile_play.c
mem_zalloc avoids valgrind warning
In `rx_thread_stream_receiver` there was a valgrind warning where aufile_play.c calls `rewind(af->f)`
```
Syscall param write(buf) points to uninitialised byte(s)
...
==1405311==    by 0x4903FF6: rewind (rewind.c:35)
```
=> aufile: init sampv buffer; NULL pointer check

webrtc/src/main.c
The Opus audio codec is used most of the time.
=> webrtc: remove G711 module

cmake/FindGST.cmake
Include `glibconfig.h` contains arch specific content and is thus placed in distribution specific arched locations, covers Fedora/RHEL and derivatives.
=> cmake: add /usr/lib{64,}/glib-2.0 to FindGST.cmake

include/baresip.h, src/core.h, src/stream.c, src/video.c
- If the video stream direction changes from receive only to send-receive,
send-only or inactive, we should stop sending dummy packets.
- Function `stream_open_natpinhole()` is not needed in the API and it doesn't
need to return an error because it can't fail.
=> video,stream: stop natpinhole timer on re-invite

src/call.c
This flag is true if any SDP answer was already sent to the peer. It is used
in static_menu.c to decide if the `ldir` has to be set or not. After sending
the first SDP answer `ldir` should stay unchanged at the value that was used
during encoding the SDP answer. It is important for call_need_modify() to
decide if a re-INVITE is needed or not. That's why sent_answer should not be
reset to false. This could lead to a missing re-INVITE.
=> call: never set sent_answer to false

test/call.c
Rules can be added to a test fixture when to cancel the re main loop. This should simplify the UA event handler and keep the business logic of the test-case in the test function.
This PR adds a first cancel rule for the CALL_PROGRESS event.  More rules that will simplify the event handler will follow.
- test: call - rules for re_cancel
- test: call - use rule to cancel on UA_EVENT_CALL_PROGRESS
- test: call - print info if rule does not match
Note: We plan to simplify `test_call_change_videodir()`. Then add more early media tests, 100rel tests, audio codec switches, SIP UPDATE.  This should ensure stability of https://github.com/baresip/baresip/pull/2454.
Here is a branch with more commits based on this: https://github.com/cspiel1/baresip/tree/test_call_simplify1
=> test call cancel rules

src/call.c
"The Contact, From, and To header fields contain a URI.  If the URI contains a comma, question mark or semicolon, the URI MUST be enclosed in angle brackets (< and >).  Any URI parameters are contained within these brackets.  If the URI is not enclosed in angle brackets, any semicolon-delimited parameters are header-parameters, not URI parameters."
Refs #2676
=> call: fix Refer-To URI angle brackets

test/call.c
- test: add rtcp_mux test
- test: rtcp test wait for RTCP SR instead off RTCP APP
=> test: add rtcp_mux test

webrtc/www/js/main.js
Default on Firefox/Chrome but needed by Safari, otherwise RTCP candidates are gathered
=> webrtc/js: add rtcpMuxPolicy require policy

CMakeLists.txt
`add_definitions` does not support cmake generator expressions and is replaced by `add_compile_definitions`
=> cmake: replace old add_definitions

include/baresip.h, modules/av1/av1.h, modules/av1/decode.c, modules/av1/encode.c, modules/avcodec/avcodec.h, modules/avcodec/decode.c, modules/avcodec/encode.c, modules/vp8/decode.c, modules/vp8/encode.c, modules/vp8/vp8.h, modules/vp9/decode.c, modules/vp9/encode.c, modules/vp9/vp9.h, src/video.c, test/mock/mock_vidcodec.c
With this change it's possible to use `video` getters within codec update callbacks.
=> video: use const struct video for videnc_update_h and viddec_update_h

tools/jbuf/.gitignore, tools/jbuf/README.md, tools/jbuf/audio/accounts, tools/jbuf/audio/config, tools/jbuf/env-template, tools/jbuf/generate_plot.sh, tools/jbuf/jbuf.plot, tools/jbuf/jitter-off.sh, tools/jbuf/jitter-on.sh, tools/jbuf/jitter.sh, tools/jbuf/plot_loop.sh, tools/jbuf/video/accounts, tools/jbuf/video/config
- tools: add jbuf plot tools
- tools: add jbuf audio call plots
- tools: jbuf support png plots
- tools: jbuf add README.md
- tools: jbuf README.md add note about units
- tools: jbuf typo in jbuf.plot
- tools: jbuf README.md add note about peer
=> tools: jbuf plots

src/ua.c
This way, the extension isn't lost if `ua_update_account` is called for example.
=> ua: move adding of norefersub extension to create_register_clients

modules/avcodec/decode.c
With hardware decoding I had crashes after `av_hwframe_transfer_data`. It looks like a clean `dst` frame is needed and can not be reused with some hardware codecs.
=> avcodec/decode: refactor hw_frame handling

src/video.c
If vtx_alloc fails (ENOMEM) video_destructor calls not initialized mutexes. This can be avoided by late destructing.
=> video: delay video_destructor

modules/avcodec/decode.c
`av_frame_unref` is called by `avcodec_receive_frame` but since `hw_frame` is used instead, it has to be called before
`av_hwframe_transfer_data` for `st->pict`
=> avcodec/decode: revert hw_frame handling and fix unref frame

include/baresip.h, src/audio.c, src/call.c, src/event.c
This will have the side effect of calling `ausrc_error_h` handlers with a 0 error code. I looked at the code (also in baresip-apps) and I didn't see any usages where this would break existing code.
I like the extra UA event `UA_END_OF_FILE`, which makes this more explicit.
=> Add UA_EVENT_END_OF_FILE 

test/call.c, test/main.c, test/test.h
Has to be rebased after merge of https://github.com/baresip/baresip/pull/2763
=> test: call - add test_call_100rel_video

src/call.c
The initial re-invite should be postponed for a random time in order to avoid
SIP 491 Request Pending error situations with concurrent re-invites.
The issue was 100% reproducible in our Asterisk setup with activated 100rel.
=> call: delay for the initial re-invite after call established

include/baresip.h, src/call.c, src/event.c, src/uag.c
This reduces complexity in the application code
- A few simple lines in baresip can reduce the complexity in the application if a call-on-hold information should be displayed.
- Fixes also multiple re-INVITES for resumes in a row if there is only one call.
=> call,event: add CALL_HOLD and CALL_RESUME events and fix call resume requests

test/call.c, test/mock/cert.c, test/mock/dnssrv.c, test/mock/mock_auplay.c, test/play.c, test/test.h
Here are some improvements for audio tests that will make it possible to add a 100rel test for audio, finally. All these will be useful to test against concurrency failures with the RX thread.
- test: call - replace re_cancel in audio_sample_handler() by cancel rule
- test: call - for test_call_aulevel() move new auframe_handler()
- test: play - update to auframe in auframe_handler
=> test: call - count audio frames

src/rtprecv.c
Fixes https://github.com/baresip/baresip/issues/2785. Please commit or provide better fix.
=> rtprecv: fix possible rtprecv_metric null pointer deref

src/rtprecv.c
Avoids NULL pointer dereferencing caused by call- and stream- API functions
if a call object has no RTP receiver (`use_rtp==false`).
=> rtprecv: add NULL pointer checks

include/baresip.h, src/call.c, test/call.c, test/main.c, test/test.h
relates to: https://github.com/baresip/re/pull/990
try to reproduce: https://github.com/baresip/baresip/issues/2772
- adds call on hold and resume test
- adds function to wait for SIP ACK
=> test: call - add call on-hold/resume test

test/call.c
I again had the failed assertion with `call_has_video()`.
Not sure if `call_has_video()` should be true or false after `call_set_video_dir(call, SDP_INACTIVE);`.
What we should check is already there:
```c
ASSERT_EQ(SDP_INACTIVE, sdp_media_ldir(vm));
ASSERT_EQ(SDP_INACTIVE, sdp_media_rdir(vm));
```
=> test: call - remove unstable check

test/call.c
Updates the `test_call_hold_resume` test by initiating a call and offering the streams as `sendonly`. The test verifies that this does not trigger an `UA_EVENT_CALL_HOLD` on the receiving side of this offer. It then does a few hold/resumes from both sides and verifies the events `UA_EVENT_CALL_HOLD` and `UA_EVENT_CALL_RESUME` are only triggered when they should.
=> test/call.c: extend test_call_hold_resume

src/audio.c, src/rtprecv.c
DTMF END is missing when registered to Asterisk.
Asterisk sends less RTP EVENT packets than baresip and does not mix audio RTP packets and DTMF packets like baresip. If the "DTMF end" follows directly a normal DTMF packet than it was not recognized.
- call `stream_pt_handler()` always
- `stream_pt_handler()` in audio and video have a lightweight check at top
- NULL pointer check of audio.rx is not needed
Alternative check with less lines, but more difficult to read:
```c
if (pt == rx->pt && (!rx->pt_tel || pt != rx->pt_tel))
return 0;
```
Does somebody prefer the shorter check?
=> audio: fix inbound dtmf END event

src/uag.c
Fixes SIP 404 for NAT setups.
In registrar less setups the IP address in the Request-URI might differ from
the local IP address if the SIP request comes from NAT. The UA fallback should
not be restricted to local IP addresses.
=> uag: fallback for registrar-less NAT setups

modules/menu/menu.c
The local media direction should be taken into account for the limit not the
remote.
=> menu: fix outgoing early media limit

modules/menu/menu.c, modules/menu/menu.h
This change fixes an issue that occurs by calling `ua_connect()` in the UA
event handler. The OUTGOING event was sent to the application before the
REFER or REDIRECT events that should trigger a follow up SIP call.
The UA events should be sent in this order to the application:
- REFER, then OUTGOING
- REDIRECT, then OUTGOING
=> menu: add follow up invite timer

src/video.c
There was a sporadic warning from clang sanitizer:
stream_update /home/runner/work/baresip/baresip/src/stream.c:893 that
writes to stream->tx.pt_enc
vs
packet_handler /home/runner/work/baresip/baresip/src/video.c:353 that
reads from pt_enc
Found here:
https://github.com/baresip/baresip/actions/runs/7164207883/job/19503867573
=> video: fix thread sanitizer warning

src/uag.c
This PR combines catch all accounts with fallback UA selection.
Only catch all accounts are used as fallback UAs.
Relates/fixes: https://github.com/baresip/baresip/issues/2822
=> uag: use catchall flag for fallback UA selection

CMakeLists.txt
CMake 3.28 is latest version: https://cmake.org/download/
=> cmake: bump minimum to 3.14

README.md, modules/debug_cmd/debug_cmd.c
As libre requires OpenSSL >= 1.1.1 or LibreSSL 3.x, I am unable to build baresip (requiring libre) against something older…
Additionally: Output of cmake while building baresip:
> -- Found OpenSSL: /usr/lib64/openssl3/libcrypto.so (found suitable version "3.0.7", minimum required is "1.1.1")
=> readme: update supported OpenSSL/LibreSSL versions

README.md
Since baresip has atomic support, gcc 4.8.x (as shipped in RHEL/CentOS 7) doesn't work for me any longer to build baresip, thus it seems to require gcc >= 4.9 (like libre does already).
=> readme: update supported compiler versions

modules/menu/menu.c
- menu: avoid parallel established calls with autoanswer
- menu: fix call waiting tone for auto-answer
When `;answermode=auto` is set for the account the expected behavior is:
- If there is an established call, ignore the auto answer setting. --> start call-waiting tone
- If there is an outgoing call, then terminate the outgoing call and answer the incoming call immediately.
=> menu autoanswer handling

modules/gzrtp/gzrtp.cpp
gzrtp module didn't compile anymore after https://github.com/baresip/re/commit/c64974a8e424b12974c2508eb289b96363c728b5.
=> Renamed gzrtp ARRAY_SIZE macro

modules/avcapture/avcapture.m
=> avcapture: fix deprecated AVCaptureDeviceTypeExternalUnknown

include/baresip.h, modules/menu/static_menu.c, src/call.c, src/ua.c, test/call.c
fix and simplify SDP negotiation state handling
The bool sent_answer is removed and instead the sdp_neg_state of the sipsess is used which accurately tracks the state of the SDP negotiation.
Further, call_set_mdir was removed and unified in call_set_media_direction.
Related re PR:
- https://github.com/baresip/re/pull/1016
=> sipsess: refactor and simplify SDP negotiation state

src/audio.c, src/stream.c, test/call.c
Adds three calls to `audio_debug()` to `test_call_rtcp` which shows that there are concurrency failures in `main`. Further provides the fixes.
- test: call - concurrency test for audio_debug()
- audio: lock r/w of tx->ts_ext
- stream: lock rtp_send() vs rtp_debug()
=> audio: solve concurrency failures of TX thread

src/aureceiver.c
The aubuf is created when the first audio frame is pushed. It can't be created during initialization because e.g. `srate` and `channels` may be changed in the filters.
Since the auplay thread (often) is started before the first audio frame is decoded, it has to check if the aubuf was already created.
Thus a mutex is needed.
=> aur: a mutex for aubuf allocation

include/baresip.h, modules/menu/dynamic_menu.c, modules/menu/static_menu.c, src/call.c, src/ua.c, test/call.c
call_set_media_direction() and call_set_media_estdir() doesn't need an error
handling.
=> call: remove unused error handling of some API functions

modules/menu/menu.c, modules/menu/menu.h
Additionally, the ringtone is only started for the first incoming call.
The ringtone is not stopped if another call is incoming.
If there are multiple incoming calls, then the first incoming call is answered with command `accept` by default.
Current behavior in main: The last incoming call is answered.
=> menu: an incoming call should not change the current call

modules/mqtt/mqtt.c
If return code (rc) is not zero, the disconnect is unexepected and a reconnect should always be started.
Fixes #2865 (has to be tested)
=> mqtt: improve disconnect reconnect handling

.github/workflows/valgrind.yml, docs/examples/config, include/baresip.h, src/audio.c, src/aureceiver.c, src/config.c, src/core.h, src/rtprecv.c, src/stream.c, test/call.c, test/main.c
The last part for the audio RX "real-time" thread.
Enables RX thread via config, uses worker for passing work to the main thread and adds tests to ensure thread safety.
- stream,rtprecv: activate RX thread via config
- test: run call tests with RX_MODE_THREAD
- test: main - init async workers
- rtprecv: detach from RTP/RTCP sockets before re_cancel
- stream,rtprecv: detach from RTP/RTCP also in RECEIVE_MODE_MAIN
- test: call - add AUDIO_MODE_THREAD for test_call_aufilt
- test: call - reset to RECEIVE_MODE_MAIN
- rtprecv: use enable flag to prevent data race on stream termination
- test: call - do not test unsupported combination
- test: call - failure debug for test_media_base()
- rtprecv: detach sockets before attach
- rtprecv: warnings for UDP thread attach
- aur: add mutex locks
- aur: …
=> misc: rx thread activate

src/ua.c
If someone calls to the local IP (e.g. 1.2.3.4) with a user less dial URI, then the call is rejected and a warning is printed. The warning currently shows an empty msg URI.
e.g. `msg->uri = "sip:1.2.3.4"`
=> ua: improve SIP 404 warning

src/account.c
`acc->rtcp_mux` is already printed and a boolean, so this leads to segfaults
=> account/debug: fix wrong and redundant rtcp_mux printf

cmake/FindRE.cmake
Effectively, `PATHS /usr/local/include/re /usr/include/re` and `PATHS /usr/local/lib64 /usr/lib64 /usr/local/lib /usr/lib` are added to match other `Find*.cmake` files more closely and also to address "Could NOT find RE (missing: RE_INCLUDE_DIR)" from #2899.
=> cmake: add /usr/{local,}/include/re and /usr/{local,}/lib{64,} to FindRE.cmake

.github/workflows/fedora.yml
To make this workflow failing, commit f4590fe6563aecf98c00be3b85d0f94278748966 needs to be reverted.
See also:
- https://github.com/baresip/baresip/issues/2849
- https://github.com/baresip/baresip/pull/2850
=> ci: add Fedora workflow to avoid e.g. rpath issues

CMakeLists.txt, docs/examples/config, src/config.c
Especially Linux distributions support, additionally to the already existing CA file, also CA paths, such as `/etc/ssl/certs` (Debian, openSUSE, SLES), `/etc/pki/tls/certs` (Fedora, CentOS/RHEL) or `/system/etc/security/cacerts` (Android).
This makes a default CA path configurable for downstreams during build-time (and provides a proper default aligned with CA file).
=> config: support distribution-specific/default CA paths

src/config.c
Thanks to @juha-h in https://github.com/baresip/baresip/pull/2905#issuecomment-1937099354, we can add the default CA path for Android, too.
=> config: add default CA path for Android

docs/examples/config, include/baresip.h, src/config.c, src/uag.c
config,uag: add sip_verify_client for TLS connections
Per default, client certificates are neither requested nor verified.
=> transp,tls: add TLS client verification

docs/examples/accounts, include/baresip.h, src/account.c, src/core.h, src/message.c, src/ua.c, test/message.c
Currently, BareSIP accepts all incoming SIP MESSAGE requests as long as they are addressed to a valid UA. This poses a security risk and is not conformant to the security considerations in [RFC 3428 section 11](https://www.rfc-editor.org/rfc/rfc3428#section-11).
With this change, SIP MESSAGEs can be enabled per account using the new account option `uas_req` (the default is off) and can be set to require TLS. If `uas_user` or `uas_pass` are set, authentication is required.
Further, a foundation was built to extend this to other out-of-dialog requests like REFER.
=> account,message,ua: secure incoming SIP MESSAGEs

modules/aufile/aufile_play.c
This fixes the error case that `aufile_write()` fails. In this case the thread
was not joined in the destructor and the threads cleanup was missed.
=> aufile: join thread if write fails

include/baresip.h, src/video.c
It's useful for an SFU (Selective Forwarding Unit) to request a picture update (new keyframe) from the encoder, when a new subscriber is added.
=> video: add video_req_keyframe api

src/call.c
In certain configurations involving early-media BareSIP sends a re-INVITE once the dialog is established to have different stream configurations in the established state and in the early media state (e.g. early state: audio=inactive,video=recvonly; established: audio=sendrecv,video=sendrecv). Other UAs often like to send re-INVITEs too once the dialog is established (e.g. Asterisk).
This can lead to glare situations becoming very common where both UAs send re-INVITEs at the exact same time, resulting in long delays in getting the streams to the desired state.
To mitigate this (especially for the case when a BareSIP UA calls another BareSIP UA), we'd like to propose to slightly change the timer for `set_established_mdir` depending on whether the call is outgoing or incoming. We have this …
=> call: improve glare handling

include/baresip.h, modules/menu/dynamic_menu.c, modules/menu/static_menu.c, src/call.c, src/ua.c, test/call.c
This reverts the behavior of `call_set_media_direction` to how it used to be. Further, re-introduce `call_set_mdir` which only sets the current media direction.
The change in behavior was introduced in #2818 in order to simplify and clarify the setting of media directions.
Resolves: #2939.
=> call: set estdir in call_set_media_direction

src/audio.c, src/aureceiver.c, src/core.h
Fixes #2935.
This is a minimal fix which we should merge now. Similar to `audio_encoder_set()` the audio player is started in `audio_decoder_set()`.
@maximilianfridrich and me plan to do some redundancy cleanup after the upcoming release for
- `call_stream_start()` vs
- `update_streams()`
- `update_audio()`
- `start_audio()`
- `audio_decoder_set()`
- `audio_encoder_set()`
- `audio_start()`
=> audio,aur: start audio player after early-video

.github/workflows/sanitizers.yml
`vm.mmap_rnd_bits` has been recently changed to 32 on GHA, which triggers issues in ASAN builds that spuriously fail on startup.
Fixes #2966
=> ci/sanitizers: add mmap rnd_bits workaround

src/account.c
This caused a `SIGABRT` when an outbound proxy is set and account debug information is printed (because of the `RE_VA_ARG` usage in `print.c`).
=> account: use correct format %zu for printing outbound

modules/sndfile/sndfile.c
When the update functions are called the sample rate and format can't be
predicted. Thus the header has to be written when the first audio frame reaches
the filter.
Issue mentioned here: https://github.com/baresip/baresip/discussions/2938#discussioncomment-8849657
=> sndfile: write correct sample rate to WAV header

docs/examples/config, include/baresip.h, src/config.c, src/uag.c
config,uag: add sip_tls_resumption config
TLS session resumption through tickets can compromise forward secrecy if the session ticket key is not rotated regularly (see [RFC 9325 section 3.4](https://www.rfc-editor.org/rfc/rfc9325#section-3.4) for details). Per default, this does not happen in OpenSSL, so we should allow to turn off the use of session tickets ([Mozilla recommends this](https://github.com/mozilla/server-side-tls/issues/135), [Apache warns about this](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslsessiontickets)).
Note: The current behavior of BareSIP stays the exact same unless the `sip_tls_resumption` option is specifically set.
=> tls: add session resumption setter

modules/mixausrc/mixausrc.c
- Fixes resampling of audio source which is mixed into the stream.
- Does some code cleanup.
- Adds warning if sample format is not supported.
Because auresamp filter can be loaded at arbitrary position, the sample rate has to be taken from the stream in functions `encode()`/`decode()`.
mentioned here: https://github.com/baresip/baresip/discussions/2938#discussioncomment-8949868
=> mixausrc: fix ausrc resampling

src/video.c
Use of `stream_enable_tx(false)` when video sending is switched off may avoid concurrency problems with the Video TX thread.
Use of `stream_enable_rx(false)` when video receiving is switched off is a first step for enabling Video RX thread.
=> video: stream enable/disable for re-INVITE/UPDATE

include/baresip.h, modules/srtp/srtp.c, src/core.h, src/stream.c, test/call.c, test/main.c, test/test.h
It's allowed to re-key and change the cipher-suite of streams at any point in time. While the new information got processed, the decryption objects never got updated.
For completeness the srtp got a command to re-key outgoing streams of a given call, selected by call id.
The new testcase depends on an re PR [#1089](https://github.com/baresip/re/pull/1089) for checking the streaming keys.
=> srtp: allow rekeying of running streams

src/ua.c
According to [RFC 3261 section 8.1.1.7](https://www.rfc-editor.org/rfc/rfc3261#section-8.1.1.7) the branch parameter in the Via header MUST start with the magic cookie "z9hG4bK". This is now enforced.
Some UAs don't comply with this and send multiple requests with the same branch values which can cause issues.
=> ua: enforce magic cookie in Via branch

src/video.c
- disable stream before video source is stopped
- enable stream after video source was started
=> video: enable/disable stream at common point

include/baresip.h, modules/srtp/srtp.c, src/stream.c, test/main.c
* while the main thread may remove the st->srtp_rx struct, the rx thread accessed the freed memory.
* concurrent access of st->srtp_rx is mitigated with lock.
* critical section is between first possible removal of st->srtp_rx, until new st->srtp_rx is ready. for the rx thread the access to srtcp_decrypt and srtp_decrypt.
=> srtp: lock possible re-keying against usage in receive handler

src/audio.c, src/call.c
- Function `audio_update()` sets filters, decoder, encoder and starts the audio
source.
- Function `audio_decoder_set()` sets the decoder and (re-)starts the audio
player.
- Similar code was removed from call.c.
part 3 of: https://github.com/baresip/baresip/pull/2945
This solution was taken from `video_update()`.
=> call,audio: remove audio start/stop redundancy

src/call.c
[RFC 2976 section 2.2](https://www.rfc-editor.org/rfc/rfc2976#section-2) states that INFO requests with no message body MUST be answered with 200 OK.
=> call.c: allow INFO requests with no body

src/audio.c, src/stream.c
Fixes call termination if there are no common audio codecs, but video is
possible. In this case now the audio stream is stopped and the call proceeds
with the video stream. In bound DTMF is not possible.
Related: https://github.com/baresip/re/pull/1128 which fixes a further issue:  the BYE was not sent.
=> audio,stream: video only call if no common audio codecs

src/ua.c
A c line with address 0.0.0.0 is allowed. In this case this should not be used
as laddr.
=> ua: avoid empty IP in SDP as local address

modules/auresamp/auresamp.c
Second "try". Now it should be correct.
The test is activated here in this draft: https://github.com/baresip/baresip/pull/3047
`st->sampv` is used for:
- audio format conversion from input format to s16le and for
- conversion from s16le to the output format (= input format)
The maximum size needs to be allocated.
=> auresamp: fix size of sampv if aufmt conversion needed

.github/workflows/coverage.yml, .github/workflows/sanitizers.yml, .github/workflows/valgrind.yml, test/CMakeLists.txt, test/call.c, test/main.c, test/mock/mock_aucodec.c, test/test.h
This PR adds a test for audio filters. More concretely:
- auconv
- auresamp
```
audio tx pipeline:      ausine ---> aubuf ---> auconv ---> auresamp ---> aucmock
audio rx pipeline:  mock-auplay <--- aubuf <--- auconv <--- auresamp <--- aucmock
```
It tests these combinations
| ausrc/auplay | codec |
| -------- | --------- |
| s16le | s16le |
| s16le | float |
| float | s16le |
| float | float |
resampler test:
```
auresamp: resample encoder 16000/1 --> 48000/2
auresamp: resample decoder 48000/2 --> 16000/1
```
=> test: call - complete test for auconv

docs/examples/config, modules/webrtc_aec/aec.cpp
The module currently contains a description for the `webrtc_aec_extended_filter` parameter, but didn't provide an implementation.
The PR implements the `webrtc_aec_extended_filter` option.
=> webrtc_aec: Add support for extended filter option

modules/aufile/aufile_src.c
Reading a WAV file as fast as possible can be done with `aufile_open()` from `re`.
So we simply could make `ptime==0` unsupported, and return EINVAL in such a case.
=> aufile: ptime zero check for ausrc

src/core.h, src/ua.c, src/uag.c
BareSIP always has the SUBSCRIBE method in its Allow header, so other UAs correctly assume that we will respond to those. However, if no `subh` is set, these SUBSCRIBE messages will not be responded to.
Now, only if `subh` is set, we add SUBSCRIBE to the Allow header and if it is not set, we respond with 405 Method Not Allowed (see [RFC 3261 section 8.2.1](https://www.rfc-editor.org/rfc/rfc3261#section-8.2.1)).
=> ua,uag: support SUBSCRIBE only if handler is set

modules/mixausrc/mixausrc.c
Fixes: https://github.com/baresip/baresip/issues/3049
- ptime taken from stream
- sampc, nbytes computed from ausrc sample rate
- the resampler needs maximum sampc between input/output
=> mixausrc: fix downsampling

test/ua.c
similar to c15b6e2a8d28ac74715f9d0cf141e337f5279ffd
Fixes: https://github.com/baresip/baresip/issues/3066
=> test/ua: disable dns cache for reg_dns tests

src/mediatrack.c
audio `decoder` and `encoder` must be set before calling `audio_start_source`
=> mediatrack: fix audio_start_source aufiltl setup order

modules/srtp/srtp.c
The base64 decode routine requires a buffer size that is somewhat larger than the expected key size by olen < 3 * (ilen/4). When given just the expected key size for AEAD_AES_256_GCM as the base64 output length, EOVERFLOW is returned.
This was previously discussed in https://github.com/baresip/baresip/pull/790 when AEAD_AES_256_GCM support was added, but has regressed due to #2975.
Found the issue and tested the fix by making calls both to other Baresip instances and to FreeSWITCH.
=> srtp: Fix base64 key decoding for AEAD_AES_256_GCM

.clangd
Necessary if the chosen compiler is not clang but clangd is used as a language server.
=> .clangd: suppress -Wgnu-zero-variadic-macro-arguments

modules/audiounit/audiounit.c, modules/audiounit/sess.c
Since iOS 7, AudioSession is deprecated and should be handled by application, so CallKit handling is easier to integrate.
=> audiounit: remove deprecated iOS session handling

docs/examples/config, include/baresip.h, src/config.c, src/core.h, src/message.c, src/reg.c, src/ua.c, src/uag.c
If the new config option `filter_registrar` is set to some transport (default: `""`), any incoming request of that transport is verified to have originated from a registered server's IP address (only makes sense for registered accounts `regint>0`). Further, no listening socket is opened for the connection-oriented transport protocols listed in `filter_registrar` (i.e. a UDP socket is always opened if UDP is configured). BareSIP's default behavior stays the exact same.
Requires:
- https://github.com/baresip/re/pull/1160
=> add filter_registrar option

test/call.c
only a workaround for now. SNI works but the selftest is broken because all UAs share the same SSL_CTX.
=> test/call: fix SNI selftest

modules/ice/ice.c
When searching for ICE candidates is not completed, but the peerconnection is quickly closed (https://github.com/baresip/baresip/blob/main/webrtc/src/sess.c#L260) the WebRTC demo will crash. 
Adding there small checks analog to this one https://github.com/baresip/baresip/blob/main/modules/ice/ice.c#L112 fixes the issue for me. I am not sure if any of the other functions should also have this check added.
=> ice: fix crash during ICE on fast disconnect

test/call.c
test/call: set global certificate again in SNI test
=> test/call: set global certificate again in SNI test

src/uag.c
Currently, when finding a UA for an incoming msg, the transport protocol and address family only had to match for registrarless (regint=0) accounts.
Consider the case where `sip_transports  udp,tls` and there is a server account configured with `<sip:vuln@sip.example.com;transport=TLS>;regint=60`. Now BareSIP receives an incoming INVITE via UDP addressed to the account `vuln`. The account would be matched even though it is configured to use TLS.
Now, the transport protocol of the account (if configured) and the address family has to match, even if it is a server account (regint>0), which is the same behavior as it has always been for registrarless accounts.
=> uag: match transport and af when finding ua for msg

test/call.c, test/main.c, test/test.h
test/call: add account certificate selection test
Currently, the test fails (as expected). With the [fix in libre](https://github.com/baresip/re/pull/1173) the test is green.
Fix:
- https://github.com/baresip/re/pull/1173
=> sip/transp: add client certificate to all TLS transports

include/baresip.h, modules/auresamp/auresamp.c, modules/mixausrc/mixausrc.c, modules/mixminus/mixminus.c, modules/webrtc_aecm/aec.cpp, src/audio.c, src/aufilt.c
Currently audio filters can not be disabled. Maybe a application want only record specific calls, so a filter like `sndfile` can be enabled/disabled at runtime now.
=> aufilt: add aufilt_enable

src/bevent.c, src/call.c, test/bevent.c
Step 2 of initial PR https://github.com/baresip/baresip/pull/3090
=> bevent: add backwards wrappers

modules/aufile/aufile_src.c
In order to retrieve the duration a read handler or setting ptime
is not needed.
Compare with module gst!
config:
```
module_app		debug_cmd.so
module			aufile.so
file_ausrc		aufile
```
```
$ echo "/aufileinfo ring.wav" | nc -N localhost 5555
/aufileinfo ring.wav
aufile: loading input file '/usr/local/share/baresip/ring.wav'
aufile: /usr/local/share/baresip/ring.wav: 8000 Hz, 1 channels, PCMU
debug_cmd: length = 1.514 seconds
```
=> aufile: fixes for prm->duration

include/baresip.h, modules/account/account.c, src/account.c, src/call.c, src/core.h, src/peerconn.c, src/video.c, test/account.c
This PR is an extension of this PR: https://github.com/baresip/baresip/pull/796
It adds support for specifying video source and display per account.
The global config will be used by default as fallback.
=> account specific video source and display

src/ua.c
Currently, only the first matching header is removed when calling ua_rm_custom_hdr. Now, all matching headers are removed.
=> ua: remove all matching headers when calling ua_rm_custom_hdr

src/bevent.c, src/call.c, src/reg.c, src/ua.c, src/uag.c
- core: use bevent API
- fix: `UA_EVENT_SHUTDOWN` moved to event class `BEVENT_CLASS_UA`
Step 3 of initial PR https://github.com/baresip/baresip/pull/3090
=> bevent: update function calls in src

test/call.c, test/ua.c
core: use bevent API
Step 3 of initial PR https://github.com/baresip/baresip/pull/3090
=> test: use bevent API

modules/menu/menu.c
core: use bevent API
Step 3 of initial PR https://github.com/baresip/baresip/pull/3090
=> menu: use new bevent API

modules/menu/menu.c
replace deprecated call to `ua_event()` by `bevent_call_emit()`
=> menu: use new bevent_call_emit()

docs/examples/config, include/baresip.h, modules/menu/menu.c, src/config.c, src/ua.c, test/call.c
Replaces https://github.com/baresip/baresip/pull/3088 "Moved 180 Ringing response from core to app (menu module)"
- The application decides when to send a 180 Ringing.
- A new config setting `call_accept` can be set to `yes` in order to let the baresip core reply with 180 Ringing, like before.
Note: As requested by @juha-h this changes the default behavior of the baresip core, because `call_accept` is `off` by default.
- [x ] module ebuacip
=> ua,menu: do not accept call by default

include/baresip.h, modules/aufile/aufile.c, modules/aufile/aufile.h, modules/aufile/aufile_src.c, modules/debug_cmd/debug_cmd.c, modules/gst/gst.c, src/ausrc.c
replaces: https://github.com/baresip/baresip/pull/3103
Another solution for duration retrieval.
Retrieving the duration of an audio file may lead to long blocking
delay. E.g. gst_element_query_duration()
Now a callback handler can be called by the application only if
needed.
```c
int ausrc_info(struct list *ausrcl, const char *name, const char *device, struct ausrc_prm *prm);
```
- Sets the fields of given ausrc_prm.
- No need to alloc an ausrc_st.
=> ausrc, aufile, gst, debug_cmd: rework on ausrc duration retrieval

src/audio.c
=> audio: initialize ausrc_prm

modules/jack/jack_play.c, modules/jack/jack_src.c
With multiple jack instances it's useful to configure server name.
=> jack: add jack_server_name config

include/baresip.h, modules/menu/menu.c, modules/menu/menu.h, modules/menu/static_menu.c, src/ua.c, src/uag.c
- ua,menu: move DnD to menu
- uag: add uag_reject() with log info
=> bevent: move dnd to menu

include/baresip.h, src/call.c
- call: add a getter for local stream directions
- call: respect local media direction on incoming call
The new getter allows an application to query the current local media direction. It is possible that other application modules change the local media direction e.g. with `call_set_mdir()`.
```c
case UA_EVENT_CALL_INCOMING:
call_set_mdir(call, SDP_SENDRECV, SDP_SENDONLY);
break;
```
=> call: a getter for local media directions

.github/workflows/sanitizers.yml, include/baresip.h, src/conf.c
=> conf: use str_dup for conf_path_set

modules/menu/menu.c
The media direction was never updated if the early audio limit was
reached and the call has no video stream.
=> menu: fix early audio limit for video less call

CMakeLists.txt, modules/gtk/gtk_mod.c, share/com.github.baresip.desktop, src/config.c
Short term solution for wayland and gnome desktops.
Added a window with a button, which only opens the same menu as the status icon would.
Added config values to setup which GTK you want.
Wayland needs the .desktop file to show notifications, so I added one for baresip.
Right now, this would open baresip with a terminal, because I still think, that menu should be used for most of the configuration.
GTK no longers registered into menu, since in wayland every action needs a GTK event, which is not triggered this way.
Pictures:
=> GTK added standalone main window

test/call.c
The warnings are expected because some TLS handshakes in the test are supposed to fail.
Fixes: #3171
=> test/call.c: test_call_sni: silence warnings

.github/workflows/fedora.yml
Important: This is just a workaround, *not* a solution for #3183. The real solution is to perform the changes related to the newer RPM version in Fedora 41, but this will happen on my side *at earliest* at the end of next week.
=> ci/fedora: Use Fedora 40 until CI is updated for Fedora 41

CMakeLists.txt
Fixes #3191, a regression related to cmake globbing of `*.desktop` introduced with commit 085e86f (#3127).
=> cmake: install logo.png and *.wav files again (fixes #3191)

modules/menu/menu.c, src/bevent.c, test/bevent.c
This adds an enum `bevent_class` field to `struct bevent` because it should not be derived from the `enum ua_event`. This does not always give wanted results. The second commit gives an example how the fixed API can be used.
- **bevent: add enum bevent_class to struct**
- **menu: emit bevent for dnd reject**
=> menu dnd event

.github/workflows/build.yml
Build using latest GCC version
=> ci/build: use GCC 14 on Ubuntu 24.04

.github/workflows/fedora.yml
- Adapt workflow for RPM 4.20 in Fedora 41 (fixes #3183)
- Unpin Fedora 40 (undo #3184)
- Run baresip `selftest` on Fedora, too (https://github.com/baresip/baresip/issues/3183#issuecomment-2452985417)
=> ci/fedora: adapt workflow for RPM 4.20 in Fedora 41 (fixes #3183)

modules/menu/menu.c
The UA_EVENT_CALL_REDIRECT event contains the status code and Contact
URI with comma separated. E.g.: 302,sip:10.10.0.5
=> menu: fix 302 Moved Temporarily redirect call

cmake/modules.cmake, modules/wasapi/CMakeLists.txt, modules/wasapi/play.c, modules/wasapi/src.c, modules/wasapi/util.c, modules/wasapi/wasapi.c, modules/wasapi/wasapi.h
This is a replacement for the winwave module, since Windows 7 there are newer improved Core Audio APIs.
=> wasapi: Add WASAPI Audio module

modules/pulse/pastream.c
Most baresip audio drivers use "default" string, instead of empty.
=> pulse: use default string as default device

modules/mixausrc/mixausrc.c
Currently, if the `ptime` of an audio stream changes, `mixausrc` gets stuck in a loop where it keeps printing a warning "mixausrc: ptime changed" and no more audio is processed. This is fixed by resetting the `ptime` of `mixstatus` if a `ptime` change is detected.
=> mixausrc: reset mixstatus ptime if ptime changes

src/bevent.c
Let this information be readily available for example in JSON events as emitted by the ctrl_tcp module.
=> bevent: Add local URI information to events

modules/wasapi/src.c
For some audio interfaces/systems, the buffer size is too small and produces poor audio quality due to overuns.
=> wasapi/src: increase record buffer size

include/baresip.h, src/call.c, src/ua.c, test/call.c
This adds a more general version of `ua_hangup()` to the API which allows to add custom headers. E.g. `Contact:` and `Diversion:` for a 302 Moved Temporarily.
```c
void ua_hangupf(struct ua *ua, struct call *call,
uint16_t scode, const char *reason, const char *fmt, ...);
```
related application: https://github.com/baresip/baresip-apps/pull/57
related discussion: https://github.com/baresip/baresip/discussions/3207
=> ua,call: add API for rejecting incoming call

include/baresip.h, src/video.c
Currently, video encoders only receive picture update information (i.e. new keyframe request) when the encoder's frame handler is called. When the encoder's packetize handler is called, this information is not passed on. Some videosrc/vidcodec combinations only work in this "pass-through" mode where *only* the packetize handler is called, and the encoder will never receive picture update information. However, some encoders can still act on picture update requests even when operated in "pass-through" mode, so now the `update` bool is also passed to the packetize handler.
=> video: add picture update bool to vidpacket

modules/menu/menu.c, modules/menu/menu.h, modules/menu/static_menu.c
This can be useful for replying for example with "603 Decline" which indicates that the user does not want to answer the call at all. From [RFC 3261 section 21.6.2](https://www.rfc-editor.org/rfc/rfc3261#section-21.6.2):
```
21.6.2 603 Decline
The callee's machine was successfully contacted but the user
explicitly does not wish to or cannot participate.  The response MAY
indicate a better time to call in the Retry-After header field.  This
status response is returned only if the client knows that no other
end point will answer the request.
```
=> menu: add scode and reason arguments to hangup command

include/baresip.h, modules/menu/menu.c, src/call.c, src/ua.c, test/call.c
- **ua,call: prevent double ua_accept**
- API function ua_accept() can be called by multiple modules which handle
the shortly added UA_EVENT_SIPSESS_CONN. This commit prevents that
multiple call/sipsess/sip_dialog objects are created for a single SIP
INVITE message.
- **menu,test: bevent_stop after ua_accept**
-  After accepting a call the bevent should not be handled by following
event handlers.
=> ua prevent double call accept

src/bevent.c
This fixes serialization of `BEVENT_CLASS_SIP` events. If display name is not set `odict_encode_bevent()` failed and the event was not sent e.g. via dbus.
=> bevent: fix encode bevent without display name

.github/workflows/fedora.yml
- Removed RHEL/CentOS 7 related package filter given it's EOL since 2024-06-30
- Updated build-time requirements based on Fedora 42 spec file (effectively builds FFmpeg-requiring baresip modules)
=> ci/fedora: synchronize packages with spec file from Fedora 42

src/config.c
This improves readability and new/unspecified struct members are by default zero.
=> config: use designated initializers

.github/workflows/coverage.yml
I need to investigate why ubuntu 24.04 fails, for now let's stick with 22.04
=> ci/coverage: use ubuntu-22.04

test/call.c
fix for: https://github.com/baresip/baresip/issues/3281
For discussion: Should we fix the test or do we have a potential problem that RTP packets are missed when the call becomes established?
=> test: make test_call_bundle stable

src/rtprecv.c
Format: "stream: %s: dropping %u<-- SIZE ERROR
=> rtprecv: fix info printf size error

modules/menu/menu.c
Otherwise, when `UA_EVENT_SIPSESS_CONN` is done processing in the menu event_handler, `menu_set_incall` and `menu_update_callstatus` will be incorrect, leading to the `dynamic_menu` being broken.
=> menu: return on UA_EVENT_SIPSESS_CONN

modules/pulse/pastream.c, modules/pulse/player.c, modules/pulse/recorder.c
This fixes SEGVs when pulse is restarted during a call.
=> pulse: add NULL checks for paconn_get

modules/menu/static_menu.c
Hanging up a call by simpy typing `b` was broken. This is fixed now and hanging up with parameters still works (e.g. `/hangup scode=603`).
=> menu: remove CMD_PRM flag from hangup command

src/call.c
src/call.c:1815:9: warning: Identical condition and return expression 'err', return value is always 0 [identicalConditionAfterEarlyExit]
return err;
^
src/call.c:1809:6: note: If condition 'err' is true, the function will return/exit
if (err)
^
src/call.c:1815:9: note: Returning identical expression 'err'
return err;
^
=> call: fix cppcheck warning

include/baresip.h, modules/menu/menu.c, src/call.c
Fixes #3324 
I suggest to set the logical `&` of contact and the "established" media direction (`estadir`, `estvdir`).
For both `SDP_SENDRECV` is the default. The user should have the chance to switch any direction off
- permanently for the contact (e.g. for security reasons) or
- for one call via `dialdir`.
This fixes the issue #3324 and works also in combination with 183 Session Progress. Whereas commands like
- `medialdir` override the media direction for the specified call and
- `videodir` override the mdir temporarily for the current call state (early media, resp. established).
Commits:
- **call: a getter for the established media direction**
- **menu: contact media direction vs dialdir (#3324)**
=> menu fix contact media direction

modules/aac/aac.c
Caused a crash on Debug build on Linux ...
=> aac: fix formatting arguments to %w

src/rtprecv.c
Format: "stream: %s: SSRC changed 0x%x -> 0x%x (%u<-- SIZE ERROR
=> rtprecv: fix debug printf size error

cmake/FindOPUS.cmake
remove standalone `opus.h`, we always include `<opus/opus.h>`
=> cmake/FindOPUS: align include path names

modules/mixminus/mixminus.c, src/audio.c
If tx audio threads are used mutex locking is needed.
Fixes #3359
=> misc: fix audio tx thread filter locking

src/conf.c
When first beed accessed from `conf_obj = mem_deref(conf_obj);` around line `conf.c:372`, `conf_obj` is not a initialized value.
=> conf: initialize conf_obj

modules/avcapture/avcapture.m, src/video.c
According to macOS doc: https://developer.apple.com/documentation/avfoundation/avcapturescreeninput?language=objc
_Starting in macOS 12.3, use the [ScreenCaptureKit](https://developer.apple.com/documentation/ScreenCaptureKit?language=objc) framework for screen recording instead._
However, this feature is still useful with minimum change.
=> avcapture: add macOS screen capture

include/baresip.h, src/main.c, src/module.c
The `ctrl_tcp` module fails to initialize when attempting to preload it with `baresip -m`. This MR addresses this issue with the following changes:
1. Update main to initialize the UA before preloading modules - makes the UA available to the initialization routine of  `ctrl_tcp` (and any other modules like it).
2. Update `load_module` to skip dynamic loading for static modules. If a static module is found an attempt is made to load/initialize it, and the result returned to the caller immediately. Previously, a static module that failed to initialize would fall through to the dynamic case which leads to misleading errors (in the `ctrl_tcp` case) or confusing behavior.
3. Update `module_preload` to allow pre-loading modules from the current working directory or from the configured module …
=> ctrl_tcp preload: allow preloading of ctrl_tcp module on baresip command line

include/baresip.h, src/call.c
Commit targeting #3367.
Indentation updated to not exceed 79 columns. Some indentation is being pushed during the commit, let me know should there be any feedback re style etc or pls feel free to make any edits as you deem necessary. 
test_call_attended_transfer passing
```log
./build/test/selftest -r main -v test_call_attended_transfer
running baresip selftest version 3.22.0 with 1 tests
Local network addresses:
lo0:  fe80::1
utun0:  fe80::2ba4:8a12:d9de:58d2
en0:  fe80::18f0:a2eb:e1dc:3cfd
en0:  fd47:2d2a:e27b:d848:188a:b882:90dc:7738
en0:  192.168.0.32
awdl0:  fe80::706b:5bff:fee5:dea5
utun1:  fe80::d5a1:760f:cdf5:79fd
utun2:  fe80::c67d:14cb:c784:832
utun3:  fe80::ce81:b1c:bd2c:69e
utun5:  fe80::9865:8ec3:7587:dc88
utun6:  fe80::ee4f:eddb:d14b:780b
utun7:  fe80::332b:88f6:6bdb:e0bf …
```
=> call: added from-tag and to-tag to Refer-To header in call_replace_transfer

src/call.c
* [call: do not go back to RINGING state if already in EARLY](https://github.com/baresip/baresip/pull/3402/commits/c0eb101d78c03432849cd3ad257a27df9cdd88dc)
The function call_progress may fail with EAGAIN (e.g. if awaiting
PRACK). In that case, try again if a PRACK was received.
* [call: do not go back to RINGING state if already in EARLY](https://github.com/maximilianfridrich/baresip/commit/c0eb101d78c03432849cd3ad257a27df9cdd88dc)
In some cases, for example when 100rel is used, 1XX responses may arrive
out of order (e.g. due to re-transmissions with 100rel). If a 180
Ringing response arrives after a 183 response has already been
processed, it does not make much sense to stop the early media streams
and go back to ringing. So now, once in the EARLY state, the call will
not go back to the …
=> 100rel improvements

.github/workflows/mingw.yml
Breaking changes
We will soon start the deprecation process for Windows 2019. While the image is being deprecated, you may experience longer queue times during peak usage hours. Deprecation will begin on 2025-06-01 and the image will be fully unsupported by 2025-06-30.
=> ci: update mingw.yml

docs/examples/config, modules/menu/menu.c, src/config.c
Gives the user the option to play an audio file when the call closes. This is a common way in many phones to provide the user an additional audio feedback when a call is terminated.
The new config option is called 'hangup_aufile' and is set to 'none' per default. Meaning there is no playback on hangup unless the user specifies a file.
=> menu: Add hangup sound on closed calls

modules/srtp/srtp.c
`Format: "srtp: srtp_tx not ready (%m<-- SIZE ERROR`
=> srtp: fix size err printf

include/baresip.h, modules/ctrl_dbus/ctrl_dbus.c, modules/ctrl_tcp/ctrl_tcp.c, modules/echo/echo.c, modules/gtk/gtk_mod.c, modules/menu/menu.c, modules/mqtt/publish.c, modules/mwi/mwi.c, modules/presence/presence.c, modules/presence/publisher.c, modules/rtcpsummary/rtcpsummary.c, modules/serreg/serreg.c, modules/vumeter/vumeter.c, src/bevent.c, src/call.c, src/reg.c, src/ua.c, src/uag.c, test/bevent.c, test/call.c, test/ua.c
- **bevent: rename enum ua_event without breaking API**
It would be really nice if we could rename the enum. But we should not break the API.
The backwards compatibility code is somehow complicated, but can be removed after a while (again one year?).
Is there a better solution? Or should we do without it?
=> enum ua event rename

src/call.c
Currently it is possible that for H.264 SPS+PPS are missed at the decoder side.
Suppose that UA a calls UA b:
- INVITE a -> b
- 200 Answering b -> a
- ACK a ->b
Details for UA a:
`re/src/sipsess/connect.c: invite_resp_handler() -> sess->answerh()
sipsess_answer_handler --> update_media --> ... --> video_update--> video_encoder_set() + video_start_source()`
The 200 Ok enables the encoder.
Details for UA b:
`sipsess/listen.c: request_handler() gets ACK -> ack_handler() -> sipsess_estab_handler() -> update_streams()`
The ACK enables the decoder.
Thus, it is possible that the first RTP packet arrives before the decoder is ready. We observed this sporadically on our ARM devices.
RFC 3264 Section 6.1
```
Once the answerer has sent the answer, it MUST be prepared to receive
  media for any …
```
=> call: prepare to receive video immediately with 200 Ok

modules/in_band_dtmf/in_band_dtmf.c
With arm gcc cross compiler there was a warning
```
src/baresip/modules/in_band_dtmf/in_band_dtmf.c:173:44: warning: cast increases required alignment of target type [-Wcast-align]
173 |         struct in_band_dtmf_filt_dec *sf = (struct in_band_dtmf_filt_dec *)st;
|
```
=> in_band_dtmf: fix cross compiler alignment warning

src/account.c, src/call.c, src/stunuri.c, src/ua.c, test/account.c, test/sip/location.c
The password field in RFC 3986 is deprecated, this is a proposal to remove
the `struct pl password` field from `struct uri`.
Two PRs for baresip and libre have to be merged at the same time.
required PR: https://github.com/baresip/re/pull/1382
=> uri: remove password field

packaging/libbaresip.pc.in
Because of a typo in the `packaging/libbaresip.pc.in` file the libdir for baresip package is not set correctly. This brings issues using baresip in CMake when it's not installed to system paths but to local paths.
=> package: Fix not working libdir

.github/workflows/windows.yml
The installation of OpenSSL using choco on Windows is currently broken.
The proper solution is to use the builtin OpenSSL that comes with the Windows image.
This should be upgraded to 3.5.x some time on October.
Suggesting using a fixed version for now as a temp solution.
=> ci: temporary workaround for choco openssl failure

src/play.c
The audio path for baresip_player() was never set to the existing config
setting.
=> play: set audio path to config

src/config.c
`audio_jitter_buffer_delay` is replaced by `audio_jitter_buffer_ms` and `audio_jitter_buffer_size`
`video_jitter_buffer_delay` is replaced by `video_jitter_buffer_ms` and `video_jitter_buffer_size`
`audio_jitter_buffer_ms` - defines min./max. audio buffer delay in milliseconds (default 100-200ms)
`audio_jitter_buffer_size` - defines max. buffer size in packages (default 50, is pre-allocated)
`video_jitter_buffer_ms` - defines min./max buffer delay in milliseconds (default 100-200ms)
`video_jitter_buffer_size` - defines max. buffer size in packages (default 250, is pre-allocated)
=> config: fix video_jitter_buffer_size and add deprecation warnings

src/ua.c
If the dial URI was `sip:b@127.0.0.1:54940;transport=udp` and the account AOR
URI contains `;transport=tcp`, then the result was
```
sip:b@127.0.0.1:54940;transport=udp;transport=tcp
```
This commit fixes the already existing helper function `append_params()`.
=> ua: avoid duplicates of URI params

test/call.c, test/main.c, test/sip/sipsrv.c, test/test.h
This PR adds stateless proxy to test/sip/sipsrv that up to now only had
registrar features.
Futher adds positive and negative test for UA selection. Thus it is also tested
if - so called - spam calls are rejected.
- **test: sipsrv - SIP message forwarding**
- **test: call - add test_call_uag_find_msg()**
- **test: registered UA rejects peer-to-peer calls**
=> test: add test_uag_find_msg()

modules/avfilter/filter.c
With ffmpeg 8.0 `av_opt_set_int_list` is deprecated
=> avfilter: fix av_opt_set_int_list deprecation warning
