modules/gtk/gtk_mod.c

Attempt to fix OpenBSD 5.7 gtk module compile errors

---

modules/daala/decode.c
modules/daala/encode.c

Use `daala_packet` structure instead.

daala: upstream doesn't have ogg_packet structure any more

---

.gitignore
Makefile

Adding pkg-config support similar to what is now in libre and librem.

Adding pkg-config support to libbaresip for the shared lib.

---

modules/echo/echo.c
modules/echo/module.mk

Hi Alfred,
this module is a proof of concept for making concurrent and independent echo calls possible. Very helpful for testing. At the moment I have no way to test vidbridge, but this could be implemented really fast. Its a modified version of the b2bua module and requires aubridge.

Multi Call Echo Module - Experimental

---

modules/gtk/gtk_mod.c

Fix build of gtk module with USE_LIBNOTIFY. Also add new calls to the menu even if notifications are disabled.

Fix notification-related things

---

modules/mpa/encode.c
modules/mpa/mpa.c

Bug at stereo wih 16 and 24k

---

mk/modules.mk

this should work for issue https://github.com/alfredh/baresip/issues/192

add test for sndfile on *BSD.

---

modules/avformat/avformat.c

avformat: improve video_fps handling

---

mk/modules.mk

This appeared to be missing. Also updated the copyright date to 2017.

Update to include JACK Audio Driver

---

modules/omx/module.c
modules/omx/omx.c

I discovered some compile erros while trying stuff again back on the Raspi.
Also i fixed a problem with VP 8codec, related to YUV padding the old conversion code.

Fixed some problems on OMX/RaspberryPi

---

modules/srtp/srtp.c
src/call.c

this is a fix for:
https://github.com/alfredh/baresip/issues/229

attempt to fix SRTP for early-media (ref #229)

---

modules/gst_video1/encode.c

Tune x264enc for low latency...

gst_video1: Fix latency issues

---

modules/zrtp/zrtp.c

non-RTP packets such as STUN, TURN, ICE might be shared on the
same UDP socket, and these packets should not be processed by ZRTP.
ref #262 
@juha-h please review and merge to master if OK.

zrtp: check for RTP packet in send handler

---

include/baresip.h
modules/presence/subscriber.c
src/contact.c

Preliminary work for avahi/Zeroconf support

Presence: Handle contacts added at run-time

---

modules/opensles/recorder.c
modules/zrtp/zrtp.c

- if there is more than one channel, use SL_SPEAKER_FRONT_LEFT |
SL_SPEAKER_FRONT_RIGHT speakers

modules/opensles: fix recorder speaker setup

---

modules/zrtp/zrtp.c

Incoming RTCP packet's encrypt-flag is checked in libzrtp.

modules/zrtp: encrypt/decrypt RTCP packets

---

modules/pulse/recorder.c

I've found that sometimes pa_simple_read() gets some garbage from my USB camera before 'real' samples arrive. This introduces an extra audio delay when calling baresip->baresip because a batch of packets (with real timestamps) is inserted at the beginning of the RTP stream. It happens randomly, usually after fast re-dials, and only when the USB camera's microphone is used (built-in analog input works fine). ALSA is not affected by this issue.
I propose a simple workaround for such cases which measures the time spent in pa_simple_read() and compares it to ptime.
Though, it's more a pulseaudio/driver issue, this workaround can be very helpful. In my case it dropped up to 50 packets (= 1 sec delay).

pulse: remove garbage at the beginning of a recording

---

modules/gzrtp/stream.cpp
modules/gzrtp/stream.h

It can be called from another thread (audio/video read).

modules/gzrtp: make send handler thread-safe

---

mk/modules.mk
src/config.c

minor PR w/ conditional inclusion of mqtt module dependent on mosquitto.h (libmosquitto-dev)

Make + Config entry for MQTT module

---

include/baresip.h
mk/modules.mk
modules/amr/amr.c
modules/auloop/auloop.c
modules/bv32/bv32.c
modules/codec2/codec2.c
modules/g711/g711.c
modules/g722/g722.c
modules/g7221/decode.c
modules/g7221/encode.c
modules/g7221/g7221.h
modules/g726/g726.c
modules/gsm/gsm.c
modules/l16/l16.c
modules/mpa/decode.c
modules/mpa/encode.c
modules/mpa/mpa.h
modules/opus/decode.c
modules/opus/encode.c
modules/opus/opus.c
modules/opus/opus.h
src/audio.c
test/mock/mock_aucodec.c

This PR merges the 2 different aucodec encode/encode_fmt functions into
one, where the audio sample format is added (int fmt).
Please help to review the API changes and test the code!

Aucodec sample format

---

mk/mod.mk

add CPPFLAGS to the makerules for C++ files.
See this issue:
https://github.com/creytiv/re/issues/134

mk: add CPPFLAGS to mod.mk

---

include/baresip.h
modules/dtls_srtp/dtls_srtp.c
modules/gzrtp/gzrtp.cpp
modules/zrtp/zrtp.c
src/call.c
src/event.c
src/ua.c

This replaces the original pull request which got conflicts and had also zrtp command changes.

added menc event

---

modules/ctrl_tcp/netstring/netstring.c
modules/ctrl_tcp/netstring/netstring.h

https://github.com/alfredh/baresip/issues/393

ctrl_tcp: add netstring files licensing

---

modules/dtls_srtp/dtls_srtp.c

Should also media name, RTP|RTPC, and profile name be included as parameter?

notify application when DTLS-SRTP is complete

---

modules/menu/menu.c

Using vidsrc driver,device to change video source during call.

video switch command added to menu module.

---

modules/menu/menu.c
src/baresip.c

This is the only way have found to send a conference call PIN from an http interface.

Send DTMF code command

---

include/baresip.h
modules/menu/menu.c
modules/pulse/player.c
modules/pulse/pulse.c
modules/pulse/pulse.h
modules/pulse/recorder.c
src/auplay.c
src/ausrc.c

- set_available_devices implementation in pulse module
- check audio player/source devices availability in switch_audio_player/source
Tested on ubuntu 16.04.

Add dev_list to auplay and ausrc struct

---

modules/mwi/mwi.c
src/ua.c

- made sure that ua_stop_all stops all UAs
- enhanced UA_EVENT_SHUTDOWN info message in mwi module

created ua_stop_all branch

---

modules/v4l2_codec/v4l2_codec.c

from a user:
"Also you need to be using poll. Epoll doesn't work."
reference #554

v4l2_codec: use thread instead of fd event

---

modules/avcodec/decode.c
modules/avcodec/encode.c
modules/avformat/avformat.c

this PR removes support for some old versions of ffmpeg.
I suggest we support ffmpeg version 2.8 and later
Please state here if you disagree or agree :)

Ffmpeg versions

---

modules/coreaudio/recorder.c

this PR removes a blocking calling to `usleep`.
tested on OSX 10.12

coreaudio: remove blocking sleep

---

modules/opengles/module.mk
modules/opengles/opengles.c

Added GL_GLEXT_PROTOTYPES CFLAGS define so that functions are found in header file.
Changed include file path.

opengles android ndk r18 update

---

Makefile
include/baresip.h
mk/Doxyfile
mk/modules.mk
mk/win32/baresip.vcxproj
modules/menu/menu.c
src/account.c
src/call.c
src/conf.c
src/config.c
src/event.c
src/srcs.mk
test/call.c
test/main.c
test/srcs.mk
test/test.h

the purpose of this is to make the code more clean and readable.

remove USE_VIDEO compile flag

---

modules/debug_cmd/debug_cmd.c

Added a command that prints the UUID
@alfredh What do you think about this?

Added debug cmd to print UUID

---

mk/modules.mk
modules/opus_multistream/decode.c
modules/opus_multistream/encode.c
modules/opus_multistream/module.mk
modules/opus_multistream/opus_multistream.c
modules/opus_multistream/opus_multistream.h
modules/opus_multistream/sdp.c
src/config.c

this patch is based on work from Tony Langley:
https://github.com/alfredh/baresip/pull/649

Opus multistream

---

modules/l16/l16.c

Not shure about the pt value yet as it has to be assigned from dynamic range.

Add 48 khz sampling rate support

---

modules/mpa/mpa.c

As seen from all other tested UAs

Interop: Parameters reordering and whitespace removal

---

modules/opus/opus.c

opus_sprop_stereo has value 'no'.

 Use opus in mono mode (opus/48000/1) if opus_stereo or opus_sprop_stereo has value 'no'

---

modules/menu/menu.c

menu: add answermode command

---

modules/srtp/srtp.c

libre already had support, was just missing from baresip.

Add support for aes_256_gcm

---

src/contact.c
src/ua.c

Slightly improves human and machine readability by using a more common list output formating for UAs, Active calls and Contacts

More common list format

---

mk/modules.mk
modules/mpa/encode.c
modules/mpa/module.mk
modules/mpa/mpa.c
modules/mpa/sdp.c

Fixes https://github.com/alfredh/baresip/issues/840
Maybe needs some love.
Working for me but please feel free to cleanup or improve.

MPA L2 and L3 encoding

---

mk/modules.mk
modules/aptx/aptx.c
modules/aptx/aptx.h
modules/aptx/decode.c
modules/aptx/encode.c
modules/aptx/module.mk
modules/aptx/sdp.c

libopenaptx
https://github.com/pali/libopenaptx/
Supports aptX and aptX HD variants

aptX audio codec module

---

modules/dtls_srtp/dtls_srtp.c

Tested with the Cloud Softphone Android App (Acrobits).

dtls_srtp: add support for AEAD_AES_128_GCM and AEAD_AES_256_GCM

---

modules/ebuacip/ebuacip.c

it's working fine with ebuacip module. 
I changed loglevel to debug for incoming events.

changed loglevel to debug.

---

include/baresip.h
modules/debug_cmd/debug_cmd.c
modules/menu/menu.c
src/play.c
test/play.c

This is an attempt to address #934, and I encountered the "call waiting" discrepancy while I was at it. Thanks!

Fix ringback and call waiting sounds coming from alert device

---

modules/coreaudio/coreaudio.c

This became apparent when using a bluetooth headset. As soon as its
devicename was listed loading the module started to fail.
According to the CFStringGetCStringPtr documentation it is normal for
the function to fail in some cases. Using CFStringGetCString as a backup
is recommended.
Might also be the reason for https://github.com/alfredh/baresip/issues/914.

coreaudio: Fallback to CFStringGetCString when CFStringGetCStringPtr fails

---

src/event.c

Get peerdisplayname when available.

PeerDisplayName

---

modules/mqtt/README.md

MQTT example updated with peerdisplayname field - README

added MQTT example with peerdisplayname

---

include/baresip.h
modules/mqtt/publish.c
src/audio.c
src/event.c

When reporting VU RX values the current audio buffer size in ms is also included.

Aubuf current jb value to mqtt

---

include/baresip.h
modules/b2bua/b2bua.c
modules/echo/echo.c
modules/gtk/gtk_mod.c
modules/menu/menu.c
src/call.c
src/ua.c
test/call.c

Tried to preserve backwards compatibility.

Added vidmode param to call_answer(), ua_answer() and ua_hold_answer() functions

---

modules/gtk/gtk_mod.c

This pull request would close issue https://github.com/baresip/baresip/issues/1002.

show call_peername in notify title

---

docs/THANKS

Attributes for (at least) references: #1006, #1010 and #1012

Update THANKS file

---

docs/ChangeLog

Discovered by Robert-André Mauchin during [package review for Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1843279#c1)

Convert ChangeLog to UTF-8 (to match THANKS file)

---

modules/jack/jack_play.c
modules/jack/jack_src.c
src/call.c

1. Implemented request/issue#1020, allowing jack client name to be specified in the config file.
2. Added the call line number to the call.c "answering" info report, for easy use in my application.

Issue #1020 feature implementation, and call.c change to report line number.

---

.travis.yml
modules/debug_cmd/debug_cmd.c

Add travis OpenSSL/LibreSSL Checks and fix no-deprecated

---

debian/changelog

Added 1.0.0 entry to debian changelog

New version 1.0.0

---

src/reg.c
src/ua.c

Request to merge Alfred's websocket patch to baresip for review and testing.

Alfred's sip websocket patch

---

.gitignore
mk/win32/baresip.vcxproj
mk/win32/baresip.vcxproj.filters
mk/win32/dirent.h
src/config.c
src/main.c

Added missing files.
Removed HAVE_GETOPT define.
Added dirent.h, since it's not present on windows.
Updated .gitignore to exclude visual studio build files.

Updating .vcxproj file for windows builds

---

include/baresip.h
modules/avcodec/decode.c
src/h264.c
test/h264.c
test/main.c
test/srcs.mk
test/test.h

h264 cleanup

---

include/baresip.h
src/event.c
src/ua.c

- the event subsystem should be generic and not specific to ua.

event: move code from ua.c

---

include/baresip.h
modules/menu/menu.c
src/call.c
src/core.h
src/stream.c

Implementation of a new command to accept a call. This acceptdir command is designed such that the user controls the media stream directions via arguments of the command.

Cmd acceptdir

---

.github/workflows/build.yml
.github/workflows/ssl.yml
.github/workflows/valgrind.yml

This PR adds dependency checkouts. The only requirement is that the github pr title of the dependent pull requests must be the same.
I added a custom action: https://github.com/sreimers/pr-dependency-action/blob/main/action.yml

ci: add pull request dependency checkouts

---

modules/alsa/alsa_play.c

fix freeze on hangup (#1135)

---

modules/gst/gst.c

Some fixes and allowing files as input for modules/gst. This makes modules/gst ready for playing tones with play.c https://github.com/baresip/baresip/pull/1147.

gst ready for file play

---

include/baresip.h
src/call.c
src/core.h
src/video.c

A suggestion how #1142 could be solved only for the video part.
exclusive the NAT topic.

video: move video related start/stop/update into video file

---

include/baresip.h
src/video.c

Need to be able to stop video display when baresip app is paused and becomes unvisible

Expose video_stop_display() to API

---

.github/workflows/build.yml
modules/aac/module.mk

Needs `mixausrc` fixes like here: https://github.com/baresip/baresip/pull/1170

Make macos warnings into errors

---

include/baresip.h
src/call.c
src/video.c

when video source is stopped in order to solve issue https://github.com/baresip/baresip/issues/1169.

Added ctx param to video_stop/video_stop_source and set ctx to null

---

modules/gst/gst.c

The error handler call for end of stream is now triggered from the re_main thread (Similar to the aufile implementation). This should avoid a deadlock situation calling _pthread_join_ in the _gst_destructor_ .

gst: fix bus error

---

src/call.c

Add support for gigaset and yealink.

call: extend SIP auto answer support for incoming calls

---

src/message.c

baresip sends a reply for a SIP MESSAGE for each message listener.
How often we process a SIP MESSAGE is not interesting for the remote who sent the MESSAGE. In our case “menu” prints the message and ctrl_tcp forwards the message.

message: reply only once

---

docs/examples/config
include/baresip.h
modules/menu/dynamic_menu.c
modules/menu/menu.c
modules/menu/menu.h
modules/menu/static_menu.c
src/config.c
src/ua.c

Get rid of the current UA which was used for dialing and also for answer call, hangup.
Instead menu holds the id of the active call.
TODO: For dialing an automatic UA selection will be implemented.

Remove uag next

---

modules/opensles/player.c
modules/opensles/recorder.c
src/audio.c

Hope parenthesis went according to style rules.

Avoid compiler warnings using casts

---

modules/menu/static_menu.c

a new hangup command to hangup all calls 
hangupall wihtout parameter or dir=all, close all calls
hangupall dir=in, hangup all incoming calls in any state
hangupall dir=out, hangup all outgoing calls in any state

menu: new hangupall command with direction parameter

---

modules/menu/static_menu.c

A wrong filter function was used to hangup all outgoing calls.
When multiple outgoing calls are started to different peers, the first who
answers the call wins. Then we want to hangup all other outgoing calls. The
application can do this by invoking:
```
hangupall dir=out
```
or simpler
```
hangupall out
```
The flag call->outgoing also includes the established call. Correct is to use
call_state() for the filter.

menu: correct hangupall command for parallel call feature

---

src/audio.c

src/audio: set started false with audio_stop

---

include/baresip.h
modules/menu/dynamic_menu.c
src/ua.c

this is a proposal to remove previous call hold
it is not clear if this is a useful feature, or if anyone is using it

ua: remove prev call

---

src/audio.c

Solves the dead lock issue #1324.

audio: prevent restart of rx_thread on call termination

---

modules/gst/gst.c

This PR removes the use of GMainLoop in module gst.
The module ctrl_dbus instantiates also a GMainLoop which might result in problems like dead-lock. We observed a dead-lock during stop of ring tone.

gst: Use GstBus sync handler instead of GMainLoop

---

modules/menu/static_menu.c

This PR depends on libre PR: https://github.com/baresip/re/pull/94

menu: print useful responses for tlsissuer and tlssubject (#1357)

---

src/ua.c

Fixes #1375.
@juha-h Please could you try your test call with this?

ua: less restrictions for local account in uag_find_requri() (#1375)

---

src/audio.c

audio: prevent potential mutex deadlock (#1381)

---

modules/multicast/receiver.c

Use unified format for events from multicast module.

multicast: use module_event() for sending events

---

.github/workflows/tools.yml
tools/fritzbox2baresip

As mentioned in #1370, I'm hereby proposing my simple converter for the newly introduced `tools` directory.

Convert FRITZ!Box XML phone book into Baresip contacts

---

modules/jack/jack_play.c

For busy tones and menu command "/play" the normal resample/reformat routine in src/audio.c is not used, therefore these commands do not work with jack since the files (busy.wav for example) are s16 and jack normally needs floats. This PR fixes that and allows jack playback to receive s16 directly; it can resample (up/down) and convert to floats. 
I have tried this with mono and stereo files in 2, 8, 16, 48, 96, 192 kHz files with valgrind without errors. (jack server running at 48kHz)

Support for s16 playback in jack. Needed for play tones

---

docs/examples/config
include/baresip.h
src/config.c
src/stream.c
src/ua.c

Allows to configure ToS differently for RTP video/audio and SIP
Was not sure which default value we should use for SIP.

ToS for video and sip

---

src/core.h
src/srcs.mk
src/ua.c
src/uag.c

- uag.c contains code for User-Agent Group. E.g. functions that operate on the
list of User-Agents.
- ua.c contains code for User-Agent. E.g. functions that operate on one User-
Agent.

ua,uag: split ua.c and uag.c

---

docs/examples/config
include/baresip.h
modules/avcodec/avcodec.c
modules/avcodec/avcodec.h
modules/avcodec/encode.c
modules/avcodec/sdp.c
modules/avformat/avformat.c
modules/avformat/mod_avformat.h
modules/avformat/video.c
src/config.c
src/video.c

original patch by:
*     Media Magic Technologies <developer@mediamagictechnologies.com>
*     and Divus GmbH <developer@divus.eu>
https://github.com/baresip/baresip/pull/1390
the patch was trimmed and improved by me.

video passthrough

---

modules/menu/menu.c
modules/menu/static_menu.c

add `/uareg` command register/unregister useragent.
examples:
```
/uareg 0
sip:alfredh@sip.antisip.com: selected for request
unregistering sip:alfredh@sip.antisip.com
...
/uareg 300
sip:alfredh@sip.antisip.com: selected for request
registering sip:alfredh@sip.antisip.com with interval 300 seconds
alfredh@sip.antisip.com: (prio 0) {0/TCP/v4} 200 OK (kamailio (5.4.4 (x86_64/linux))) [1 binding]
```
@jose1711

menu: add command /uareg

---

README.md

as suggested by https://github.com/znoteer

Update README.md with configuration suggestion

---

modules/serreg/serreg.c

If no User-Agent could register successfully the registration of prio 0
accounts is restarted. This commit prevents very fast restarts by means of a
timer.

serreg: use a timer for registration restart

---

modules/ctrl_dbus/module.mk

This could be a solution to fix #1447.
Opened for discussion.

ctrl dbus makefile depends

---

modules/vidbridge/disp.c

vidbridge: check vidbridge_disp_display args fixes segfault

---

modules/ausine/ausine.c

support for multiple samplerates.
@sreimers what do you think ?

ausine: support for multiple samplerates

---

Makefile

Depends on https://github.com/baresip/re/pull/107 and https://github.com/baresip/rem/pull/10

pkg-config version check

---

Makefile

similar for rem: https://github.com/baresip/rem/pull/11

mk: support more locations for libre.pc and librem.pc

---

src/audio.c

audio: fix aufilt_setup update handling

---

src/config.c

resolves https://github.com/baresip/baresip/issues/1508

config: not all audio config was printed

---

Makefile
src/net.c

net_if_getname supports IPv6 now: https://github.com/baresip/re/commit/7bab565aa012bfda32abbfd8bd304e04c7e50730

net: replace network_if_getname with net_if_getname

---

modules/turn/turn.c

add support for TURN over TCP/TLS
this can be enabled with:
```
medianat=turn;stunserver="turn:turnserver.net?transport=tcp";stunuser=USERNAME;stunpass=PASSWORD
```
```
medianat=turn;stunserver="turns:turnserver.net?transport=tcp";stunuser=USERNAME;stunpass=PASSWORD
```

turn: add TCP and TLS transports

---

src/event.c

If module event contains larger formatted arguments (for example a SDP response)
256 bytes is not enough. This commit increases the limit to 4096 bytes.

event: increase module_event buffer size

---

Makefile

../re/libre.pc and ../rem/librem.pc should checked first.

Makefile dependency check improvements

---

src/ua.c

Reduce the number of unimportant info messages 
According to issue #1546

ua: downgrade level of message "ua: using best effort AF"

---

src/audio.c

audio: changed log level for ausrc error handler messages

---

src/uag.c

based on https://github.com/baresip/re/pull/131

SIP default protocol

---

modules/multicast/multicast.c

multicast: fix coverity scan

---

modules/ctrl_dbus/ctrl_dbus.c
modules/ctrl_tcp/ctrl_tcp.c
modules/menu/menu.c
test/event.c
test/test.h

depends on https://github.com/baresip/re/pull/130

odict: hide struct odict_entry

---

modules/ctrl_dbus/ctrl_dbus.c

Found this issue during discussion: https://github.com/baresip/re/discussions/139

ctrl_dbus: use mqueue to trigger processing of command in remain thread

---

modules/serreg/serreg.c

Use the failwait() and fail counter like re/src/sipreg does.

serreg: do not ignore returned errors of ua_register()

---

README.md
include/baresip.h
src/audio.c
src/bundle.c
src/call.c
src/config.c
src/core.h
src/srcs.mk
src/stream.c
src/video.c
test/call.c
test/main.c
test/test.h

https://datatracker.ietf.org/doc/html/rfc8843
Add support for multiplexing audio/video over the same RTP/RTCP transport.
Please review and test

Bundle media mux

---

modules/netroam/module.mk
modules/netroam/netlink.c
modules/netroam/netlink.h
modules/netroam/netroam.c

This works for OS linux. See: man netlink

netroam: add netlink immediate network change detection

---

src/audio.c

fix helgrind warning:
```
[ RUN      ] test_call_dtmf
==268477== ---Thread-Announcement------------------------------------------
==268477== 
==268477== Thread #5 was created
==268477==    at 0x4A34DDE: clone (clone.S:71)
==268477==    by 0x4908D7B: create_thread.constprop.0 (createthread.c:101)
==268477==    by 0x490A68D: pthread_create@@GLIBC_2.2.5 (pthread_create.c:817)
==268477==    by 0x483F677: pthread_create_WRK (hg_intercepts.c:425)
==268477==    by 0x4852A30: alloc_handler (ausine.c:248)
==268477==    by 0x13B2D7: ausrc_alloc (ausrc.c:108)
==268477==    by 0x139758: start_source (audio.c:1824)
==268477==    by 0x139945: audio_start (audio.c:1897)
==268477==    by 0x139D28: audio_encoder_set (audio.c:2053)
==268477==    by 0x13CC00: update_audio (call.c:316)
==268477==    by …
```

audio: add lock

---

src/ua.c

- For registrar-less accounts: If the dial URI of an outgoing call is an IP address, we want to select a local address with route to the destination. Note: Nothing changes for cases where the dial URI is a domain name.
- For registrar accounts: Use laddr of registration for SDP.

ua: select proper af and laddr for outgoing IP calls

---

modules/menu/menu.c

menu: start ringback tone also by 183 Session Progress

menu ringback session progress

---

modules/netroam/netroam.c

- adds a fail counter
- adds an event an external application may use to decide if baresip should be
restarted

netroam: add fail counter and event

---

modules/menu/menu.c

When placing a call I expect to hear the ringing sound in the headset
(play device) but not in the alert device.
This provides a fix similar to #934 (which was initially fixed in
99487e221d0f8af1994769c9b6df34fe6eccb580). However, this fix was
basically reverted in 3bd44f1c95f464af66820dda242b2a2de1e0fc03 when
the menu_play helper was introduced.

menu: Play ringback in play device

---

modules/ice/ice.c

depends on https://github.com/baresip/re/pull/147

ice: remove ice_mode

---

src/audio.c

not a big problem but a first fix for warnings detected by the clang ThreadSanitizer (-fsanitize=thread)

Fixing clang ThreadSanitizer warnings

---

modules/multicast/receiver.c

+ removed a few bools and add a state enum instead
+ priority and state handling is moved completely into the prio handler
+ the timeout handler now detects EOS
+ disabling a receiving receiver does not trigger a timeout anymore
+ the main behavior between mc-mc and mc-calls is not changed

mc: new priority handling with multicast state

---

src/call.c

Needs https://github.com/baresip/re/pull/252

Allow hanging up call that has not been ACKed yet

---

include/baresip.h
modules/menu/dynamic_menu.c
src/call.c

Added new API function `call_supported()` and used it in menu module `atransferstart` command

Added new API function call_supported() and used it in menu module

---

modules/menu/static_menu.c

Allow to add/remove a custom header to e.g. INVITE.
Found also this feature request: https://github.com/baresip/baresip/issues/230

menu: support custom SIP headers

---

modules/menu/dynamic_menu.c
modules/menu/menu.c
modules/menu/static_menu.c

menu: use new sdp_dir_decode

---

include/baresip.h
src/call.c

The new function `call_progress_dir()` is used in https://github.com/baresip/baresip-apps/pull/12.

intercom: add video preview call

---

docs/examples/config
include/baresip.h
modules/multicast/player.c
src/audio.c
src/config.c

- config,audio: add config setting for silence audio level
- multicast: set silence audio level of aubuf

multicast set aubuf silence

---

src/audio.c

And we may need locks around all tx->ts_ext too ?

audio: missing lock around stream_send

---

include/baresip.h
src/conf.c

return the extension of a filename:
readme.txt -> "txt"
index.html -> "html"

conf: add fs_file_extension()

---

modules/pulse/player.c
modules/pulse/recorder.c

E.g. this lead to fail multicast playback after pulseaudio restarts.

pulse: support restart of pulseaudio during stream

---

modules/multicast/multicast.c
modules/multicast/multicast.h
modules/multicast/player.c
modules/multicast/receiver.c

- multicast: bad playback quality after unmute
- fadein/fadeout fixes of crackly audio artefacts

mulitcast unmute bad quality

---

modules/multicast/receiver.c

Reducing jitter buffer for low latency did not work.

multicast: support error code EAGAIN of jbuf_get()

---

mk/modules.mk

mk/modules: fix omx RPI detection

---

src/audio.c

struct members are read/written by 2 different threads, without locking.
fixes this helgrind warning:
```
alfredh@debian:~/tmp/baresip$ valgrind --tool=helgrind ./selftest test_call_aufilt 
==132353== Helgrind, a thread error detector
==132353== Copyright (C) 2007-2017, and GNU GPL'd, by OpenWorks LLP et al.
==132353== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==132353== Command: ./selftest test_call_aufilt
==132353== 
running baresip selftest version 2.3.0 with 1 tests
[ RUN      ] test_call_aufilt
==132353== ---Thread-Announcement------------------------------------------
==132353== 
==132353== Thread #2 was created
==132353==    at 0x4A48DDE: clone (clone.S:71)
==132353==    by 0x491CD7B: create_thread.constprop.0 (createthread.c:101)
==132353==    by …
```

audio: add more locking

---

modules/ice/ice.c

ice: fix local prio calculation

---

modules/dtls_srtp/dtls_srtp.c

Found while looking into the source code for #1869

dtls_srtp: Minor whitespace fix

---

modules/multicast/receiver.c

after this all usage of "struct lock" has been converted to C11 mutex.
what is left:
- couple of places in rem
- couple of places in re
convert also these to C11 mutex, then re "lock" module can be phased out

multicast: C11 mutex

---

mk/modules.mk
modules/pulse_async/module.mk
modules/pulse_async/pastream.c
modules/pulse_async/player.c
modules/pulse_async/pulse.c
modules/pulse_async/pulse.h
modules/pulse_async/recorder.c

A new pulseaudio module taking advantage of the asynchronous interface of pulseaudio.

Pulseaudio Async Interface Module

---

src/ua.c

Also, had to change location of `create_register_clients` and `add_extension` functions.

In start_registering, create register clients if reg list is empty

---

modules/ctrl_dbus/ctrl_dbus.c

- ctrl_dbus: add check to cnd_wait to support spurious wakeups
- ctrl_dbus: call module_event() in main thread

ctrl_dbus send event in main thread

---

src/call.c

Revert PR #1922 due to serious issues with early media and perhaps something else too.

Revert PR #1922

---

CMakeLists.txt
modules/fakevideo/CMakeLists.txt
modules/g711/CMakeLists.txt

for #1971 
small contribution :)
I'll add more as soon as I have free time.

Modules cmake

---

modules/avformat/audio.c

avformat: fix ffmpeg channel_layout deprecation

---

modules/aufile/aufile_src.c
modules/gst/gst.c
src/play.c

- aufile: use aubuf_read_auframe()
- play: use new aubuf API and don't start auplay too early

play: ring tone fixes if file_ausrc is set

---

modules/gzrtp/stream.cpp

- generate also MENC_EVENT_PEER_VERIFIED when peer has already been verified
- fixed typo in MENC_EVENT_VERIFY_REQUEST argument

Generate also MENC_EVENT_PEER_VERIFIED event

---

test/call.c
test/main.c
test/test.h

test/call: Add test_call_change_videodir

---

src/call.c

In `sipsess_estab_handler` the re-INVITE to the peer to set the correct established media directions was called before the ua event handlers had been called. Since modifying the call can lead to more events being generated, those events would be triggered before the call established event which could lead to problems. Now, the call modification is done after the UA event handlers have been executed.

call: send reinvite after established handlers

---

modules/gtk/gtk_mod.c
modules/menu/static_menu.c

Fixes a few potential memory leaks in functions calling account_uri_complete.

gtk & menu: Fix potential memory leaks

---

CMakeLists.txt

cmake: Add options -DDEFAULT_CAFILE="…" and -DDEFAULT_AUDIO_DEVICE="…"

---

CMakeLists.txt

cmake: add ABI (soname) versioning

---

docs/examples/accounts
modules/account/account.c
modules/contact/contact.c
modules/dtls_srtp/dtls_srtp.c
modules/srtp/srtp.c

- RFC 2606 (Reserved Top Level DNS Names)
- RFC 3849 (IPv6 Address Prefix Reserved for Documentation)
- RFC 5737 (IPv4 Address Blocks Reserved for Documentation)

misc: Use example domains and IPs

---

CMakeLists.txt

cmake: symlink modules

---

src/call.c

call: fix mnat call_streams_alloc

---

modules/selfview/selfview.c

this fixes issues in sdl with starting timer
from wrong thread

selfview: create window in encode_update

---

include/baresip.h
modules/menu/static_menu.c
src/account.c
src/uag.c

- Introduce two new functions `account_uri_complete_strdup()` and `uag_find_requri_pl()`.
- These allow to simplify the code in `modules/menu/static_menu.c`.

menu: simplify URI complete

---

modules/gtk/gtk_mod.c

gtk: use new function account_uri_complete_strdup()

---

modules/sdl/sdl.c

Recommended by: https://wiki.libsdl.org/SDL_VideoInit

sdl: small improvements

---

modules/avcodec/decode.c
modules/avcodec/encode.c
modules/avformat/video.c
modules/swscale/swscale.c
modules/vidinfo/vidinfo.c

Depends on https://github.com/baresip/rem/pull/103

vid: add support for YUV422P pixel format

---

modules/ice/ice.c
src/config.c

depends on: https://github.com/baresip/re/pull/589

ice: local candidate policy config

---

modules/gtk/gtk_mod.c

Closes #2315 
Small fix of errors shown when closing baresip via GTK

fixes 2315 and GTK errors on quit

---

modules/aufile/aufile_src.c

aufile/src: add auframe support

---

src/ua.c
src/uag.c

- uag: support multiple TLS server certificates
- ua,uag: parameter of tls_add_certf() change to const char*

tls multiple server certs

---

test/ccheck.py

pylint gives around 90 warnings... this PR fixes some of them ...

ccheck: fix some pylint warnings

---

src/account.c

Bug was result of commit https://github.com/baresip/baresip/commit/77c5dcaeeddc9d0cad7e893d9ea6e099d69e4182.

Fixed account debug of mwi and call_transfer

---

CHANGELOG.md
CMakeLists.txt
LICENSE
README.md
debian/changelog
include/baresip.h
mk/Doxyfile

checklist: https://github.com/baresip/re/wiki/Release-Checklist

release v2.11.0

---

.github/workflows/build.yml
.github/workflows/cmake.yml
modules/av1/decode.c

- Add aom to CI
- Fix warnings in av1 module

av1: fix warnings

---

src/core.h
src/stream.c

stream: remove stream_decode from internal API

---

src/core.h
src/reg.c
src/ua.c

Trying to solve [this issue](https://github.com/baresip/baresip/issues/2450) in a simple way

ua: allow custom headers in sip REGISTER request

---

src/main.c

main: fix async init order (after config load)

---

modules/srtp/srtp.c
src/stream.c
src/video.c

video: add TX thread

---

src/call.c

Calls of `call_event_handler` were vulnerable to format string attacks in FROM headers which could lead to DOS attacks. This is now fixed.

call: Fix calls of call_event_handler

---

src/config.c

Similar to `net_interface`.  Possible values are `4` and `6`.

config: add net_af config setting

---

modules/av1/CMakeLists.txt
modules/sndfile/CMakeLists.txt
modules/x11/CMakeLists.txt

fix cmake modules

---

modules/multicast/receiver.c

In some situations the event when the incoming multicast stream stops was missing.

mc: send module event whenever receiver is stopped

---

modules/account/account.c

If OK, I would appreciate fast merge in order to get my Android app fixed.

account: increase line handler size to 1024 characters

---

src/audio.c
src/call.c

Parallel call memory issue: #2502 - Part 1

call,audio: respect SDP media dir on audio start similar to video

---

include/baresip.h
src/config.c
src/video.c

Paced sending like FFmpeg: https://ffmpeg.org/ffmpeg-protocols.html#udp
https://chromium.googlesource.com/external/webrtc/+/master/modules/pacing/g3doc/index.md

video: refactor paced and burst sending

---

src/video.c

video: fix possible 32bit overflow

---

src/uag.c

ua: deref call on reset_transp fail

---

.github/workflows/coverage.yml

Discussed in https://github.com/baresip/baresip/discussions/2548

ci: add coverage workflow

---

README.md

Hello, thank you for your project!
Is a silly contribution but I think could be useful to have some instruction in the readme to build the documentation.

Add instruction to build the doxygen docs

---

modules/aubridge/device.c

Also moves the check for auplay/ausrc compatibility before the thread start.
This avoids a memleak that occurs if the thread terminates without being
joined.

aubridge: use atomic for run flag

---

src/stream.c

stream: log last RTP packet debug after 100ms

---

modules/mixausrc/mixausrc.c

Fixes crackly audio during fading and simplifies fade algorithm.
+ remove existing calculation code of the fade (it produced unwanted crackly audio)
+ fade with a fixed delta. using a sweep reduces the calculation cost of the fade.
+ mixing the first frame, the audio buffer for the file is not ready yet. maintain down-faded audio volume

mixausrc: sweep fading for performance

---

src/account.c
src/stream.c

Could replace https://github.com/baresip/baresip/pull/2617

account,stream: natpinhole account parameter orthogonal to medianat

---

docs/examples/accounts
src/account.c

- default value in docs example
- add natpinhole to debug output of account

docs: update default value for natpinhole

---

src/audio.c

This PR makes the code for codec changes more readable and fixes #2612.
- encoder/decoder has to be updated as soon as the codec changes
- audio source/player, aubuf and filters have to be updated/flushed if the
samplerate or the number of channels change or the call was put on-hold
- always flush both filter lists, rx and tx for a correct AEC update
Note:
There are more code sections where only one of rx filters or tx filters are flushed. These are not touched by this PR.

audio: rework on codec changes

---

test/call.c

Adds logical AND. As first example replaces
```c
if (f->stop_on_rtcp && ag->peer->n_rtcp > 0)		
re_cancel();
```
in `event_handler()` by a cancel rule.

test: call - combine cancel rules with logical AND

---

modules/evdev/evdev.c
modules/mqtt/mqtt.c
modules/mqtt/mqtt.h
modules/netroam/netlink.c
modules/stdio/stdio.c

Depends on https://github.com/baresip/re/pull/805

main: fd_listen fhs alloc rewrite

---

include/baresip.h
modules/menu/static_menu.c
src/ua.c

ua, static_menu: Fix 100rel cmd

---

src/call.c

include Referred-by: in call_transfer and call_replace_transfer

call: include Referred-by: tag in REFERs

---

test/call.c
test/mock/mock_vidisp.c
test/test.h

- test: call - wait for three video frames in video test
- test: call - count video frames in videodir test

test: call - count video frames in videodir tests

---

test/call.c

- test: call - add cancel_rules_debug()
- test: call - reset all cancel rules and cancel only once

test call - fix logical and

---

include/baresip.h
src/call.c

call: add call_msg_src getter
Related:
- https://github.com/baresip/baresip-apps/pull/30

Implement OPTIONS ping

---

test/call.c

- test: call - beautify cancel rule debug output
- test: call - replace BEHAVIOUR_PROGRESS by answermode early
- test: call - check also value zero for counter
- further, re_main timeout of 5 seconds should be enough

test: call - improve tests for call progress

---

test/call.c
test/ua.c

This increases the coverage from 49.1% to 50%. :-)

test: activate RTP stats

---

modules/gtk/gtk_mod.c

gtk: close GTK on unsupported icon

---

src/audio.c
src/aureceiver.c
src/core.h

audio,aur: audio_set_player() only stops auplay

---

CMakeLists.txt

cmake: add RE_LIBS config and add atomic check

---

.github/workflows/build.yml
.github/workflows/coverage.yml
.github/workflows/lint.yml
.github/workflows/mingw.yml
.github/workflows/sanitizers.yml
.github/workflows/ssl.yml
.github/workflows/valgrind.yml

ci: use actions/checkout@v4

---

src/aureceiver.c

Solves https://github.com/baresip/baresip/issues/2856

aur: fix uninitialized warning in auplay handler

---

src/aureceiver.c

Fixes https://github.com/baresip/baresip/issues/2858

aur: set audio format correctly

---

src/call.c

fixes https://github.com/baresip/baresip/issues/2873

call: fix race condition for call_set_video_dir()

---

README.md

The diff should be pretty much self-explaining, I guess?

readme: cosmetic changes

---

modules/aufile/aufile_src.c

In case of very short live time of aufile the thread got started after the
destructor was called.
Also the `started` flag is only read/written from main thread and doesn't need
to be atomic.

aufile: avoid race condition in case of fast destruction

---

src/call.c

call: start streams in sipsess_estab_handler

---

modules/echo/echo.c

echo: fix re_snprintf pointer ARG

---

modules/netroam/CMakeLists.txt

netroam/cmake: add optional netlink detection

---

docs/examples/accounts
modules/account/account.c
src/account.c

account: set inreq_allowed=yes as default

---

src/play.c

- error handling for start_ausrc() and start_auplay()
- ensure that playback is stopped if ausrc reported eof but the audio buffer
is waiting for the wish size

play: err handling and ensure eof

---

src/audio.c

part 1 of https://github.com/baresip/baresip/pull/2991

audio: remove stop_aur()

---

include/baresip.h
src/audio.c

audio_update() should respect sdp_media disabled flag like video_update().
part 2 of: https://github.com/baresip/baresip/pull/2945

audio: respect SDP media disabled flag

---

src/uag.c

part 1 of DnD feature: https://github.com/baresip/baresip/pull/2979
The initializer of uag is not correct.

uag: fix initializer

---

.github/workflows/build.yml
.github/workflows/coverage.yml
.github/workflows/fedora.yml
.github/workflows/mingw.yml
.github/workflows/sanitizers.yml
.github/workflows/ssl.yml
.github/workflows/valgrind.yml

ci: bump pr dependency action

---

src/audio.c

Currently audio filters do not work.
Enc/Dec need to be setup first.

audio: fix setup of audio filters

---

src/uag.c

https://www.rfc-editor.org/rfc/rfc3261#section-8.2.1

uag: add Allow header to 405 SUBSCRIBE response

---

test/call.c

Fixes: https://github.com/baresip/baresip/issues/3066

test: call - reset max_calls to default value

---

.gitignore

Ignore local `.vscode` configurations.

Add .vscode to .gitignore (cosmetic change)

---

modules/pipewire/pipewire.c

Fixes: https://github.com/baresip/baresip/issues/3064

pipewire: lock loop while starting and registry scan

---

modules/gst/gst.c

There are code paths in `gst/gsc.c` which could lead to SEGVs. For example, if an audio file source is configured which does not exist: `audio_source  gst,/home/nonexistent.wav`.

gst: fix potential SEGVs in error cases

---

modules/mwi/mwi.c

mwi: use bevent_ua_emit()

---

src/call.c

Currently, I see the following incorrect behavior:
* No `UA_EVENT_CALL_REMOTE_SDP` is emtted if BareSIP receives an offer in an initial INVITE
* No `UA_EVENT_CALL_LOCAL_SDP` is emitted in `sipsess_offer_handler` when a local SDP is generated and sent
* A `CALL_EVENT_ANSWERED` is emitted in `sipsess_answer_handler` on re-INVITE even if the call is already established
So with this PR:
* Emit `UA_EVENT_CALL_REMOTE_SDP` if there is an offer in an initial INVITE
* Emit `UA_EVENT_CALL_LOCAL_SDP` in `sipsess_offer_handler` when local SDP is generated
* Do not emit `CALL_EVENT_ANSWERED` in `sipsess_answer_handler` if call is already established

call: fix emitting of call and ua events

---

modules/sndfile/sndfile.c

fixes: https://github.com/baresip/baresip/issues/3135
The main thread allocates and sets the filename and emits the
module event.

sndfile: module_event from main thread

---

src/rtprecv.c

`ENODATA` is never returned by `pass_pt_work();`

rtprecv: remove obsolete code

---

test/bevent.c

- Remove tests for deprecated functions.

bevent: avoid deprecated warnings in selftest

---

README.md

https://github.com/baresip/baresip/wiki/Supported-platforms

readme: sync with wiki

---

modules/menu/dynamic_menu.c

to allow explicit mute/unmute instead of just toggling

menu/dynamic_menu: add argument to mute command

---

modules/menu/static_menu.c

menu/static_menu: fix hangup SEGV

---

CMakeLists.txt

See: https://cliutils.gitlab.io/modern-cmake/chapters/basics.html

cmake: update min requirement and use range

---

src/video.c

Use designated initalizer to inialize vidframe struct.

video: initialize vidframe properly

---

modules/aaudio/player.c
modules/aaudio/recorder.c

aaudio modifications:
- set AAUDIO_PERFORMANCE_MODE_LOW_LATENCY for player and recorder
- set AAUDIO_INPUT_PRESET_VOICE_RECOGNITION for recorder
- fix typo in player module_event string
- added recorder buffer capacity and buffer size debug

aaudio: modifications

---

include/baresip.h
src/log.c

Improves usage if application is not build with HAVE_RE_ARG

log: refactor safe RE_ARG handling

---

src/call.c

call/call_event_handler: fix possible call NULL deref

---

src/call.c

and return 481 if no matching dialog is found as required by [RFC 3891 section 3](https://datatracker.ietf.org/doc/html/rfc3891#section-3).
Fixes #3304.

call: use call_find_replaces for finding call to replace

---

include/baresip.h
modules/contact/contact.c
modules/menu/menu.c
src/contact.c

- **contact: add/rm contacts via commands**
- **contact: add audio/video local direction**
- **contact: avoid duplicate contacts**
- **menu: apply contact media direction if specified**

contact commands

---

modules/portaudio/portaudio.c

* audio_source actually required an device index integer as reported by `baresip -v` and silently fell back to the default device for everything else. /ausrc however checked against the media registry, ie. accepted only long names based on the host backend and Portaudio device name. Called with such a name, it would still fall back to the default device. In other words `/ausrc portaudio` was totally broken.
* src_alloc() and play_alloc() should accept a name as stored in the media registry, ie. as reported by `baresip -v`. Additionally, it accepts "default" as is apparently supported by all the other audio modules. All other strings result in an error. This is good - you don't want the system to silently fall back to the default device after requesting a specific device.
* For instance, …

portaudio: fixed inconsistency between the device specification in audio_source and via /ausrc

---

src/mediadev.c

mediadev: fix mediadev_get_default

---

modules/audiounit/audiounit.c
modules/audiounit/audiounit.h

Fixes https://github.com/baresip/baresip/issues/3344
Suggested by @alfredh

audiounit: fix linking

---

modules/evdev/CMakeLists.txt

evdev: allowing evdev module compilation on FreeBSD

---

modules/debug_cmd/debug_cmd.c

```
/siptrace  # toggle on/off
/siptrace on # toggle on
/siptrace off # toggle off
```

debug: add siptrace debug cmd

---

src/call.c

According to RFC 3261 section 19.1.1. (Table 1), headers MUST NOT be present in a Request URI. Further, the URI in the Replaces header must be unescaped.

call: fix URI encoding in call_connect

---

modules/gzrtp/srtp.cpp
src/config.c

Fix to issue https://github.com/baresip/baresip/issues/3408.

gzrtp: increase mbuf size if about to run out

---

src/bevent.c

If a bevent handler calls `ua_hangup()` in order to terminate a call the
following bevent handlers get an invalid pointer. This leads to an
illegal memory access. Now an invalid call object pointer is detected
and the bevent forwarding is stopped.

bevent: ensure that pointer to call is valid

---

test/ua.c

@alfredh please have a look! I am unsure.

test: ua - fix index for domain_add
